
/* 
 * File:   _SCOLOR_GRP_DEF.h
 * Author: chi.hailong;
 *
 * Created on 2006年8月30日, 上午10:48
 *  SYN by hcl 2007.12.12
 */

#ifndef _COLOR_GRP_DEF_H
#define	_COLOR_GRP_DEF_H

#ifdef	__cplusplus
extern "C" {
#endif





#define MAX_COLOR_GRPS		64	/* max COLOR groups */
#define GRP_MAX_COLORS		16	/* max COLORS in a string group */
#define COLOR_GRP_NAME_LEN	20
#define CGRP_CELL_NAME_LEN	20
#define COLOR_GRP_WIDTH		32
#define COLOR_GRP_HEIGHT	   	32

#define	MAX_COLOR_PAIR		160	
#define	MAX_ALM_DSP_COLOR_PAIR		6
#define	DEFAULT_DSP_COLOR_PAIR		1

/*
typedef	struct
{
	int	clr[2];
}	COLOR_PAIR;
*/
GdkColor    pixels[MAX_CRT_NUMBER][MAXCOLORS];



#ifdef	COLOR_GROUP_DEF
COLOR_PAIR	clr_pair[MAX_COLOR_PAIR]	={
	BLACK1, BLACK2, 	BLACK1, BLACK3, 	BLACK1,	BLACK4, 	BLACK2,	BLACK4,
	GRAY1,	GRAY2, 		GRAY1,	GRAY3, 		GRAY1,	GRAY4, 		GRAY2,	GRAY4,
	GREEN1,	GREEN2, 	GREEN1,	GREEN3, 	GREEN1,	GREEN4, 	GREEN2,	GREEN4,
	L_GRN1,	L_GRN2, 	L_GRN1,	L_GRN3, 	L_GRN1,	L_GRN4, 	L_GRN2,	L_GRN4,
	BLUE1,	BLUE2, 		BLUE1,	BLUE3, 		BLUE1,	BLUE4, 		BLUE2,	BLUE4,
	L_BLUE1,L_BLUE2, 	L_BLUE1,L_BLUE3, 	L_BLUE1,L_BLUE4, 	L_BLUE2,L_BLUE4,
	RED1,	RED2, 		RED1,	RED3, 		RED1,	RED4, 		RED2,	RED4,
	L_RED1,	L_RED2, 	L_RED1,	L_RED3, 	L_RED1,	L_RED4, 	L_RED2,	L_RED4,
	YLW1,	YLW2, 		YLW1,	YLW3, 		YLW1,	YLW4, 		YLW2,	YLW4,
	L_YLW1,	L_YLW2, 	L_YLW1,	L_YLW3,	 	L_YLW1,	L_YLW4, 	L_YLW2,	L_YLW4,
	PINK1,	PINK2, 		PINK1,	PINK3, 		PINK1,	PINK4, 		PINK2,	PINK4,
	PURPLE1,PURPLE2, 	PURPLE1,PURPLE3, 	PURPLE1,PURPLE4, 	PURPLE2,PURPLE4,
	CHOCLT1,CHOCLT2, 	CHOCLT1,CHOCLT3, 	CHOCLT1,CHOCLT4, 	CHOCLT2,CHOCLT4,
	L_CHOCLT1,L_CHOCLT2, 	L_CHOCLT1,L_CHOCLT3, 	L_CHOCLT1,L_CHOCLT4, 	L_CHOCLT2,L_CHOCLT4,
	SEA_BLUE1,SEA_BLUE2, 	SEA_BLUE1,SEA_BLUE3, 	SEA_BLUE1,SEA_BLUE4, 	SEA_BLUE2,SEA_BLUE4,
	LEM_CHFN1,LEM_CHFN2, 	LEM_CHFN1,LEM_CHFN3, 	LEM_CHFN1,LEM_CHFN4, 	LEM_CHFN2,LEM_CHFN4,
	DK_BLUE1, DK_BLUE2,	DK_BLUE1,DK_BLUE3,	DK_BLUE2,DK_BLUE3,	DK_BLUE2,DK_BLUE4,
	DK_BLUE5,DK_BLUE6,	DK_BLUE5,DK_BLUE7,	DK_BLUE6,DK_BLUE7,	DK_BLUE6,DK_BLUE8,
	GRN_BLUE1,GRN_BLUE3,	GRN_BLUE2,GRN_BLUE3,	GRN_BLUE1,GRN_BLUE4,	GRN_BLUE2,GRN_BLUE4,
	GRN_BLUE5,GRN_BLUE7,	GRN_BLUE6,GRN_BLUE8,	GRN_BLUE7,GRN_BLUE8,	GRN_BLUE5,GRN_BLUE8,
	BL_PURPLE1,BL_PURPLE3,  BL_PURPLE2,BL_PURPLE4,  BL_PURPLE1,BL_PURPLE2,  BL_PURPLE3,BL_PURPLE4,
	BL_PURPLE5,BL_PURPLE6,  BL_PURPLE5,BL_PURPLE7,  BL_PURPLE6,BL_PURPLE7,  BL_PURPLE7,BL_PURPLE8,
	CLD_YLW1,CLD_YLW2,	CLD_YLW1,CLD_YLW3,	CLD_YLW2,CLD_YLW3,	CLD_YLW2,CLD_YLW4,
	CLD_GRY1,CLD_GRY2,	CLD_GRY1,CLD_GRY3,	CLD_GRY2,CLD_GRY4,	CLD_GRY1,CLD_GRY4,
	DK_RED1,DK_RED4,	DK_RED1,DK_RED3,	DK_RED2,DK_RED4,	DK_RED3,DK_RED4,
	DK_PINK1,DK_PINK4,	DK_PINK2,DK_PINK4,	DK_PINK3,DK_PINK1,	DK_PINK3,DK_PINK4,
	DK_PINK5,DK_PINK7,	DK_PINK6,DK_PINK7,	DK_PINK5,DK_PINK8,	DK_PINK6,DK_PINK8,
	C_GRN1,C_GRN3,		C_GRN1,C_GRN4,		C_GRN2,C_GRN4,		C_GRN2,C_GRN5,
	C_GRN5,C_GRN7,		C_GRN6,C_GRN8,		C_GRN5,C_GRN8,		C_GRN5,C_GRN6,
	C_GRN9,C_GRN11,		C_GRN9,C_GRN10,		C_GRN11,C_GRN12,	C_GRN10,C_GRN12,
	GROUND1,GROUND3,	GROUND2,GROUND4,	GROUND1,GROUND4,	GROUND2,GROUND3,
	GROUND5,GROUND1,	GROUND2,GROUND6,	GROUND7,GROUND3,	GROUND4,GROUND6,
	CASCAD_RED1, CASCAD_RED3, CASCAD_RED2, CASCAD_RED4, CASCAD_RED1, CASCAD_RED4, CASCAD_RED2, CASCAD_RED3,
	CASCAD_RED5, CASCAD_RED7, CASCAD_RED6, CASCAD_RED8, CASCAD_RED5, CASCAD_RED8, CASCAD_RED6, CASCAD_RED7,
	CASCAD_RED9, CASCAD_RED10, CASCAD_RED9, CASCAD_RED11, CASCAD_RED11, CASCAD_RED12, CASCAD_RED12, CASCAD_RED10,
	CASCAD_GRN1, CASCAD_GRN3, CASCAD_GRN2, CASCAD_GRN4, CASCAD_GRN1, CASCAD_GRN4, CASCAD_GRN2, CASCAD_GRN3,
	CASCAD_GRN5, CASCAD_GRN7, CASCAD_GRN6, CASCAD_GRN8, CASCAD_GRN6, CASCAD_GRN7, CASCAD_GRN5, CASCAD_GRN8,
	CASCAD_GRN9, CASCAD_GRN10, CASCAD_GRN9, CASCAD_GRN11, CASCAD_GRN10, CASCAD_GRN11, CASCAD_GRN11, CASCAD_GRN12,
	CASCAD_BLU1, CASCAD_BLU3, CASCAD_BLU2, CASCAD_BLU4,  CASCAD_BLU1, CASCAD_BLU4, CASCAD_BLU2, CASCAD_BLU3,
	CASCAD_BLU5, CASCAD_BLU7, CASCAD_BLU5, CASCAD_BLU8, CASCAD_BLU6, CASCAD_BLU7, CASCAD_BLU6, CASCAD_BLU8
};

/*COLOR_PAIR	alm_dsp_clr_pair[MAX_ALM_DSP_COLOR_PAIR]	= {
	BLACK2,	BLACK3,		GREEN2, GREEN4,		YLW2, YLW4,		RED2, RED4,
	GRAY2, GRAY4,		L_RED2,	L_RED4
};
*/
COLOR_PAIR	alm_dsp_clr_pair[MAX_ALM_DSP_COLOR_PAIR]	= {
	BLACK4, BLACK3,		GREEN2, GREEN4,		 YLW2, YLW4,		RED2, RED4,
	GRAY4, GRAY2,		PURPLE2, PURPLE4
};

COLOR_PAIR	red_cp	= { RED1, RED3 };
COLOR_PAIR	green_cp	= { GREEN, GREEN3 };
COLOR_PAIR	ylw_cp	= { YLW1, YLW3 };
COLOR_PAIR	white_cp	= { WHITE, GRAY2 };
COLOR_PAIR	l_red_cp	= { PURPLE1,PURPLE3  };

#else
extern	COLOR_PAIR	clr_pair[MAX_COLOR_PAIR];
extern	COLOR_PAIR	alm_dsp_clr_pair[MAX_ALM_DSP_COLOR_PAIR];

extern	COLOR_PAIR	red_cp;
extern	COLOR_PAIR	green_cp;
extern	COLOR_PAIR	ylw_cp;
extern	COLOR_PAIR	white_cp;
extern	COLOR_PAIR	l_red_cp;
#endif


typedef struct
{
	int			name;
	int			c_normal;
	int			flash;
}	CGRP_CELL;

typedef struct
{
	char		name[COLOR_GRP_NAME_LEN];
	CGRP_CELL	cgrp_cell[GRP_MAX_COLORS];
}	COLOR_GRP;

COLOR_GRP		cgdb[MAX_COLOR_GRPS];
int			cgdb_cnt;

#ifndef   	_COLOR_GRP_DEF_
#define	 	_COLOR_GRP_DEF_





#endif 




#ifdef	__cplusplus
}
#endif

#endif	/*  DEF_H */

