/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_dialog1 (void)
{
  GtkWidget *dialog1;
  GtkWidget *dialog_vbox1;
  GtkWidget *notebook2;
  GtkWidget *hbox17;
  GtkWidget *vbox14;
  GtkWidget *togglebutton1;
  GtkWidget *togglebutton2;
  GtkWidget *togglebutton3;
  GtkWidget *vbox15;
  GtkWidget *label40;
  GtkWidget *scrolledwindow20;
  GtkWidget *execuTview;
  GtkWidget *vbox16;
  GtkWidget *hbox19;
  GtkWidget *label50;
  GtkWidget *entry9;
  GtkWidget *entry10;
  GtkWidget *hbox20;
  GtkWidget *label51;
  GtkWidget *entry11;
  GtkWidget *hbox21;
  GtkWidget *label52;
  GtkWidget *entry12;
  GtkWidget *hbox22;
  GtkWidget *button19;
  GtkWidget *button20;
  GtkWidget *button21;
  GtkWidget *label32;
  GtkWidget *scrolledwindow11;
  GtkWidget *viewport1;
  GtkWidget *table3;
  GtkWidget *hbox23;
  GtkWidget *addgrp;
  GtkWidget *delgrp;
  GtkWidget *savegrp;
  GtkWidget *canclegrp;
  GtkWidget *hbox24;
  GtkWidget *hbox25;
  GtkWidget *addpot;
  GtkWidget *delpot;
  GtkWidget *label59;
  GtkWidget *scrolledwindow19;
  GtkWidget *creategrptview;
  GtkWidget *scrolledwindow21;
  GtkWidget *pointtview;
  GtkWidget *label33;
  GtkWidget *table2;
  GtkWidget *label47;
  GtkWidget *entry5;
  GtkWidget *label48;
  GtkWidget *entry6;
  GtkWidget *label49;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *label34;
  GtkWidget *scrolledwindow18;
  GtkWidget *textview3;
  GtkWidget *label63;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  dialog1 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog1), _("dialog1"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog1), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (dialog1)->vbox;
  gtk_widget_show (dialog_vbox1);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), notebook2, TRUE, TRUE, 0);

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (notebook2), hbox17);

  vbox14 = gtk_vbox_new (TRUE, 0);
  gtk_widget_show (vbox14);
  gtk_box_pack_start (GTK_BOX (hbox17), vbox14, TRUE, TRUE, 0);

  togglebutton1 = gtk_toggle_button_new_with_mnemonic (_("\344\272\244\347\217\255\345\267\241\346\243\200"));
  gtk_widget_show (togglebutton1);
  gtk_box_pack_start (GTK_BOX (vbox14), togglebutton1, FALSE, FALSE, 0);
  gtk_widget_set_size_request (togglebutton1, -1, 50);

  togglebutton2 = gtk_toggle_button_new_with_mnemonic (_("\347\217\255\345\206\205\345\256\232\346\227\266\345\267\241\346\243\200"));
  gtk_widget_show (togglebutton2);
  gtk_box_pack_start (GTK_BOX (vbox14), togglebutton2, FALSE, FALSE, 0);
  gtk_widget_set_size_request (togglebutton2, -1, 50);

  togglebutton3 = gtk_toggle_button_new_with_mnemonic (_("\350\207\252\345\256\232\344\271\211\345\267\241\346\243\200"));
  gtk_widget_show (togglebutton3);
  gtk_box_pack_start (GTK_BOX (vbox14), togglebutton3, FALSE, FALSE, 0);
  gtk_widget_set_size_request (togglebutton3, -1, 50);

  vbox15 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox15);
  gtk_box_pack_start (GTK_BOX (hbox17), vbox15, TRUE, TRUE, 0);

  label40 = gtk_label_new (_("\345\210\206\347\273\204"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (vbox15), label40, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label40, -1, 25);

  scrolledwindow20 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow20);
  gtk_box_pack_start (GTK_BOX (vbox15), scrolledwindow20, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow20), GTK_SHADOW_IN);

  execuTview = gtk_tree_view_new ();
  gtk_widget_show (execuTview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow20), execuTview);
  gtk_widget_set_size_request (execuTview, -1, 441);

  vbox16 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox16);
  gtk_box_pack_start (GTK_BOX (vbox15), vbox16, TRUE, TRUE, 0);

  hbox19 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox19);
  gtk_box_pack_start (GTK_BOX (vbox16), hbox19, TRUE, TRUE, 0);

  label50 = gtk_label_new (_("\350\265\267\345\247\213\346\227\266\351\227\264"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox19), label50, FALSE, FALSE, 0);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_box_pack_start (GTK_BOX (hbox19), entry9, TRUE, TRUE, 0);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_box_pack_start (GTK_BOX (hbox19), entry10, TRUE, TRUE, 0);

  hbox20 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox20);
  gtk_box_pack_start (GTK_BOX (vbox16), hbox20, TRUE, TRUE, 0);

  label51 = gtk_label_new (_("\345\267\241\346\243\200\345\221\250\346\234\237"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox20), label51, FALSE, FALSE, 0);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_box_pack_start (GTK_BOX (hbox20), entry11, TRUE, TRUE, 0);

  hbox21 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox21);
  gtk_box_pack_start (GTK_BOX (vbox16), hbox21, TRUE, TRUE, 0);

  label52 = gtk_label_new (_("\346\227\266\351\227\264\350\214\203\345\233\264"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox21), label52, FALSE, FALSE, 0);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_box_pack_start (GTK_BOX (hbox21), entry12, TRUE, TRUE, 0);

  hbox22 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox22);
  gtk_box_pack_start (GTK_BOX (vbox16), hbox22, TRUE, TRUE, 0);

  button19 = gtk_button_new_with_mnemonic (_("\346\222\244\351\224\200"));
  gtk_widget_show (button19);
  gtk_box_pack_start (GTK_BOX (hbox22), button19, FALSE, FALSE, 0);
  gtk_widget_set_size_request (button19, 100, -1);

  button20 = gtk_button_new_with_mnemonic (_("\347\241\256\345\256\232"));
  gtk_widget_show (button20);
  gtk_box_pack_start (GTK_BOX (hbox22), button20, FALSE, FALSE, 0);
  gtk_widget_set_size_request (button20, 100, -1);

  button21 = gtk_button_new_with_mnemonic (_("\344\277\235\345\255\230"));
  gtk_widget_show (button21);
  gtk_box_pack_start (GTK_BOX (hbox22), button21, FALSE, FALSE, 0);
  gtk_widget_set_size_request (button21, 100, -1);

  label32 = gtk_label_new (_("\345\267\241\346\243\200\351\205\215\347\275\256"));
  gtk_widget_show (label32);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label32);

  scrolledwindow11 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow11);
  gtk_container_add (GTK_CONTAINER (notebook2), scrolledwindow11);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow11), GTK_POLICY_NEVER, GTK_POLICY_NEVER);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow11), GTK_SHADOW_IN);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow11), viewport1);

  table3 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (viewport1), table3);

  hbox23 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox23);
  gtk_table_attach (GTK_TABLE (table3), hbox23, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  addgrp = gtk_button_new_with_mnemonic (_("\346\267\273\345\212\240\345\210\206\347\273\204"));
  gtk_widget_show (addgrp);
  gtk_box_pack_start (GTK_BOX (hbox23), addgrp, FALSE, FALSE, 0);

  delgrp = gtk_button_new_with_mnemonic (_("\345\210\240\351\231\244\345\210\206\347\273\204"));
  gtk_widget_show (delgrp);
  gtk_box_pack_start (GTK_BOX (hbox23), delgrp, FALSE, FALSE, 0);

  savegrp = gtk_button_new_with_mnemonic (_("  \344\277\235\345\255\230  "));
  gtk_widget_show (savegrp);
  gtk_box_pack_start (GTK_BOX (hbox23), savegrp, FALSE, FALSE, 0);

  canclegrp = gtk_button_new_with_mnemonic (_("  \345\217\226\346\266\210  "));
  gtk_widget_show (canclegrp);
  gtk_box_pack_start (GTK_BOX (hbox23), canclegrp, FALSE, FALSE, 0);

  hbox24 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox24);
  gtk_table_attach (GTK_TABLE (table3), hbox24, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox25 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox25);
  gtk_table_attach (GTK_TABLE (table3), hbox25, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  addpot = gtk_button_new_with_mnemonic (_("\346\267\273\345\212\240\347\202\271"));
  gtk_widget_show (addpot);
  gtk_box_pack_start (GTK_BOX (hbox25), addpot, FALSE, FALSE, 0);

  delpot = gtk_button_new_with_mnemonic (_("\345\210\240\351\231\244\347\202\271"));
  gtk_widget_show (delpot);
  gtk_box_pack_start (GTK_BOX (hbox25), delpot, FALSE, FALSE, 0);

  label59 = gtk_label_new (_("\345\210\206\347\273\204\345\256\232\344\271\211"));
  gtk_widget_show (label59);
  gtk_table_attach (GTK_TABLE (table3), label59, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label59, -1, 25);
  gtk_misc_set_alignment (GTK_MISC (label59), 0, 0.5);

  scrolledwindow19 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow19);
  gtk_table_attach (GTK_TABLE (table3), scrolledwindow19, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow19), GTK_SHADOW_IN);

  creategrptview = gtk_tree_view_new ();
  gtk_widget_show (creategrptview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow19), creategrptview);
  gtk_widget_set_size_request (creategrptview, -1, 540);

  scrolledwindow21 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow21);
  gtk_table_attach (GTK_TABLE (table3), scrolledwindow21, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow21), GTK_SHADOW_IN);

  pointtview = gtk_tree_view_new ();
  gtk_widget_show (pointtview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow21), pointtview);

  label33 = gtk_label_new (_("\345\267\241\346\243\200\347\273\204\351\205\215\347\275\256"));
  gtk_widget_show (label33);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label33);

  table2 = gtk_table_new (3, 3, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (notebook2), table2);

  label47 = gtk_label_new (_("\350\265\267\345\247\213\346\227\266\351\227\264"));
  gtk_widget_show (label47);
  gtk_table_attach (GTK_TABLE (table2), label47, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label47, -1, 25);
  gtk_misc_set_alignment (GTK_MISC (label47), 0, 0.5);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_table_attach (GTK_TABLE (table2), entry5, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry5, -1, 25);

  label48 = gtk_label_new (_("\350\207\252\345\212\250\350\277\220\350\241\214\345\221\250\346\234\237"));
  gtk_widget_show (label48);
  gtk_table_attach (GTK_TABLE (table2), label48, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label48, -1, 25);
  gtk_misc_set_alignment (GTK_MISC (label48), 0, 0.5);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_table_attach (GTK_TABLE (table2), entry6, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry6, -1, 25);

  label49 = gtk_label_new (_("\346\227\266\351\227\264\350\214\203\345\233\264"));
  gtk_widget_show (label49);
  gtk_table_attach (GTK_TABLE (table2), label49, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label49, -1, 25);
  gtk_misc_set_alignment (GTK_MISC (label49), 0, 0.5);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_table_attach (GTK_TABLE (table2), entry7, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry7, -1, 25);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_table_attach (GTK_TABLE (table2), entry8, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry8, -1, 25);

  label34 = gtk_label_new (_("label3"));
  gtk_widget_show (label34);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label34);

  scrolledwindow18 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow18);
  gtk_container_add (GTK_CONTAINER (notebook2), scrolledwindow18);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow18), GTK_SHADOW_IN);

  textview3 = gtk_text_view_new ();
  gtk_widget_show (textview3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow18), textview3);

  label63 = gtk_label_new (_("label63"));
  gtk_widget_show (label63);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 3), label63);

  dialog_action_area1 = GTK_DIALOG (dialog1)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) addgrp, "clicked",
                    G_CALLBACK (on_addgrp_clicked),
                    NULL);
  g_signal_connect ((gpointer) delgrp, "clicked",
                    G_CALLBACK (on_delgrp_clicked),
                    NULL);
  g_signal_connect ((gpointer) savegrp, "clicked",
                    G_CALLBACK (on_savegrp_clicked),
                    NULL);
  g_signal_connect ((gpointer) canclegrp, "clicked",
                    G_CALLBACK (on_canclegrp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog1, "dialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog1, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (dialog1, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (dialog1, vbox14, "vbox14");
  GLADE_HOOKUP_OBJECT (dialog1, togglebutton1, "togglebutton1");
  GLADE_HOOKUP_OBJECT (dialog1, togglebutton2, "togglebutton2");
  GLADE_HOOKUP_OBJECT (dialog1, togglebutton3, "togglebutton3");
  GLADE_HOOKUP_OBJECT (dialog1, vbox15, "vbox15");
  GLADE_HOOKUP_OBJECT (dialog1, label40, "label40");
  GLADE_HOOKUP_OBJECT (dialog1, scrolledwindow20, "scrolledwindow20");
  GLADE_HOOKUP_OBJECT (dialog1, execuTview, "execuTview");
  GLADE_HOOKUP_OBJECT (dialog1, vbox16, "vbox16");
  GLADE_HOOKUP_OBJECT (dialog1, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (dialog1, label50, "label50");
  GLADE_HOOKUP_OBJECT (dialog1, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (dialog1, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (dialog1, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (dialog1, label51, "label51");
  GLADE_HOOKUP_OBJECT (dialog1, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (dialog1, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (dialog1, label52, "label52");
  GLADE_HOOKUP_OBJECT (dialog1, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (dialog1, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (dialog1, button19, "button19");
  GLADE_HOOKUP_OBJECT (dialog1, button20, "button20");
  GLADE_HOOKUP_OBJECT (dialog1, button21, "button21");
  GLADE_HOOKUP_OBJECT (dialog1, label32, "label32");
  GLADE_HOOKUP_OBJECT (dialog1, scrolledwindow11, "scrolledwindow11");
  GLADE_HOOKUP_OBJECT (dialog1, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (dialog1, table3, "table3");
  GLADE_HOOKUP_OBJECT (dialog1, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (dialog1, addgrp, "addgrp");
  GLADE_HOOKUP_OBJECT (dialog1, delgrp, "delgrp");
  GLADE_HOOKUP_OBJECT (dialog1, savegrp, "savegrp");
  GLADE_HOOKUP_OBJECT (dialog1, canclegrp, "canclegrp");
  GLADE_HOOKUP_OBJECT (dialog1, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (dialog1, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (dialog1, addpot, "addpot");
  GLADE_HOOKUP_OBJECT (dialog1, delpot, "delpot");
  GLADE_HOOKUP_OBJECT (dialog1, label59, "label59");
  GLADE_HOOKUP_OBJECT (dialog1, scrolledwindow19, "scrolledwindow19");
  GLADE_HOOKUP_OBJECT (dialog1, creategrptview, "creategrptview");
  GLADE_HOOKUP_OBJECT (dialog1, scrolledwindow21, "scrolledwindow21");
  GLADE_HOOKUP_OBJECT (dialog1, pointtview, "pointtview");
  GLADE_HOOKUP_OBJECT (dialog1, label33, "label33");
  GLADE_HOOKUP_OBJECT (dialog1, table2, "table2");
  GLADE_HOOKUP_OBJECT (dialog1, label47, "label47");
  GLADE_HOOKUP_OBJECT (dialog1, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (dialog1, label48, "label48");
  GLADE_HOOKUP_OBJECT (dialog1, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (dialog1, label49, "label49");
  GLADE_HOOKUP_OBJECT (dialog1, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (dialog1, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (dialog1, label34, "label34");
  GLADE_HOOKUP_OBJECT (dialog1, scrolledwindow18, "scrolledwindow18");
  GLADE_HOOKUP_OBJECT (dialog1, textview3, "textview3");
  GLADE_HOOKUP_OBJECT (dialog1, label63, "label63");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog1, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (dialog1, okbutton1, "okbutton1");

  return dialog1;
}

