/*-----------------------------------------------------------------------
	
	Upadate from X11 to GTK ;
	Created by chi.hailong
	Date : 2006.4.8 
     

---------------------------------------------------------------------*/



#ifndef   _GTK_SCALER_H 
#define   _GTK_SCALER_H 
#define  OLDWIDTH	1256			// ALTHA whole window width and height
#define  OLDHEIGHT	  936
 
#define  LOCAL_WIDTH	1016    	 
#define	 LOCAL_HEIGHT  	 706   


#define  STD_WIDTH	    1256   	 
#define	 STD_HEIGHT  	 962
  
 

float	xscale, yscale;	

#define	POINT_OFFSET  2	// mouse drag distance (pixel)

#endif