package com.bitc.jk.xmis.dao.impl;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.PreparedStatementCallback;

import com.bitc.jk.xmis.dao.DevelopProgressDAO;

public class DevelopProgressDAOImpl implements DevelopProgressDAO {

	private JdbcTemplate jt;

	public List getDevelopProgressList() {
		final String sql = "select model.业务模块ID ,model.业务模块名称 ,RTRIM(modelhr.姓氏) + RTRIM(modelhr.名字) as 业务模块提交人 ,model.提交时间 as 业务模块提交时间 ,submodel.业务子模块ID ,submodel.业务子模块名称 ,RTRIM(submodelhr.姓氏) + RTRIM(submodelhr.名字) as 业务子模块提交人 ,submodel.提交时间 as 业务子模块提交时间 ,submodel.提交状态 as 业务子模块提交状态ID ,submodelstatus.状态名称 as 业务子模块提交状态 ,modfuncmapping.业务功能ID ,model.业务模块排位序号 ,modmapping.业务子模块排列顺序"
				+ " into #temp1"
				+ " FROM  xmis.sec_业务模块表 as model ,xmis.sec_业务模块对应表 as modmapping ,xmis.sec_业务子模块表 as submodel ,xmis.sec_业务模块功能对应表 as modfuncmapping ,xmis.hr_人员 as modelhr ,xmis.hr_人员 as submodelhr ,xmis.sys_状态 as submodelstatus "
				+ " where  model.业务模块ID<>7 "
				+ " and model.业务模块ID = modmapping.业务模块ID  "
				+ " and modmapping.业务子模块ID=submodel.业务子模块ID "
				+ " and submodel.业务子模块ID *= modfuncmapping.业务子模块ID "
				+ " and submodel.提交状态 *= submodelstatus.状态ID "
				+ " and model.提交人*=modelhr.人员ID and submodel.提交人*=submodelhr.人员ID "
				+ " select func.业务功能ID ,func.业务功能名称 ,RTRIM(funchr.姓氏) + RTRIM(funchr.名字) as 业务功能提交人 ,func.提交时间 as 业务功能提交时间 ,func.提交状态 as 业务功能提交状态ID ,funcstatus.状态名称 as 业务功能提交状态 "
				+ " into #temp2"
				+ " from xmis.sec_业务功能表 as func ,xmis.hr_人员 as funchr ,xmis.sys_状态 as funcstatus "
				+ " where func.提交人 *= funchr.人员ID and func.提交状态 *= funcstatus.状态ID "
				+ "  select temp1.业务模块ID "
				+ "  ,temp1.业务模块名称 "
				+ "  ,temp1.业务模块提交人  "
				+ "  ,temp1.业务模块提交时间  "
				+ "  ,temp1.业务模块ID * 100 + temp1.业务子模块ID  as 业务子模块ID "
				+ "  ,temp1.业务子模块名称 "
				+ "  ,temp1.业务子模块提交人  "
				+ "  ,temp1.业务子模块提交时间 "
				+ "  ,temp1.业务子模块提交状态ID "
				+ "  ,temp1.业务子模块提交状态 "
				+ "  ,temp1.业务功能ID "
				+ "  ,temp1.业务模块排位序号 "
				+ "  ,temp1.业务子模块排列顺序 "
				+ " ,temp2.业务功能名称 as 业务功能名称 "
				+ "  ,temp2.业务功能提交人 as 业务功能提交人 "
				+ "  ,temp2.业务功能提交时间 as 业务功能提交时间  "
				+ " ,temp2.业务功能提交状态ID as 业务功能提交状态ID "
				+ " ,temp2.业务功能提交状态 as 业务功能提交状态  "
				+ " from  #temp1 as temp1 "
				+ " ,#temp2 as temp2 "
				+ " where temp1.业务功能ID *=temp2.业务功能ID "
				+ "  order by temp1.业务模块排位序号,temp1.业务子模块排列顺序,temp1.业务功能ID ";
		List alist = (List) jt.execute(sql, new PreparedStatementCallback() {
			public Object doInPreparedStatement(PreparedStatement arg0)
					throws SQLException, DataAccessException {
				ResultSet rs = arg0.executeQuery();
				List list = new ArrayList();
				ResultSetMetaData md = rs.getMetaData();
				int columnCount = md.getColumnCount();
				while (rs.next()) {
					Map map = new HashMap();
					for (int i = 1; i <= columnCount; i++) {
						map.put(md.getColumnName(i), rs.getObject(i));
					}
					list.add(map);
				}
				return list;
			}
		});
		return alist;
	}
	
	public List getMonthAccounting(String start, String end,String sort) {
		//默认月报
		String hsql = " SET NOCOUNT ON declare @beginDate varchar(7) --开始日期 \n"
		  + " declare @endDate varchar(7)   --结束日期 \n"
		  + " declare @betweenMonth int   --结束日期与当前日期之间相差的月数 \n"
		  + " declare @sortDate varchar(7)   --排序 \n"
		  + " set @beginDate= ? \n"
		  + " set @endDate= ? \n"
		  + " set @sortDate= ? \n"
		  + " SELECT 公司ID \n"
		  + " ,xmis.org_部门归属公司表.部门ID \n"
		  + " ,xmis.org_部门.部门名称 \n"
		  + " ,排序 \n"
		  + " into #d \n"
		  + " FROM xmis.org_部门归属公司表,xmis.org_部门 \n"
		  + " where 公司ID = 1 and 是否直属 = 1 \n"
		  + " and xmis.org_部门归属公司表.部门ID = xmis.org_部门.部门ID \n"
		  + " and xmis.org_部门.部门ID <> 504 \n"
		  + " select xmis.sys_系统日志.id \n"
		  + " ,xmis.sys_系统日志.userID \n"
		  + " ,xmis.sys_系统日志.opTime \n"
		  + " ,convert(varchar(7),xmis.sys_系统日志.opTime,120) as loginmonth \n"
		  + " ,xmis.hr_人员部门关系表.部门ID as subDeptID \n"
		  + " into #history \n"
		  + " from xmis.sys_系统日志,xmis.hr_人员部门关系表,xmis.hr_人员 \n"
		  + " where userID<>-1 and opType = 'login' and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID \n"
		  + " and xmis.sys_系统日志.userID = xmis.hr_人员.人员ID \n"
		  + " AND (xmis.hr_人员.禁用 is null or xmis.hr_人员.禁用= 0)   \n"
		  + " union all \n"
		  + " select xmis.sys_系统日志.id \n"
		  + " ,xmis.sys_系统日志.userID \n"
		  + " ,xmis.sys_系统日志.opTime \n"
		  + " ,convert(varchar(7),xmis.sys_系统日志.opTime,120) as loginmonth \n"
		  + " ,xmis.hr_人员部门关系表.部门ID as subDeptID \n"
		  + " from xmis.sys_系统日志,xmis.hr_人员部门关系表,xmis.hr_人员 \n"
		  + " where userID<>-1 and (opType = 'timeout' or opType = 'loginout') and opTime>='2011-10-01' and opTime<'2012-06-01' and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID \n"
		  + " and xmis.sys_系统日志.userID = xmis.hr_人员.人员ID \n"
		  + " AND (xmis.hr_人员.禁用 is null or xmis.hr_人员.禁用= 0)   \n"
		  + " select #history.* \n"
		  + " ,case when xmis.org_部门归属部门表.父部门ID IS null then #history.subDeptID else xmis.org_部门归属部门表.父部门ID end as deptID \n"
		  + " into #history2 \n"
		  + " from #history,xmis.org_部门归属部门表 \n"
		  + " where #history.subDeptID *= xmis.org_部门归属部门表.部门ID \n"
		  + " and loginmonth>=@beginDate  \n"
		  + " and loginmonth<=@endDate \n"
		  + " select #history2.deptID,loginmonth,COUNT(*) as total \n"
		  + " into #re \n"
		  + " from #history2 \n"
		  + " group by deptID,loginmonth \n"
		  + " --根据开始日期和结束日期及当前日期，查找所有月份 \n"
		  + " DECLARE @today VARCHAR(10) \n"
		  + " SELECT @today = CONVERT(VARCHAR(7),GETDATE(),120) + '-01' \n"
		  + " select convert(varchar(7),null,120) as loginmonth into #months where 1=2   \n"
		  + " declare @tdate datetime   \n"
		  + " set @tdate = @beginDate + '-01'   \n"
		  + " IF @tdate < '2011-08-01' BEGIN \n"
		  + " 	SET @tdate = '2011-08-01' \n"
		  + " END \n"
		  + " while(@tdate <= @endDate + '-01' AND @tdate <= @today) begin    \n"
		  + "     insert into #months select convert(varchar(7),@tdate,120)   \n"
		  + "     set @tdate = DATEADD(MONTH,1,@tdate) \n"
		  + " end   \n"
		  + " select identity(int,0,1) as row_no,#months.loginmonth into #allMonth from #months  \n"
		  + " ----------------------------------------------- \n"
		  + " declare @count int \n"
		  + " select @count = count(*) from #allMonth \n"
		  + " declare @i int \n"
		  + " set @i = 0 \n"
		  + " while(@i < @count) \n"
		  + " begin \n"
		  + " 	declare @yearAndMonth varchar(7) \n"
		  + " 	select @yearAndMonth = loginmonth from #allMonth where row_no = @i \n"
		  + " 	insert into #re select #d.部门ID,@yearAndMonth,0 from #d where #d.部门ID not in (select #re.deptID from #re where loginmonth = @yearAndMonth) \n"
		  + " 	set @i = @i + 1 \n"
		  + " end \n"
		  + " select #re.*,#d.部门名称 as deptName,#d.排序 as deptPx \n"
		  + " into #result \n"
		  + " from #re,#d  \n"
		  + " where #re.deptID = #d.部门ID \n"
		  + " order by loginmonth asc,total desc,deptPx \n"
		  
		  + " select * into #pxtemp from #result where 1=2  \n"
		  + " if(@sortDate = '小计') begin   \n"
		  + " 	insert into #pxtemp select deptID,'小计',SUM(total),deptName,0 from #result group by deptID,deptName  \n"
		  + " end  \n"
		  + " else begin  \n"
		  + " 	insert into #pxtemp select * from #result where loginmonth = @sortDate \n"
		  + " end \n"
		  
		  + " select identity(int,1,1) as row_no,*  \n"
		  + " into #px \n"
		  + " from #pxtemp    \n"
//		  + " where loginmonth = @sortDate \n"
		  + " order by total desc,deptPX \n"
		  + " update #result set #result.deptPx = #px.row_no from #result,#px where #result.deptID = #px.deptID \n"
		  + " select 99999 as deptID,loginmonth,SUM(total) as total,'合计' as deptName,99999 as deptPx into #totalTemp from #result group by loginmonth \n"
		  + " union all  \n"
		  + " select deptID,'小计',SUM(total),deptName,99999 from #result group by deptID,deptName \n"
		  + " union all \n"
		  + " select 99999,'小计',SUM(total),'合计',99999 from #result \n"
		  + " insert into #result select * from #totalTemp \n"
		  + " update #result set #result.deptPx = #px.row_no from #result,#px where #result.deptID = #px.deptID and #result.loginmonth = '小计' \n"
		  //+ " select * from #result order by loginmonth,deptPx\n";
		  + " select * \n"
		  + " ,case when SUBSTRING(loginmonth,1,4)='小计' then '<div style=\"display:none;\">2222</div>' else SUBSTRING(loginmonth,1,4) end as year \n"
		  + " ,case when SUBSTRING(loginmonth,6,2)='' then '小计' else SUBSTRING(loginmonth,6,2) end as month from #result \n";
//		  + " union all \n"
//		  + " select * from #totalTemp "
		System.out.println(hsql);
		return jt.queryForList(hsql, new Object[]{start,end,sort});
	}

	public List getMonthAccounting(String start, String end,String sort,String deptName) {
		String hsql = "SET NOCOUNT ON \n" 
			+ " declare @beginDate varchar(7) --开始日期  \n"
			+ " declare @endDate varchar(7)   --结束日期 \n"
			+ " declare @betweenMonth int   --结束日期与当前日期之间相差的月数  \n"
			+ " declare @sortDate varchar(7)   --排序 \n"
			+ " set @beginDate= ? \n"
			+ " set @endDate= ? \n"
			+ " set @sortDate=? \n"
			+ " declare @deptName varchar(100) --部门名称 \n"
			+ " declare @deptID int --部门名称 \n"
			+ " set @deptName= ? \n"
			+ " SELECT @deptID=comp.部门ID \n"
			+ " FROM xmis.org_部门归属公司表 as comp,xmis.org_部门 as dept \n"
			+ " where comp.公司ID = 1 and dept.部门ID = comp.部门ID \n"
			+ " and dept.部门名称 = @deptName \n"
			+ " SELECT dh.人员ID \n"
			+ "   ,dh.部门ID \n"
			+ "   ,RTRIM(hr.姓氏) + RTRIM(hr.名字) as userName \n"
			+ " into #user \n"
			+ " FROM xmis.hr_人员部门关系表 as dh,xmis.hr_人员 hr \n"
			+ " where dh.部门ID = @deptID \n"
			+ " and dh.人员ID = hr.人员ID \n"
			+ " and hr.人员ID > 0 AND (hr.禁用 is null or hr.禁用= 0) \n"
			+ " select xmis.sys_系统日志.id  \n"
			+ " ,xmis.sys_系统日志.userID  \n"
			+ " ,xmis.sys_系统日志.opTime  \n"
			+ " ,convert(varchar(7),xmis.sys_系统日志.opTime,120) as loginmonth  \n"
			+ " ,xmis.hr_人员部门关系表.部门ID as subDeptID  \n"
			+ " into #history  \n"
			+ " from xmis.sys_系统日志,xmis.hr_人员部门关系表  \n"
			+ " where userID<>-1  \n"
			+ " and opType = 'login'  \n"
			+ " and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID  \n"
			+ " and xmis.hr_人员部门关系表.部门ID = @deptID \n"
			+ " union all  \n"
			+ " select xmis.sys_系统日志.id  \n"
			+ " ,xmis.sys_系统日志.userID  \n"
			+ " ,xmis.sys_系统日志.opTime  \n"
			+ " ,convert(varchar(7),xmis.sys_系统日志.opTime,120) as loginmonth  \n"
			+ " ,xmis.hr_人员部门关系表.部门ID as subDeptID  \n"
			+ " from xmis.sys_系统日志,xmis.hr_人员部门关系表  \n"
			+ " where userID<>-1  \n"
			+ " and (opType = 'timeout' or opType = 'loginout')  \n"
			+ " and opTime>='2011-10-01'  \n"
			+ " and opTime<'2012-06-01'  \n"
			+ " and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID  \n"
			+ " and xmis.hr_人员部门关系表.部门ID = @deptID \n"
			+ " select #history.*  \n"
			+ " ,case when xmis.org_部门归属部门表.父部门ID IS null then #history.subDeptID else xmis.org_部门归属部门表.父部门ID end as deptID  \n"
			+ " into #history2  \n"
			+ " from #history,xmis.org_部门归属部门表  \n"
			+ " where #history.subDeptID *= xmis.org_部门归属部门表.部门ID  \n"
			+ " and loginmonth>=@beginDate   \n"
			+ " and loginmonth<=@endDate \n"
			+ " select #history2.userID,loginmonth,COUNT(*) as total  \n"
			+ " into #re  \n"
			+ " from #history2  \n"
			+ " group by userID,loginmonth  \n"
			
			/*
			+ "  select convert(varchar(7),null,120) as loginmonth into #months where 1=2  \n"
			+ "  declare @tdate datetime  \n"
			+ "  set @tdate = @beginDate + '-01'  \n"
			+ "  while(@tdate <= @endDate + '-01') begin   \n"
			+ "      insert into #months select convert(varchar(7),@tdate,120)  \n"
			+ "      set @tdate = DATEADD(MONTH,1,@tdate)  \n"
			+ "  end  \n"
			 
			+ "  --得到所有月份 \n"
			+ " select identity(int,0,1) as row_no,#months.loginmonth into #allMonth from #months  \n"
			*/
			
			+ " --根据开始日期和结束日期及当前日期，查找所有月份 \n"
			+ " DECLARE @today VARCHAR(10) \n"
			+ " SELECT @today = CONVERT(VARCHAR(7),GETDATE(),120) + '-01' \n"
			+ " select convert(varchar(7),null,120) as loginmonth into #months where 1=2   \n"
			+ " declare @tdate datetime   \n"
			+ " set @tdate = @beginDate + '-01'   \n"
			+ " IF @tdate < '2011-08-01' BEGIN \n"
			+ " 	SET @tdate = '2011-08-01' \n"
			+ " END \n"
			+ " while(@tdate <= @endDate + '-01' AND @tdate <= @today) begin    \n"
			+ "     insert into #months select convert(varchar(7),@tdate,120)   \n"
			+ "     set @tdate = DATEADD(MONTH,1,@tdate) \n"
			+ " end   \n"
			+ " select identity(int,0,1) as row_no,#months.loginmonth into #allMonth from #months  \n"
			+ " ----------------------------------------------- \n"
			
			+ " declare @count int  \n"
			+ " select @count = count(*) from #allMonth  \n"
			+ " declare @i int  \n"
			+ " set @i = 0  \n"
			+ " while(@i < @count)  \n"
			+ "  begin  \n"
			+ " declare @yearAndMonth varchar(7)  \n"
			+ " select @yearAndMonth = loginmonth from #allMonth where row_no = @i  \n"
			+ " insert into #re select #user.人员ID,@yearAndMonth,0 from #user where #user.人员ID not in (select #re.userID from #re where loginmonth = @yearAndMonth)  \n"
			+ " set @i = @i + 1  \n"
			+ " end  \n"
			+ " select #re.*,#user.userName as userName,0 as userPx  \n"
			+ " into #result  \n"
			+ " from #re,#user \n"
			+ " where #re.userID = #user.人员ID  \n"
			
			+ " select * into #pxtemp from #result where 1=2   \n"
			+ "  if(@sortDate = '小计') begin    \n"
			+ "  	insert into #pxtemp select userID,'小计',SUM(total),userName,0 from #result group by userID,userName    \n"
			+ "  end   \n"
			+ "  else begin   \n"
			+ "  	insert into #pxtemp select * from #result where loginmonth = @sortDate   \n"
			+ "  end   \n"
			
			+ " select identity(int,1,1) as row_no,*   \n"
			+ " into #px  \n"
			+ " from #pxtemp   \n"
			+ " order by total desc \n"
			+ " update #result set #result.userPx = #px.row_no from #result,#px where #result.userID = #px.userID  \n"
			+ " select 99999 as userID,loginmonth,SUM(total) as total,'合计' as userName,99999 as userPx into #totalTemp from #result group by loginmonth  \n"
			+ " union all   \n"
			+ " select userID,'小计',SUM(total),userName,99999 from #result group by userID,userName  \n"
			+ " union all  \n"
			+ " select 99999,'小计',SUM(total),'合计',99999 from #result  \n"
			+ " insert into #result select * from #totalTemp  \n"
			+ " update #result set #result.userPx = #px.row_no from #result,#px where #result.userID = #px.userID and #result.loginmonth = '小计'  \n"
			+ " select *  \n"
			+ " ,case when SUBSTRING(loginmonth,1,4)='小计' then '<div style=\"display:none;\">2222</div>' else SUBSTRING(loginmonth,1,4) end as year \n"
			+ " ,case when SUBSTRING(loginmonth,6,2)='' then '小计' else SUBSTRING(loginmonth,6,2) end as month from #result  \n";
		 System.out.println(hsql);
		return jt.queryForList(hsql, new Object[]{start,end,sort,deptName});
	}
	
	public JdbcTemplate getJt() {
		return jt;
	}

	public void setJt(JdbcTemplate ajdbcTemplate) {
		this.jt = ajdbcTemplate;
	}

	public List getMonthAccounting(String start, String end, String sort,
			int deptID) {
		String sql = " SET NOCOUNT ON \n" 
			+ " declare @currentMonth varchar(7) \n"
			+ " declare @endMonth varchar(7) \n"
			+ " declare @beginDate varchar(10) --开始日期   \n"
			+ " declare @endDate varchar(10)   --结束日期  \n"
			+ " declare @betweenMonth int   --结束日期与当前日期之间相差的月数   \n"
			+ " declare @sortDate varchar(21)   --排序  \n"
			+ " declare @deptName varchar(100) --部门名称  \n"
			+ " declare @deptID int --部门ID \n"
			+ " set @currentMonth = ? \n"
			+ " set @endMonth = ? \n"
			+ " set @sortDate = ? \n"
			+ " set @deptID = ? \n"
		 
			+ " --设置开始日期和结束日期 \n"
			+ " set @beginDate= @currentMonth + '-01' \n"
			+ " SELECT @endDate = convert(varchar(10),DATEADD(Day,0,CONVERT(char(8),DATEADD(Month,1,@beginDate),120)+'1'),120) \n"
			+ " --查找该部门下的所有用户 \n"
			+ " SELECT dh.人员ID  \n"
			+ " ,dh.部门ID  \n"
			+ " ,RTRIM(hr.姓氏) + RTRIM(hr.名字) as userName  \n"
			+ " into #user  \n"
			+ " FROM xmis.hr_人员部门关系表 as dh,xmis.hr_人员 hr  \n"
			+ " where dh.部门ID = @deptID  \n"
			+ " and dh.人员ID = hr.人员ID  \n"
			+ " and hr.人员ID > 0 AND (hr.禁用 is null or hr.禁用= 0)  \n"
			+ " select xmis.sys_系统日志.id   \n"
			+ " ,xmis.sys_系统日志.userID   \n"
			+ " ,xmis.sys_系统日志.opTime   \n"
			+ " ,case when DATEADD(Day,0-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime) < @beginDate then convert(varchar(10),@beginDate,120) else convert(varchar(10),DATEADD(Day,0-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end as startDay \n"
			+ " ,case when DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime) > @endDate then convert(varchar(10),DATEADD(DAY,-1,@endDate),120) else convert(varchar(10),DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end as endDay \n"
			+ " ,xmis.hr_人员部门关系表.部门ID as subDeptID   \n"
			+ " into #history   \n"
			+ " from xmis.sys_系统日志,xmis.hr_人员部门关系表   \n"
			+ " where userID<>-1   \n"
			+ " and opType = 'login'   \n"
			+ " and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID   \n"
			+ " and xmis.hr_人员部门关系表.部门ID = @deptID  \n"
			+ " and opTime >= @beginDate \n"
			+ " and opTime < @endDate \n"
			+ " union all   \n"
			+ " select xmis.sys_系统日志.id   \n"
			+ " ,xmis.sys_系统日志.userID   \n"
			+ " ,xmis.sys_系统日志.opTime   \n"
			+ " ,case when DATEADD(Day,0-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime) < @beginDate then convert(varchar(10),@beginDate,120) else convert(varchar(10),DATEADD(Day,0-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end \n"
			+ " ,case when DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime) > @endDate then convert(varchar(10),DATEADD(DAY,-1,@endDate),120) else convert(varchar(10),DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end   \n"
			+ " ,xmis.hr_人员部门关系表.部门ID as subDeptID   \n"
			+ " from xmis.sys_系统日志,xmis.hr_人员部门关系表   \n"
			+ " where userID<>-1   \n"
			+ " and (opType = 'timeout' or opType = 'loginout')   \n"
			+ " and opTime>='2011-10-01'   \n"
			+ " and opTime<'2012-06-01'   \n"
			+ " and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID   \n"
			+ " and xmis.hr_人员部门关系表.部门ID = @deptID  \n"
			+ " and opTime >= @beginDate \n"
			+ " and opTime < @endDate \n"
			+ " select #history.*   \n"
			+ " ,case when xmis.org_部门归属部门表.父部门ID IS null then #history.subDeptID else xmis.org_部门归属部门表.父部门ID end as deptID   \n"
			+ " into #history2   \n"
			+ " from #history,xmis.org_部门归属部门表   \n"
			+ " where #history.subDeptID *= xmis.org_部门归属部门表.部门ID \n"
			+ " select #history2.userID,startDay,endDay,COUNT(*) as total \n"
			+ " into #re   \n"
			+ " from #history2   \n"
			+ " group by userID,startDay,endDay \n"
			+ " --查找一月内所有周 \n"
			+ " declare @tempDate datetime \n"
			+ " select @tempDate = DATEADD(Day,0-(DATEPART(Weekday,@beginDate)+@@DATEFIRST-2)%7-1,@beginDate) \n"
			+ " select CONVERT(varchar(10),null,120) as startDay,CONVERT(varchar(10),null,120) as endDay into #weeks where 1=2 \n"
			+ " while(@tempDate < @endDate) begin \n"
			+ "      insert into #weeks  \n"
			+ "     values(case when @tempDate < @beginDate then CONVERT(varchar(10),@beginDate,120) else CONVERT(varchar(10),@tempDate,120) end,case when DATEADD(DAY,6,@tempDate) > DATEADD(DAY,-1,@endDate) then CONVERT(varchar(10),DATEADD(DAY,-1,@endDate),120) else CONVERT(varchar(10),DATEADD(DAY,6,@tempDate),120) end) \n"
			+ "     select @tempDate = DATEADD(Day,7,@tempDate) \n"
			+ " end \n"
		 
			+ " --得到所有月份  \n"
			+ " select identity(int,0,1) as row_no,#weeks.startDay,#weeks.endDay into #allWeeks from #weeks where endDay >= startDay\n"
			+ " declare @count int   \n"
			+ " select @count = count(*) from #allWeeks   \n"
			+ " declare @i int   \n"
			+ " set @i = 0   \n"
			+ " while(@i < @count)   \n"
			+ " begin   \n"
			+ " declare @sd varchar(10) \n"
			+ " declare @ed varchar(10) \n"
			+ " select @sd = startDay,@ed=endDay from #allWeeks where row_no = @i   \n"
			+ " insert into #re select #user.人员ID,@sd,@ed,0 from #user where #user.人员ID not in (select #re.userID from #re where startDay = @sd and endDay = @ed)   \n"
			+ " set @i = @i + 1   \n"
			+ " end   \n"
			+ " select #re.userID,#re.startDay + 'Z' + #re.endDay as weeks,#re.total,#user.userName as userName,0 as userPx,cast(#allWeeks.row_no + 1 as varchar(100)) as weeknum   \n"
			+ " into #result   \n"
			+ " from #re,#user,#allWeeks \n"
			+ " where #re.userID = #user.人员ID \n"
			+ " and #re.startDay = #allWeeks.startDay \n"
			+ " and #re.endDay = #allWeeks.endDay \n"
			+ " --select * from #result \n"
			+ " select * into #pxtemp from #result where 1=2 \n"
			+ " if(@sortDate = '小计') begin  \n"
			+ " 	insert into #pxtemp select userID,'小计',SUM(total),userName,0,'小计' from #result group by userID,userName  \n"
			+ " end \n"
			+ " else begin \n"
			+ " 	insert into #pxtemp select * from #result where weeks = @sortDate \n"
			+ " end \n"
			+ " select identity(int,1,1) as row_no,*    \n"
			+ " into #px   \n"
			+ " from #pxtemp \n"
			+ " order by total desc  \n"
			+ " update #result set #result.userPx = #px.row_no from #result,#px where #result.userID = #px.userID   \n"
			+ " select 99999 as userID,weeks,SUM(total) as total,'合计' as userName,99999 as userPx,cast(weeknum as varchar(100)) as weeknum into #totalTemp from #result group by weeks,weeknum   \n"
			+ " union all    \n"
			+ " select userID,'小计',SUM(total),userName,0,'<div style=\"display:none;\">小计</div>' from #result group by userID,userName \n"
			+ " union all   \n"
			+ " select 99999,'小计',SUM(total),'合计',99999,'<div style=\"display:none;\">小计</div>' from #result   \n"
			+ " insert into #result select * from #totalTemp \n"
//			+ "  if(@sortDate = '小计') begin   \n"
			+ "  update #result set #result.userPx = #px.row_no from #result,#px where #result.userID = #px.userID and #result.weeks = '小计' \n"
//			+ " 	end \n"
			+ " select *  from #result  \n";
		System.out.println(sql);
		return jt.queryForList(sql, new Object[]{start,end,sort,deptID});
	}

	public int getSubDeptCount(String deptName) {
		String sql = " SET NOCOUNT ON " 
			+ " declare @deptID int --部门ID \n"
			+ " SELECT 部门ID \n"
			+ "   into #comp \n"
			+ " FROM [xmis].[xmis].[org_部门归属公司表] where 公司ID = 1 \n"
			+ " SELECT @deptID = d.部门ID \n"
			+ " FROM xmis.org_部门 as d,#comp  \n"
			+ " where d.部门名称 = ? \n"
			+ " and d.部门ID = #comp.部门ID \n"
			+ " SELECT COUNT(*) \n"
			+ " FROM [xmis].[xmis].[org_部门归属部门表] where 父部门ID = @deptID \n";
		
		return jt.queryForInt(sql, new Object[]{deptName});
	}
	
	public List getMonthAccounting2(String start, String end, String sort,
			int deptID) {
		String sql = " SET NOCOUNT ON \n" 
			+ " declare @currentMonth varchar(7) \n"
			+ " declare @endMonth varchar(7) \n"
			+ " declare @beginDate varchar(10) --开始日期   \n"
			+ " declare @endDate varchar(10)   --结束日期  \n"
			+ " declare @betweenMonth int   --结束日期与当前日期之间相差的月数   \n"
			+ " declare @sortDate varchar(21)   --排序  \n"
			+ " declare @deptName varchar(100) --部门名称  \n"
			+ " declare @deptID int --部门ID \n"
			+ " set @currentMonth = ? \n"
			+ " set @endMonth = ? \n"
			+ " set @sortDate = ? \n"
			+ " set @deptID = ? \n"
		 
			+ " --设置开始日期和结束日期 \n"
			+ " set @beginDate= @currentMonth + '-01' \n"
			+ " SELECT @endDate = convert(varchar(10),DATEADD(Day,0,CONVERT(char(8),DATEADD(Month,1,@beginDate),120)+'1'),120) \n"
			+ " --查找该部门下的所有用户 \n"
			+ " SELECT dh.人员ID  \n"
			+ " ,dh.部门ID  \n"
			+ " ,RTRIM(hr.姓氏) + RTRIM(hr.名字) as userName  \n"
			+ " into #user  \n"
			+ " FROM xmis.hr_人员部门关系表 as dh,xmis.hr_人员 hr  \n"
			+ " where dh.部门ID in (  SELECT 部门ID FROM xmis.org_部门归属部门表 where 父部门ID =@deptID)  \n"
			+ " and dh.人员ID = hr.人员ID  \n"
			+ " and hr.人员ID > 0 AND (hr.禁用 is null or hr.禁用= 0)  \n"
			+ " select xmis.sys_系统日志.id   \n"
			+ " ,xmis.sys_系统日志.userID   \n"
			+ " ,xmis.sys_系统日志.opTime   \n"
			+ " ,case when DATEADD(Day,0-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime) < @beginDate then convert(varchar(10),@beginDate,120) else convert(varchar(10),DATEADD(Day,0-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end as startDay \n"
//			+ " ,case when DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime) > @endDate then convert(varchar(10),DATEADD(DAY,-1,@endDate),120) else convert(varchar(10),DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end as endDay \n"
			+ "  ,case when DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime) > @endDate then convert(varchar(10),DATEADD(DAY,-1,@endDate),120) when convert(varchar(10),DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120)> @beginDate then convert(varchar(10),DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) else convert(varchar(10),DATEADD(Day,13-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120)  end as endDay \n"
			+ " ,xmis.hr_人员部门关系表.部门ID as subDeptID   \n"
			+ " into #history   \n"
			+ " from xmis.sys_系统日志,xmis.hr_人员部门关系表   \n"
			+ " where userID<>-1   \n"
			+ " and opType = 'login'   \n"
			+ " and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID   \n"
			+ " and xmis.hr_人员部门关系表.部门ID in (  SELECT 部门ID FROM xmis.org_部门归属部门表 where 父部门ID =@deptID)  \n"
			+ " and opTime >= @beginDate \n"
			+ " and opTime < @endDate \n"
			+ " union all   \n"
			+ " select xmis.sys_系统日志.id   \n"
			+ " ,xmis.sys_系统日志.userID   \n"
			+ " ,xmis.sys_系统日志.opTime   \n"
			+ " ,case when DATEADD(Day,0-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime) < @beginDate then convert(varchar(10),@beginDate,120) else convert(varchar(10),DATEADD(Day,0-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end \n"
			+ "  ,case when DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime) > @endDate then convert(varchar(10),DATEADD(DAY,-1,@endDate),120) when convert(varchar(10),DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120)> @beginDate then convert(varchar(10),DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) else convert(varchar(10),DATEADD(Day,13-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end   \n"
//			+ " ,case when DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime) > @endDate then convert(varchar(10),DATEADD(DAY,-1,@endDate),120) else convert(varchar(10),DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end   \n"
			+ " ,xmis.hr_人员部门关系表.部门ID as subDeptID   \n"
			+ " from xmis.sys_系统日志,xmis.hr_人员部门关系表   \n"
			+ " where userID<>-1   \n"
			+ " and (opType = 'timeout' or opType = 'loginout')   \n"
			+ " and opTime>='2011-10-01'   \n"
			+ " and opTime<'2012-06-01'   \n"
			+ " and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID   \n"
			+ " and xmis.hr_人员部门关系表.部门ID in (  SELECT 部门ID FROM xmis.org_部门归属部门表 where 父部门ID =@deptID)  \n"
			+ " and opTime >= @beginDate \n"
			+ " and opTime < @endDate \n"
			+ " select #history.*   \n"
			+ " ,case when xmis.org_部门归属部门表.父部门ID IS null then #history.subDeptID else xmis.org_部门归属部门表.父部门ID end as deptID   \n"
			+ " into #history2   \n"
			+ " from #history,xmis.org_部门归属部门表   \n"
			+ " where #history.subDeptID *= xmis.org_部门归属部门表.部门ID \n"
			+ " select #history2.userID,startDay,endDay,COUNT(*) as total \n"
			+ " into #re   \n"
			+ " from #history2   \n"
			+ " group by userID,startDay,endDay \n"
			+ " --查找一月内所有周 \n"
			+ " declare @tempDate datetime \n"
			+ " select @tempDate = DATEADD(Day,0-(DATEPART(Weekday,@beginDate)+@@DATEFIRST-2)%7-1,@beginDate) \n"
			+ " select CONVERT(varchar(10),null,120) as startDay,CONVERT(varchar(10),null,120) as endDay into #weeks where 1=2 \n"
			+ " while(@tempDate < @endDate) begin \n"
			+ "      insert into #weeks  \n"
			+ "     values(case when @tempDate < @beginDate then CONVERT(varchar(10),@beginDate,120) else CONVERT(varchar(10),@tempDate,120) end,case when DATEADD(DAY,6,@tempDate) > DATEADD(DAY,-1,@endDate) then CONVERT(varchar(10),DATEADD(DAY,-1,@endDate),120) else CONVERT(varchar(10),DATEADD(DAY,6,@tempDate),120) end) \n"
			+ "     select @tempDate = DATEADD(Day,7,@tempDate) \n"
			+ " end \n"
		 
			+ " --得到所有月份  \n"
			+ " select identity(int,0,1) as row_no,#weeks.startDay,#weeks.endDay into #allWeeks from #weeks where endDay >= startDay\n"
			+ " declare @count int   \n"
			+ " select @count = count(*) from #allWeeks   \n"
			+ " declare @i int   \n"
			+ " set @i = 0   \n"
			+ " while(@i < @count)   \n"
			+ " begin   \n"
			+ " declare @sd varchar(10) \n"
			+ " declare @ed varchar(10) \n"
			+ " select @sd = startDay,@ed=endDay from #allWeeks where row_no = @i   \n"
			+ " insert into #re select #user.人员ID,@sd,@ed,0 from #user where #user.人员ID not in (select #re.userID from #re where startDay = @sd and endDay = @ed)   \n"
			+ " set @i = @i + 1   \n"
			+ " end   \n"
			+ " select #re.userID,#re.startDay + 'Z' + #re.endDay as weeks,#re.total,#user.userName as userName,0 as userPx,cast(#allWeeks.row_no + 1 as varchar(100)) as weeknum   \n"
			+ " into #result   \n"
			+ " from #re,#user,#allWeeks \n"
			+ " where #re.userID = #user.人员ID \n"
			+ " and #re.startDay = #allWeeks.startDay \n"
			+ " and #re.endDay = #allWeeks.endDay \n"
			+ " --select * from #result \n"
			+ " select * into #pxtemp from #result where 1=2 \n"
			+ " if(@sortDate = '小计') begin  \n"
			+ " 	insert into #pxtemp select userID,'小计',SUM(total),userName,0,'小计' from #result group by userID,userName  \n"
			+ " end \n"
			+ " else begin \n"
			+ " 	insert into #pxtemp select * from #result where weeks = @sortDate \n"
			+ " end \n"
			+ " select identity(int,1,1) as row_no,*    \n"
			+ " into #px   \n"
			+ " from #pxtemp \n"
			+ " order by total desc  \n"
			+ " update #result set #result.userPx = #px.row_no from #result,#px where #result.userID = #px.userID   \n"
			+ " select 99999 as userID,weeks,SUM(total) as total,'合计' as userName,99999 as userPx,cast(weeknum as varchar(100)) as weeknum into #totalTemp from #result group by weeks,weeknum   \n"
			+ " union all    \n"
			+ " select userID,'小计',SUM(total),userName,0,'<div style=\"display:none;\">小计</div>' from #result group by userID,userName \n"
			+ " union all   \n"
			+ " select 99999,'小计',SUM(total),'合计',99999,'<div style=\"display:none;\">小计</div>' from #result   \n"
			+ " insert into #result select * from #totalTemp \n"
//			+ "  if(@sortDate = '小计') begin   \n"
			+ "  update #result set #result.userPx = #px.row_no from #result,#px where #result.userID = #px.userID and #result.weeks = '小计' \n"
//			+ " 	end \n"
			+ " select *  from #result  \n";
		System.out.println(sql);
		return jt.queryForList(sql, new Object[]{start,end,sort,deptID});
	}
	
	public List getMonthAccounting3(String start, String end,String sort,String deptName) {
		String hsql = " SET NOCOUNT ON declare @beginDate varchar(7) --开始日期 \n"
		  + " declare @endDate varchar(7)   --结束日期 \n"
		  + " declare @betweenMonth int   --结束日期与当前日期之间相差的月数 \n"
		  + " declare @sortDate varchar(7)   --排序 \n"
		  + " set @beginDate= ? \n"
		  + " set @endDate= ? \n"
		  + " set @sortDate= ? \n"
		  
		  + " declare @deptID int --部门ID \n"
		  + " SELECT 部门ID \n"
		  + "    ,是否直属 \n"
		  + "    into #comp \n"
		  + " FROM xmis.org_部门归属公司表 where 公司ID = 1 \n"
		  

		  + " SELECT @deptID = d.部门ID \n"
		  + " FROM xmis.org_部门 as d,#comp  \n"
		  + "  where d.部门名称 = ? \n"
		  + " and d.部门ID = #comp.部门ID \n"
		  
		  + " SELECT 公司ID \n"
		  + " ,xmis.org_部门归属公司表.部门ID \n"
		  + " ,xmis.org_部门.部门名称 \n"
		  + " ,xmis.org_部门归属公司表.排序 \n"
		  + " into #d \n"
		  + " FROM xmis.org_部门归属公司表,xmis.org_部门,xmis.org_部门归属部门表 \n"
		  + " where 公司ID = 1 and 是否直属 = 0 \n"
		  + " and xmis.org_部门归属公司表.部门ID = xmis.org_部门.部门ID \n"
		  + " and xmis.org_部门归属部门表.父部门ID = @deptID \n"
		  
		  + " select xmis.sys_系统日志.id \n"
		  + " ,xmis.sys_系统日志.userID \n"
		  + " ,xmis.sys_系统日志.opTime \n"
		  + " ,convert(varchar(7),xmis.sys_系统日志.opTime,120) as loginmonth \n"
		  + " ,xmis.hr_人员部门关系表.部门ID as subDeptID \n"
		  + " into #history \n"
		  + " from xmis.sys_系统日志,xmis.hr_人员部门关系表,xmis.hr_人员 \n"
		  + " where userID<>-1 and opType = 'login' and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID \n"
		  + " and xmis.sys_系统日志.userID = xmis.hr_人员.人员ID \n"
		  + " AND (xmis.hr_人员.禁用 is null or xmis.hr_人员.禁用= 0)   \n"
		  + " union all \n"
		  + " select xmis.sys_系统日志.id \n"
		  + " ,xmis.sys_系统日志.userID \n"
		  + " ,xmis.sys_系统日志.opTime \n"
		  + " ,convert(varchar(7),xmis.sys_系统日志.opTime,120) as loginmonth \n"
		  + " ,xmis.hr_人员部门关系表.部门ID as subDeptID \n"
		  + " from xmis.sys_系统日志,xmis.hr_人员部门关系表,xmis.hr_人员 \n"
		  + " where userID<>-1 and (opType = 'timeout' or opType = 'loginout') and opTime>='2011-10-01' and opTime<'2012-06-01' and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID \n"
		  + " and xmis.sys_系统日志.userID = xmis.hr_人员.人员ID \n"
		  + " AND (xmis.hr_人员.禁用 is null or xmis.hr_人员.禁用= 0)   \n"
		  + " select #history.* \n"
		  + " ,case when xmis.org_部门归属部门表.父部门ID IS null then #history.subDeptID else xmis.org_部门归属部门表.父部门ID end as deptID \n"
		  + " into #history2 \n"
		  + " from #history,xmis.org_部门归属部门表 \n"
		  + " where #history.subDeptID *= xmis.org_部门归属部门表.部门ID \n"
		  + " and loginmonth>=@beginDate  \n"
		  + " and loginmonth<=@endDate \n"
		  + " select #history2.subDeptID  as deptID,loginmonth,COUNT(*) as total \n"
		  + " into #re \n"
		  + " from #history2 \n"
		  + " where subDeptID in (select 部门ID from #d) \n"
		  + " group by subDeptID,loginmonth \n"
		  + " --根据开始日期和结束日期及当前日期，查找所有月份 \n"
		  + " DECLARE @today VARCHAR(10) \n"
		  + " SELECT @today = CONVERT(VARCHAR(7),GETDATE(),120) + '-01' \n"
		  + " select convert(varchar(7),null,120) as loginmonth into #months where 1=2   \n"
		  + " declare @tdate datetime   \n"
		  + " set @tdate = @beginDate + '-01'   \n"
		  + " IF @tdate < '2011-08-01' BEGIN \n"
		  + " 	SET @tdate = '2011-08-01' \n"
		  + " END \n"
		  + " while(@tdate <= @endDate + '-01' AND @tdate <= @today) begin    \n"
		  + "     insert into #months select convert(varchar(7),@tdate,120)   \n"
		  + "     set @tdate = DATEADD(MONTH,1,@tdate) \n"
		  + " end   \n"
		  + " select identity(int,0,1) as row_no,#months.loginmonth into #allMonth from #months  \n"
		  + " ----------------------------------------------- \n"
		  + " declare @count int \n"
		  + " select @count = count(*) from #allMonth \n"
		  + " declare @i int \n"
		  + " set @i = 0 \n"
		  + " while(@i < @count) \n"
		  + " begin \n"
		  + " 	declare @yearAndMonth varchar(7) \n"
		  + " 	select @yearAndMonth = loginmonth from #allMonth where row_no = @i \n"
		  + " 	insert into #re select distinct #d.部门ID,@yearAndMonth,0 from #d where #d.部门ID not in (select #re.deptID from #re where loginmonth = @yearAndMonth) \n"
		  + " 	set @i = @i + 1 \n"
		  + " end \n"
		  + " select distinct #re.*,#d.部门名称 as deptName,#d.排序 as deptPx \n"
		  + " into #result \n"
		  + " from #re,#d  \n"
		  + " where #re.deptID = #d.部门ID \n"
		  + " order by loginmonth asc,total desc,deptPx \n"
		  + " select * into #pxtemp from #result where 1=2   \n"
		  + " if(@sortDate = '小计') begin    \n"
		  + " 	insert into #pxtemp select deptID,'小计',SUM(total),deptName,0 from #result group by deptID,deptName  \n" 
		  + " end   \n"
		  + " else begin   \n"
		  + " 	insert into #pxtemp select * from #result where loginmonth = @sortDate  \n"
		  + " end  \n"
		  + " select identity(int,1,1) as row_no,*  \n"
		  + " into #px \n"
		  + " from #pxtemp    \n"
		  + " where loginmonth = @sortDate \n"
		  + " order by total desc,deptPX \n"
		  + " update #result set #result.deptPx = #px.row_no from #result,#px where #result.deptID = #px.deptID \n"
		  + " select 99999 as deptID,loginmonth,SUM(total) as total,'合计' as deptName,99999 as deptPx into #totalTemp from #result group by loginmonth \n"
		  + " union all  \n"
		  + " select deptID,'小计',SUM(total),deptName,99999 from #result group by deptID,deptName \n"
		  + " union all \n"
		  + " select 99999,'小计',SUM(total),'合计',99999 from #result \n"
		  + " insert into #result select * from #totalTemp \n"
		  + " update #result set #result.deptPx = #px.row_no from #result,#px where #result.deptID = #px.deptID and #result.loginmonth = '小计' \n"
		  + " select * \n"
		  + " ,case when SUBSTRING(loginmonth,1,4)='小计' then '<div style=\"display:none;\">2222</div>' else SUBSTRING(loginmonth,1,4) end as year \n"
		  + " ,case when SUBSTRING(loginmonth,6,2)='' then '小计' else SUBSTRING(loginmonth,6,2) end as month from #result \n";
//		  + " union all \n"
//		  + " select * from #totalTemp "
		System.out.println(hsql);
		return jt.queryForList(hsql, new Object[]{start,end,sort,deptName});
	}

	public List getLastAccounting(String sort) {
		String sql = "SET NOCOUNT ON \n"
			+ " declare @beginDate datetime --开始日期  \n"
			+ " declare @endDate datetime   --结束日期  \n"
			+ " declare @betweenMonth int   --结束日期与当前日期之间相差的月数  \n"
			+ " declare @sortDate varchar(21)   --排序  \n"
			+ " set @sortDate = ? \n"
			+ " declare @numOfWeek int \n"
			+ " declare @tempDate datetime  \n"
			+ " select @endDate = GETDATE() \n"
			+ " select @numOfWeek = datepart(weekday,@endDate)   --日期是周内的第几天 \n"
			+ " if(@numOfWeek = 1) --如果当天在本周是第一天，即周日 \n"
			+ " begin  \n"
			+ " 	set @tempDate = @endDate \n"
			+ " end \n"
			+ " else begin \n"
			+ " 	select @tempDate = DATEADD(Day,0-(DATEPART(Weekday,@endDate)+@@DATEFIRST-2)%7-1,@endDate) \n"
			+ " end \n"
			+ " --查找所有周 \n"
			+ " select CONVERT(varchar(10),null,120) as startDay,CONVERT(varchar(10),null,120) as endDay into #weeks where 1=2  \n"
			+ " declare @j int \n"
			+ " set @j = 0 \n"
			+ " while(@j < 4) begin  \n"
			+ "   insert into #weeks   \n"
			+ "  values(CONVERT(varchar(10),@tempDate,120),CONVERT(varchar(10),DATEADD(DAY,6,@tempDate),120))  \n"
			+ "  select @tempDate = DATEADD(Day,-7,@tempDate)  \n"
			+ "  set @j = @j + 1 \n"
			+ " end  \n"
			+ " select @beginDate = min(CONVERT(datetime,startDay,120)) from #weeks \n"
			+ " SELECT 公司ID  \n"
			+ " ,xmis.org_部门归属公司表.部门ID  \n"
			+ " ,xmis.org_部门.部门名称  \n"
			+ " ,xmis.org_部门归属公司表.排序  \n"
			+ " into #d  \n"
			+ " FROM xmis.org_部门归属公司表,xmis.org_部门  \n"
			+ " where 公司ID = 1  \n"
			+ " and 是否直属 = 1 \n"
			+ " and xmis.org_部门归属公司表.部门ID = xmis.org_部门.部门ID  \n"
			+ " and xmis.org_部门.部门ID <> 504 \n"
			+ " select xmis.sys_系统日志.id  \n"
			+ " ,xmis.sys_系统日志.userID  \n"
			+ " ,xmis.sys_系统日志.opTime  \n"
			+ " ,xmis.hr_人员部门关系表.部门ID as subDeptID  \n"
			+ " into #h \n"
			+ " from xmis.sys_系统日志,xmis.hr_人员部门关系表,xmis.hr_人员  \n"
			+ " where userID<>-1 and opType = 'login' and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID  \n"
			+ " and xmis.sys_系统日志.userID = xmis.hr_人员.人员ID  \n"
			+ " AND (xmis.hr_人员.禁用 is null or xmis.hr_人员.禁用= 0) \n"
			+ " union all  \n"
			+ " select xmis.sys_系统日志.id  \n"
			+ " ,xmis.sys_系统日志.userID  \n"
			+ " ,xmis.sys_系统日志.opTime  \n"
			+ " ,xmis.hr_人员部门关系表.部门ID as subDeptID  \n"
			+ " from xmis.sys_系统日志,xmis.hr_人员部门关系表,xmis.hr_人员  \n"
			+ " where userID<>-1 and (opType = 'timeout' or opType = 'loginout') and opTime>='2011-10-01' and opTime<'2012-06-01' and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID  \n"
			+ " and xmis.sys_系统日志.userID = xmis.hr_人员.人员ID  \n"
			+ " AND (xmis.hr_人员.禁用 is null or xmis.hr_人员.禁用= 0)    \n"
			+ " select * \n"
			+ " ,case when datepart(weekday,opTime) = 1 then convert(varchar(10),opTime,120) else convert(varchar(10),DATEADD(Day,0-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end as startDay  \n"
			+ " ,case when datepart(weekday,opTime) = 1 then convert(varchar(10),dateadd(day,6,opTime),120) else convert(varchar(10),DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end as endDay   \n"
			+ " into #history \n"
			+ " from #h where opTime >=@beginDate and opTime <=@endDate \n"
			+ " select #history.*  \n"
			+ " ,case when xmis.org_部门归属部门表.父部门ID IS null then #history.subDeptID else xmis.org_部门归属部门表.父部门ID end as deptID  \n"
			+ " into #history2  \n"
			+ " from #history,xmis.org_部门归属部门表  \n"
			+ " where #history.subDeptID *= xmis.org_部门归属部门表.部门ID  \n"
			+ " select #history2.deptID,startDay,endDay,COUNT(*) as total  \n"
			+ " into #re  \n"
			+ " from #history2  \n"
			+ " group by deptID,startDay,endDay \n"
			+ " select identity(int,0,1) as row_no,#weeks.startDay,#weeks.endDay into #allWeeks from #weeks order by #weeks.startDay,#weeks.endDay \n"
			+ " declare @count int  \n"
			+ " select @count = count(*) from #allWeeks  \n"
			+ " declare @i int  \n"
			+ " set @i = 0  \n"
			+ " while(@i < @count)  \n"
			+ " begin  \n"
			+ " 	declare @sd varchar(10)  \n"
			+ " 	declare @ed varchar(10)  \n"
			+ " 	select @sd = startDay,@ed=endDay from #allWeeks where row_no = @i   \n" 
			+ " 	insert into #re select #d.部门ID,@sd,@ed,0 from #d where #d.部门ID not in (select #re.deptID from #re where startDay = @sd and endDay = @ed)  \n"
			+ " 	set @i = @i + 1  \n"
			+ " end  \n"
			+ " select #re.deptID,#re.startDay + 'Z' + #re.endDay as weeks,#re.total,#d.部门名称 as deptName,#d.排序 as deptPx,cast(#allWeeks.row_no + 1 as varchar(100)) as weeknum  \n"
			+ " into #result  \n"
			+ " from #re,#d ,#allWeeks   \n"
			+ " where #re.deptID = #d.部门ID  \n"
			+ " and #re.startDay = #allWeeks.startDay  \n"
			+ " and #re.endDay = #allWeeks.endDay  \n"
			+ " select * into #pxtemp from #result where 1=2   \n"
			+ " if(@sortDate = '小计') begin    \n"
			+ " 	insert into #pxtemp select deptID,'小计',SUM(total),deptName,0,'小计' from #result group by deptID,deptName   \n"
			+ " end   \n"
			+ " else begin   \n"
			+ " 	insert into #pxtemp select * from #result where weeks = @sortDate  \n"
			+ " end  \n"
			+ " select identity(int,1,1) as row_no,*   \n"
			+ " into #px  \n"
			+ " from #pxtemp     \n"
			+ " order by total desc,deptPX  \n"
			+ " update #result set #result.deptPx = #px.row_no from #result,#px where #result.deptID = #px.deptID  \n"
			+ " select 99999 as deptID,weeks as weeks,SUM(total) as total,'合计' as deptName,99999 as deptPx,cast(weeknum as varchar(100)) as weeknum into #totalTemp from #result group by weeks,weeknum \n"
			+ " union all   \n"
			+ " select deptID,'小计',SUM(total),deptName,99999,'<div style=\"display:none;\">小计</div>' from #result group by deptID,deptName  \n"
			+ " union all  \n"
			+ " select 99999,'小计',SUM(total),'合计',99999,'<div style=\"display:none;\">小计</div>' from #result  \n"
			+ " insert into #result select * from #totalTemp  \n"
			+ " update #result set #result.deptPx = #px.row_no from #result,#px where #result.deptID = #px.deptID and #result.weeks = '小计'  \n"
			+ " select *  from #result  \n";
		System.out.println(sql);
		return jt.queryForList(sql, new Object[]{sort});
	}

	public List getLastAccounting(String sort, String deptName) {
		String sql = " SET NOCOUNT ON \n" 
			+ " declare @beginDate datetime --开始日期  \n"
			+ " declare @endDate datetime   --结束日期 \n"
			+ " declare @numOfWeek int \n"
			+ " declare @tempDate datetime  \n"
			+ " declare @deptName varchar(100) --部门名称  \n"
			+ " declare @deptID int --部门名称  \n"
			+ " declare @sortDate varchar(21)   --排序  \n"
			+ " select @endDate = GETDATE()  \n"
			+ " set @sortDate=? \n"
			+ " set @deptName= ? \n"
			+ " --得到当先日期的周一是哪天 \n"
			+ " select @numOfWeek = datepart(weekday,@endDate)   --日期是周内的第几天 \n"
			+ " if(@numOfWeek = 1) --如果当天在本周是第一天，即周日 \n"
			+ " begin  \n"
			+ " 	set @tempDate = @endDate \n"
			+ " end \n"
			+ "  else begin \n"
			+ " 	select @tempDate = DATEADD(Day,0-(DATEPART(Weekday,@endDate)+@@DATEFIRST-2)%7-1,@endDate) \n"
			+ " end \n"
			+ " --查找所有周 \n"
			+ " select CONVERT(varchar(10),null,120) as startDay,CONVERT(varchar(10),null,120) as endDay into #weeks where 1=2  \n"
			+ " declare @j int \n"
			+ " set @j = 0 \n"
			+ " while(@j < 4) begin  \n"
			+ "   insert into #weeks   \n"
			+ "   values(CONVERT(varchar(10),@tempDate,120),CONVERT(varchar(10),DATEADD(DAY,6,@tempDate),120))  \n"
			+ "   select @tempDate = DATEADD(Day,-7,@tempDate)  \n"
			+ "   set @j = @j + 1 \n"
			+ " end  \n"
			+ " --设置开始日期 \n"
			+ " select @beginDate = min(CONVERT(datetime,startDay,120)) from #weeks \n"
			+ " --得到部门ID \n"
			+ " SELECT @deptID = comp.部门ID  \n"
			+ " FROM xmis.org_部门归属公司表 as comp,xmis.org_部门 as dept  \n"
			+ " where comp.公司ID = 1 and dept.部门ID = comp.部门ID  \n"
			+ " and dept.部门名称 = @deptName \n"
			+ " --得到该部门下的所有人员 \n"
			+ " SELECT dh.人员ID  \n"
			+ " ,dh.部门ID  \n"
			+ " ,RTRIM(hr.姓氏) + RTRIM(hr.名字) as userName  \n"
			+ " into #user  \n"
			+ " FROM xmis.hr_人员部门关系表 as dh,xmis.hr_人员 hr  \n"
			+ " where dh.部门ID = @deptID  \n"
			+ " and dh.人员ID = hr.人员ID  \n"
			+ " and hr.人员ID > 0 AND (hr.禁用 is null or hr.禁用= 0)  \n"
			+ " select xmis.sys_系统日志.id  \n"
			+ " ,xmis.sys_系统日志.userID  \n"
			+ " ,xmis.sys_系统日志.opTime  \n"
			+ " ,xmis.hr_人员部门关系表.部门ID as subDeptID  \n"
			+ " into #h \n"
			+ " from xmis.sys_系统日志,xmis.hr_人员部门关系表,xmis.hr_人员  \n"
			+ " where userID<>-1 and opType = 'login' and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID  \n"
			+ " and xmis.sys_系统日志.userID = xmis.hr_人员.人员ID  \n"
			+ " AND (xmis.hr_人员.禁用 is null or xmis.hr_人员.禁用= 0) \n"
			+ " and xmis.hr_人员部门关系表.部门ID = @deptID  \n"
			+ " union all  \n"
			+ " select xmis.sys_系统日志.id  \n"
			+ " ,xmis.sys_系统日志.userID  \n"
			+ " ,xmis.sys_系统日志.opTime  \n"
			+ " ,xmis.hr_人员部门关系表.部门ID as subDeptID  \n"
			+ " from xmis.sys_系统日志,xmis.hr_人员部门关系表,xmis.hr_人员  \n"
			+ " where userID<>-1 and (opType = 'timeout' or opType = 'loginout') and opTime>='2011-10-01' and opTime<'2012-06-01' and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID  \n"
			+ " and xmis.sys_系统日志.userID = xmis.hr_人员.人员ID  \n"
			+ " AND (xmis.hr_人员.禁用 is null or xmis.hr_人员.禁用= 0) \n"
			+ " and xmis.hr_人员部门关系表.部门ID = @deptID  \n"
			+ " select * \n"
			+ " ,case when datepart(weekday,opTime) = 1 then convert(varchar(10),opTime,120) else convert(varchar(10),DATEADD(Day,0-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end as startDay  \n"
			+ " ,case when datepart(weekday,opTime) = 1 then convert(varchar(10),dateadd(day,6,opTime),120) else convert(varchar(10),DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end as endDay   \n"
			+ " into #history \n"
			+ " from #h where opTime >=@beginDate and opTime <=@endDate \n"
			+ " select #history.*  \n"
			+ " ,case when xmis.org_部门归属部门表.父部门ID IS null then #history.subDeptID else xmis.org_部门归属部门表.父部门ID end as deptID  \n"
			+ " into #history2  \n"
			+ " from #history,xmis.org_部门归属部门表  \n"
			+ " where #history.subDeptID *= xmis.org_部门归属部门表.部门ID  \n"
			+ " select #history2.userID,startDay,endDay,COUNT(*) as total  \n"
			+ " into #re  \n"
			+ " from #history2  \n"
			+ " group by userID,startDay,endDay \n"
			+ " select identity(int,0,1) as row_no,#weeks.startDay,#weeks.endDay into #allWeeks from #weeks order by #weeks.startDay,#weeks.endDay \n"
			+ " declare @count int  \n"
			+ " select @count = count(*) from #allWeeks  \n"
			+ " declare @i int  \n"
			+ " set @i = 0  \n"
			+ " while(@i < @count)  \n"
			+ " begin  \n"
			+ " 	declare @sd varchar(10)  \n"
			+ " 	declare @ed varchar(10)  \n"
			+ " 	select @sd = startDay,@ed=endDay from #allWeeks where row_no = @i   \n" 
			+ "  	insert into #re select #user.人员ID,@sd,@ed,0 from #user where #user.人员ID not in (select #re.userID from #re where startDay = @sd and endDay = @ed)  \n"
			+ " 	set @i = @i + 1  \n"
			+ " end  \n"
			+ " select #re.userID,#re.startDay + 'Z' + #re.endDay as weeks,#re.total,#user.userName as userName,0 as userPx,cast(#allWeeks.row_no + 1 as varchar(100)) as weeknum  \n"
			+ " into #result   \n"
			+ " from #re,#user,#allWeeks   \n"
			+ " where #re.userID = #user.人员ID   \n"
			+ " and #re.startDay = #allWeeks.startDay  \n"
			+ " and #re.endDay = #allWeeks.endDay  \n"
			+ " select * into #pxtemp from #result where 1=2    \n"
			+ " if(@sortDate = '小计') begin     \n"
			+ " 	insert into #pxtemp select userID,'小计',SUM(total),userName,0,'小计' from #result group by userID,userName     \n"
			+ " end    \n"
			+ " else begin    \n"
			+ " 	insert into #pxtemp select * from #result where weeks = @sortDate   \n" 
			+ " end \n"
			+ " select identity(int,1,1) as row_no,*    \n"
			+ " into #px   \n"
			+ " from #pxtemp    \n"
			+ " order by total desc  \n"
			+ " update #result set #result.userPx = #px.row_no from #result,#px where #result.userID = #px.userID  \n"
			+ " select 99999 as userID,weeks as weeks,SUM(total) as total,'合计' as userName,99999 as userPx,cast(weeknum as varchar(100)) as weeknum into #totalTemp from #result group by weeks,weeknum \n"
			+ " union all    \n"
			+ " select userID,'小计',SUM(total),userName,99999,'<div style=\"display:none;\">小计</div>' from #result group by userID,userName   \n"
			+ " union all   \n"
			+ " select 99999,'小计',SUM(total),'合计',99999,'<div style=\"display:none;\">小计</div>' from #result   \n"
			+ " insert into #result select * from #totalTemp   \n"
			+ " update #result set #result.userPx = #px.row_no from #result,#px where #result.userID = #px.userID and #result.weeks = '小计'  \n"
			+ " select * from #result \n";
		System.out.println(sql);
		return jt.queryForList(sql, new Object[]{sort,deptName});
	}

	public List getLastAccounting2(String sort, String deptName) {
		String sql = " SET NOCOUNT ON \n"
			+ " declare @beginDate datetime --开始日期  \n"
			+ " declare @endDate datetime   --结束日期  \n"
			+ " declare @sortDate varchar(21)   --排序 \n"
			+ " declare @deptID int           --部门ID \n"
			+ " declare @numOfWeek int \n"
			+ " declare @tempDate datetime  \n"
			+ " declare @deptName varchar(100) --部门名称    \n"
			+ " select @endDate = GETDATE() \n"
			+ " set @sortDate = ? \n"
			+ " set @deptName= ? \n"
			+ " --得到当先日期的周一是哪天 \n"
			+ " select @numOfWeek = datepart(weekday,@endDate)   --日期是周内的第几天 \n"
			+ " if(@numOfWeek = 1) --如果当天在本周是第一天，即周日 \n"
			+ " begin  \n"
			+ " 	set @tempDate = @endDate \n"
			+ " end \n"
			+ " else begin \n"
			+ " 	select @tempDate = DATEADD(Day,0-(DATEPART(Weekday,@endDate)+@@DATEFIRST-2)%7-1,@endDate) \n"
			+ " end \n"
			+ " --查找所有周 \n"
			+ " select CONVERT(varchar(10),null,120) as startDay,CONVERT(varchar(10),null,120) as endDay into #weeks where 1=2  \n"
			+ " declare @j int \n"
			+ " set @j = 0 \n"
			+ " while(@j < 4) begin  \n"
			+ "     insert into #weeks   \n"
			+ "    values(CONVERT(varchar(10),@tempDate,120),CONVERT(varchar(10),DATEADD(DAY,6,@tempDate),120))  \n"
			+ "     select @tempDate = DATEADD(Day,-7,@tempDate)  \n"
			+ "     set @j = @j + 1 \n"
			+ " end  \n"
			+ " --设置开始日期 \n"
			+ " select @beginDate = min(CONVERT(datetime,startDay,120)) from #weeks \n"
			+ " SELECT 部门ID  \n"
			+ " ,是否直属  \n"
			+ " into #comp  \n"
			+ " FROM xmis.org_部门归属公司表 where 公司ID = 1  \n"
			+ " SELECT @deptID = d.部门ID  \n"
			+ " FROM xmis.org_部门 as d,#comp   \n"
			+ " where d.部门名称 = @deptName \n"
			+ " and d.部门ID = #comp.部门ID  \n"
			+ " SELECT distinct 公司ID  \n"
			+ " ,xmis.org_部门归属公司表.部门ID  \n"
			+ " ,xmis.org_部门.部门名称  \n"
			+ " ,xmis.org_部门归属公司表.排序  \n"
			+ " into #d  \n"
			+ " FROM xmis.org_部门归属公司表,xmis.org_部门,xmis.org_部门归属部门表  \n"
			+ " where 公司ID = 1  \n"
			+ " and 是否直属 = 0  \n"
			+ " and xmis.org_部门归属公司表.部门ID = xmis.org_部门.部门ID  \n"
			+ " and xmis.org_部门归属部门表.父部门ID = @deptID  \n"
			+ " select xmis.sys_系统日志.id  \n"
			+ " ,xmis.sys_系统日志.userID  \n"
			+ " ,xmis.sys_系统日志.opTime  \n"
			+ " ,xmis.hr_人员部门关系表.部门ID as subDeptID  \n"
			+ " into #h \n"
			+ " from xmis.sys_系统日志,xmis.hr_人员部门关系表,xmis.hr_人员  \n"
			+ " where userID<>-1 and opType = 'login' and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID  \n"
			+ " and xmis.sys_系统日志.userID = xmis.hr_人员.人员ID  \n"
			+ " AND (xmis.hr_人员.禁用 is null or xmis.hr_人员.禁用= 0) \n"
			+ " union all  \n"
			+ " select xmis.sys_系统日志.id  \n"
			+ " ,xmis.sys_系统日志.userID  \n"
			+ " ,xmis.sys_系统日志.opTime  \n"
			+ " ,xmis.hr_人员部门关系表.部门ID as subDeptID  \n"
			+ " from xmis.sys_系统日志,xmis.hr_人员部门关系表,xmis.hr_人员  \n"
			+ " where userID<>-1  \n"
			+ " and (opType = 'timeout' or opType = 'loginout')  \n"
			+ " and opTime>='2011-10-01' and opTime<'2012-06-01'  \n"
			+ " and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID  \n"
			+ " and xmis.sys_系统日志.userID = xmis.hr_人员.人员ID  \n"
			+ " AND (xmis.hr_人员.禁用 is null or xmis.hr_人员.禁用= 0) \n"
			+ " select * \n"
			+ " ,case when datepart(weekday,opTime) = 1 then convert(varchar(10),opTime,120) else convert(varchar(10),DATEADD(Day,0-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end as startDay  \n"
			+ " ,case when datepart(weekday,opTime) = 1 then convert(varchar(10),dateadd(day,6,opTime),120) else convert(varchar(10),DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end as endDay   \n"
			+ " into #history \n"
			+ " from #h where opTime >=@beginDate and opTime <=@endDate \n"
			+ " select #history.*  \n"
			+ " ,case when xmis.org_部门归属部门表.父部门ID IS null then #history.subDeptID else xmis.org_部门归属部门表.父部门ID end as deptID  \n"
			+ " into #history2  \n"
			+ " from #history,xmis.org_部门归属部门表  \n"
			+ " where #history.subDeptID *= xmis.org_部门归属部门表.部门ID \n"
			+ " select #history2.subDeptID  as deptID,startDay,endDay,COUNT(*) as total  \n"
			+ " into #re  \n"
			+ " from #history2  \n"
			+ " where subDeptID in (select 部门ID from #d)  \n"
			+ " group by subDeptID,startDay,endDay \n"
			+ " select identity(int,0,1) as row_no,#weeks.startDay,#weeks.endDay into #allWeeks from #weeks order by #weeks.startDay,#weeks.endDay \n"
			+ " declare @count int  \n"
			+ " select @count = count(*) from #allWeeks  \n"
			+ " declare @i int  \n"
			+ " set @i = 0  \n"
			+ " while(@i < @count)  \n"
			+ " begin  \n"
			+ " 	declare @sd varchar(10)  \n"
			+ " 	declare @ed varchar(10)  \n"
			+ " 	select @sd = startDay,@ed=endDay from #allWeeks where row_no = @i    \n"
			+ " 	insert into #re select #d.部门ID,@sd,@ed,0 from #d where #d.部门ID not in (select #re.deptID from #re where startDay = @sd and endDay = @ed)  \n"
			+ " 	set @i = @i + 1  \n"
			+ " end  \n"
			+ " select #re.deptID,#re.startDay + 'Z' + #re.endDay as weeks,#re.total,#d.部门名称 as deptName,0 as deptPx,cast(#allWeeks.row_no + 1 as varchar(100)) as weeknum  \n"
			+ " into #result   \n"
			+ " from #re,#d,#allWeeks   \n"
			+ " where #re.deptID = #d.部门ID   \n"
			+ " and #re.startDay = #allWeeks.startDay  \n"
			+ " and #re.endDay = #allWeeks.endDay  \n"
			+ " select * into #pxtemp from #result where 1=2    \n"
			+ " if(@sortDate = '小计') begin     \n"
			+ " 	insert into #pxtemp select deptID,'小计',SUM(total),deptName,0,'小计' from #result group by deptID,deptName   \n"
			+ " end    \n"
			+ " else begin    \n"
			+ " 	insert into #pxtemp select * from #result where weeks = @sortDate  \n"
			+ " end   \n"
			+ " select identity(int,1,1) as row_no,*   \n"
			+ " into #px  \n"
			+ " from #pxtemp \n"
			+ " order by total desc,deptPX  \n"
			+ " update #result set #result.deptPx = #px.row_no from #result,#px where #result.deptID = #px.deptID  \n"
			+ " select 99999 as deptID,weeks,SUM(total) as total,'合计' as deptName,99999 as deptPx,cast(weeknum as varchar(100)) as weeknum into #totalTemp from #result group by weeks,weeknum \n"
			+ " union all   \n"
			+ " select deptID,'小计',SUM(total),deptName,99999,'<div style=\"display:none;\">小计</div>' from #result group by deptID,deptName  \n"
			+ " union all  \n"
			+ " select 99999,'小计',SUM(total),'合计',99999,'<div style=\"display:none;\">小计</div>' from #result  \n"
			+ " insert into #result select * from #totalTemp  \n"
			+ " update #result set #result.deptPx = #px.row_no from #result,#px where #result.deptID = #px.deptID and #result.weeks = '小计'  \n"
			+ " select * from #result \n";
		System.out.println(sql);
		return jt.queryForList(sql, new Object[]{sort,deptName});
	}

	public List getPersonAndMonthTotalInCompany(String start,String end,String sort) {
		String sql = " SET NOCOUNT ON  \n"  
			+ " declare @beginDate varchar(7) --开始日期   \n"  
			+ " declare @endDate varchar(7)   --结束日期  \n"  
			+ " declare @betweenMonth int   --结束日期与当前日期之间相差的月数   \n"  
			+ " declare @sortDate varchar(7)   --排序  \n"  
			+ " set @beginDate= ? \n"  
			+ " set @endDate= ? \n"  
			+ " set @sortDate=? \n"  
			+ " SELECT dh.人员ID  \n"  
			+ " ,dh.部门ID  \n"  
			+ " ,RTRIM(hr.姓氏) + RTRIM(hr.名字) as userName  \n"  
			+ " into #user  \n"  
			+ " FROM xmis.hr_人员部门关系表 as dh,xmis.hr_人员 hr  \n"  
			+ " where dh.人员ID = hr.人员ID  \n"  
			+ " and hr.人员ID > 0 AND (hr.禁用 is null or hr.禁用= 0) \n"  
			+ " and  dh.部门ID in (select 部门ID from xmis.org_部门归属公司表 where 公司ID = 1) \n"  
			+ " select xmis.sys_系统日志.id \n"  
			+ " ,xmis.sys_系统日志.userID   \n"  
			+ " ,xmis.sys_系统日志.opTime   \n"  
			+ " ,convert(varchar(7),xmis.sys_系统日志.opTime,120) as loginmonth \n"  
			+ " into #history   \n"  
			+ " from xmis.sys_系统日志,#user   \n"  
			+ " where userID<>-1   \n"  
			+ " and opType = 'login' \n"  
			+ " and xmis.sys_系统日志.userID = #user.人员ID \n"  
			+ " union all   \n"  
			+ " select xmis.sys_系统日志.id   \n"  
			+ " ,xmis.sys_系统日志.userID   \n"  
			+ " ,xmis.sys_系统日志.opTime   \n"  
			+ " ,convert(varchar(7),xmis.sys_系统日志.opTime,120) as loginmonth \n"  
			+ " from xmis.sys_系统日志,#user \n"  
			+ " where userID<>-1   \n"  
			+ " and (opType = 'timeout' or opType = 'loginout')   \n"  
			+ " and opTime>='2011-10-01'   \n"  
			+ " and opTime<'2012-06-01' \n"  
			+ " and xmis.sys_系统日志.userID = #user.人员ID \n"  
			+ " select #history.*   \n"  
			+ " into #history2   \n"  
			+ " from #history \n"  
			+ " where loginmonth>=@beginDate    \n"  
			+ " and loginmonth<=@endDate  \n"  
			+ " select #history2.userID,loginmonth,COUNT(*) as total   \n"  
			+ " into #re   \n"  
			+ " from #history2   \n"  
			+ " group by userID,loginmonth   \n"  
			+ " --根据开始日期和结束日期及当前日期，查找所有月份 \n"
			+ " DECLARE @today VARCHAR(10) \n"
			+ " SELECT @today = CONVERT(VARCHAR(7),GETDATE(),120) + '-01' \n"
			+ " select convert(varchar(7),null,120) as loginmonth into #months where 1=2   \n"
			+ " declare @tdate datetime   \n"
			+ " set @tdate = @beginDate + '-01'   \n"
			+ " IF @tdate < '2011-08-01' BEGIN \n"
			+ " 	SET @tdate = '2011-08-01' \n"
			+ " END \n"
			+ " while(@tdate <= @endDate + '-01' AND @tdate <= @today) begin    \n"
			+ "     insert into #months select convert(varchar(7),@tdate,120)   \n"
			+ "     set @tdate = DATEADD(MONTH,1,@tdate) \n"
			+ " end   \n"
			+ " select identity(int,0,1) as row_no,#months.loginmonth into #allMonth from #months  \n"
			+ " ----------------------------------------------- \n"  
			+ " declare @count int   \n"  
			+ " select @count = count(*) from #allMonth   \n"  
			+ " declare @i int   \n"  
			+ " set @i = 0   \n"  
			+ " while(@i < @count)   \n"  
			+ "  begin   \n"  
			+ " declare @yearAndMonth varchar(7)   \n"  
			+ " select @yearAndMonth = loginmonth from #allMonth where row_no = @i   \n"  
			+ " insert into #re select #user.人员ID,@yearAndMonth,0 from #user where #user.人员ID not in (select #re.userID from #re where loginmonth = @yearAndMonth)   \n"  
			+ " set @i = @i + 1   \n"  
			+ " end   \n"  
			+ " select #re.*,#user.userName as userName,0 as userPx   \n"  
			+ " into #result   \n"  
			+ " from #re,#user  \n"  
			+ " where #re.userID = #user.人员ID \n"  
			+ " select * into #pxtemp from #result where 1=2    \n"  
			+ "  if(@sortDate = '小计') begin     \n"  
			+ "  	insert into #pxtemp select userID,'小计',SUM(total),userName,0 from #result group by userID,userName     \n"  
			+ "  end    \n"  
			+ "  else begin    \n"  
			+ " 	insert into #pxtemp select * from #result where loginmonth = @sortDate  \n"    
			+ " end    \n"  
			+ " select identity(int,1,1) as row_no,*    \n"  
			+ " into #px   \n"  
			+ " from #pxtemp    \n"  
			+ " order by total desc  \n"  
			+ " update #result set #result.userPx = #px.row_no from #result,#px where #result.userID = #px.userID   \n"  
//			+ " select 99999 as userID,loginmonth,SUM(total) as total,'合计' as userName,99999 as userPx into #totalTemp from #result group by loginmonth   \n"  
//			+ " union all    \n"  
//			+ " select userID,'小计',SUM(total),userName,99999 from #result group by userID,userName   \n"  
//			+ " union all   \n"  
//			+ " select 99999,'小计',SUM(total),'合计',99999 from #result   \n"  
//			+ " insert into #result select * from #totalTemp   \n"  
			+ " delete from #result where userPx > 20  \n"
			+ " insert into #result select userID,'小计',SUM(total),userName,99999 from #result group by userID,userName \n"
			+ " update #result set #result.userPx = #px.row_no from #result,#px where #result.userID = #px.userID and #result.loginmonth = '小计'   \n"  
			+ " select *   \n"  
			+ " ,case when SUBSTRING(loginmonth,1,4)='小计' then '<div style=\"display:none;\">2222</div>' else SUBSTRING(loginmonth,1,4) end as year  \n"  
			+ " ,case when SUBSTRING(loginmonth,6,2)='' then '小计' else SUBSTRING(loginmonth,6,2) end as month from #result   \n" ;
		System.out.println(sql);
		return jt.queryForList(sql, new Object[]{start,end,sort});
	}

	public List getPersonOfCompInOneWeek(String start, String end, String sort) {
		String sql = "SET NOCOUNT ON \n" 
			+ " declare @currentMonth varchar(7)  \n"
			+ " declare @endMonth varchar(7)  \n"
			+ " declare @beginDate varchar(10) --开始日期    \n"
			+ " declare @endDate varchar(10)   --结束日期  \n"
			+ " declare @sortDate varchar(21)   --排序   \n"
			+ " set @currentMonth = ? \n"
			+ " set @endMonth = ? \n"
			+ " set @sortDate = ? \n"
			+ " --设置开始日期和结束日期  \n"
			+ " set @beginDate= @currentMonth + '-01'  \n"
			+ " SELECT @endDate = convert(varchar(10),DATEADD(Day,0,CONVERT(char(8),DATEADD(Month,1,@beginDate),120)+'1'),120)  \n"
			+ " --查找该部门下的所有用户  \n"
			+ " SELECT dh.人员ID  \n"
			+ " ,dh.部门ID  \n"
			+ " ,RTRIM(hr.姓氏) + RTRIM(hr.名字) as userName  \n"
			+ " into #user  \n"
			+ " FROM xmis.hr_人员部门关系表 as dh,xmis.hr_人员 hr  \n"
			+ " where dh.人员ID = hr.人员ID  \n"
			+ " and hr.人员ID > 0 AND (hr.禁用 is null or hr.禁用= 0) \n"
			+ " and  dh.部门ID in (select 部门ID from xmis.org_部门归属公司表 where 公司ID = 1) \n"
			+ " select xmis.sys_系统日志.id    \n"
			+ " ,xmis.sys_系统日志.userID    \n"
			+ " ,xmis.sys_系统日志.opTime    \n"
			+ " ,case when DATEADD(Day,0-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime) < @beginDate then convert(varchar(10),@beginDate,120) else convert(varchar(10),DATEADD(Day,0-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end as startDay  \n"
			+ " ,case when DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime) > @endDate then convert(varchar(10),DATEADD(DAY,-1,@endDate),120) else convert(varchar(10),DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end as endDay  \n"
			+ " into #history2    \n"
			+ " from xmis.sys_系统日志,#user \n"
			+ " where userID<>-1    \n"
			+ " and opType = 'login' \n"
			+ " and xmis.sys_系统日志.userID = #user.人员ID \n"
			+ " and opTime >= @beginDate  \n"
			+ " and opTime < @endDate  \n"
			+ " union all \n"
			+ " select xmis.sys_系统日志.id    \n"
			+ " ,xmis.sys_系统日志.userID    \n"
			+ " ,xmis.sys_系统日志.opTime    \n"
			+ " ,case when DATEADD(Day,0-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime) < @beginDate then convert(varchar(10),@beginDate,120) else convert(varchar(10),DATEADD(Day,0-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end  \n"
			+ " ,case when DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime) > @endDate then convert(varchar(10),DATEADD(DAY,-1,@endDate),120) else convert(varchar(10),DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end    \n"
			+ " from xmis.sys_系统日志,#user \n"
			+ " where userID<>-1    \n"
			+ " and (opType = 'timeout' or opType = 'loginout')    \n"
			+ " and opTime>='2011-10-01'    \n"
			+ " and opTime<'2012-06-01' \n"
			+ " and xmis.sys_系统日志.userID = #user.人员ID \n"
			+ " and opTime >= @beginDate  \n"
			+ " and opTime < @endDate  \n"
			+ " select #history2.userID,startDay,endDay,COUNT(*) as total  \n"
			+ " into #re    \n"
			+ " from #history2    \n"
			+ " group by userID,startDay,endDay  \n"
			+ " --查找一月内所有周  \n"
			+ " declare @tempDate datetime  \n"
			+ " select @tempDate = DATEADD(Day,0-(DATEPART(Weekday,@beginDate)+@@DATEFIRST-2)%7-1,@beginDate)  \n"
			+ " select CONVERT(varchar(10),null,120) as startDay,CONVERT(varchar(10),null,120) as endDay into #weeks where 1=2  \n"
			+ " while(@tempDate < @endDate) begin  \n"
			+ "    insert into #weeks   \n"
			+ "    values(case when @tempDate < @beginDate then CONVERT(varchar(10),@beginDate,120) else CONVERT(varchar(10),@tempDate,120) end,case when DATEADD(DAY,6,@tempDate) > DATEADD(DAY,-1,@endDate) then CONVERT(varchar(10),DATEADD(DAY,-1,@endDate),120) else CONVERT(varchar(10),DATEADD(DAY,6,@tempDate),120) end)  \n"
			+ "    select @tempDate = DATEADD(Day,7,@tempDate)  \n"
			+ " end  \n"
			+ " --得到所有月份   \n"
			+ " select identity(int,0,1) as row_no,#weeks.startDay,#weeks.endDay into #allWeeks from #weeks where endDay >= startDay \n"
			+ " declare @count int    \n"
			+ " select @count = count(*) from #allWeeks    \n"
			+ " declare @i int    \n"
			+ " set @i = 0    \n"
			+ " while(@i < @count)    \n"
			+ " begin    \n"
			+ " declare @sd varchar(10)  \n"
			+ " declare @ed varchar(10)  \n"
			+ " select @sd = startDay,@ed=endDay from #allWeeks where row_no = @i    \n"
			+ " insert into #re select #user.人员ID,@sd,@ed,0 from #user where #user.人员ID not in (select #re.userID from #re where startDay = @sd and endDay = @ed)    \n"
			+ " set @i = @i + 1    \n"
			+ " end    \n"
			+ " select #re.userID,#re.startDay + 'Z' + #re.endDay as weeks,#re.total,#user.userName as userName,0 as userPx,cast(#allWeeks.row_no + 1 as varchar(100)) as weeknum    \n"
			+ " into #result    \n"
			+ " from #re,#user,#allWeeks  \n"
			+ " where #re.userID = #user.人员ID  \n"
			+ " and #re.startDay = #allWeeks.startDay  \n"
			+ " and #re.endDay = #allWeeks.endDay  \n"
			+ " --select * from #result  \n"
			+ " select * into #pxtemp from #result where 1=2  \n"
			+ " if(@sortDate = '小计') begin   \n"
			+ " 	insert into #pxtemp select userID,'小计',SUM(total),userName,0,'小计' from #result group by userID,userName   \n"
			+ " end  \n"
			+ " else begin  \n"
			+ " 	insert into #pxtemp select * from #result where weeks = @sortDate  \n"
			+ " end  \n"
			+ " select identity(int,1,1) as row_no,*     \n"
			+ " into #px    \n"
			+ " from #pxtemp  \n"
			+ " order by total desc   \n"
			+ " update #result set #result.userPx = #px.row_no from #result,#px where #result.userID = #px.userID  \n"
			+ " delete from #result where userPx > 20  \n"
			+ " insert into #result select userID,'小计',SUM(total),userName,0,'<div style=\"display:none;\">小计</div>' from #result group by userID,userName  \n"
			+ " update #result set #result.userPx = #px.row_no from #result,#px where #result.userID = #px.userID and #result.weeks = '小计'  \n"
			+ " select *  from #result  \n";
		System.out.println(sql);
		return jt.queryForList(sql, new Object[]{start,end,sort});
	}

	public List getMonthAccounting5(String start, String end, String sort,
			String deptName) {
		String sql = " SET NOCOUNT ON \n" 
			+ " declare @beginDate varchar(7) --开始日期   \n"
			+ " declare @endDate varchar(7)   --结束日期  \n"
			+ " declare @betweenMonth int   --结束日期与当前日期之间相差的月数   \n"
			+ " declare @sortDate varchar(7)   --排序  \n"
			+ " set @beginDate= ? \n"
			+ " set @endDate= ? \n"
			+ " set @sortDate= ? \n"
			+ " declare @deptName varchar(100) --部门名称  \n"
			+ " declare @deptID int --部门名称  \n"
			+ " set @deptName= ? \n"
			+ " SELECT @deptID= \n"
			+ " comp.部门ID  \n"
			+ " FROM xmis.org_部门归属公司表 as comp,xmis.org_部门 as dept  \n"
			+ " where comp.公司ID = 1 and dept.部门ID = comp.部门ID  \n"
			+ " and dept.部门名称 = @deptName  \n"
			+ " SELECT dh.人员ID   \n"
			+ " ,dh.部门ID   \n"
			+ " ,RTRIM(hr.姓氏) + RTRIM(hr.名字) as userName   \n"
			+ " into #user   \n"
			+ " FROM xmis.hr_人员部门关系表 as dh,xmis.hr_人员 hr   \n"
			+ " where dh.部门ID in (  SELECT 部门ID FROM xmis.org_部门归属部门表 where 父部门ID =@deptID)   \n"
			+ " and dh.人员ID = hr.人员ID   \n"
			+ " and hr.人员ID > 0 AND (hr.禁用 is null or hr.禁用= 0)   \n"
			+ " select xmis.sys_系统日志.id   \n"
			+ " ,xmis.sys_系统日志.userID   \n"
			+ " ,xmis.sys_系统日志.opTime   \n"
			+ " ,convert(varchar(7),xmis.sys_系统日志.opTime,120) as loginmonth   \n"
			+ " ,xmis.hr_人员部门关系表.部门ID as subDeptID   \n"
			+ " into #history   \n"
			+ " from xmis.sys_系统日志,xmis.hr_人员部门关系表   \n"
			+ " where userID<>-1   \n"
			+ " and opType = 'login'   \n"
			+ " and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID   \n"
			+ " union all   \n"
			+ " select xmis.sys_系统日志.id   \n"
			+ " ,xmis.sys_系统日志.userID   \n"
			+ " ,xmis.sys_系统日志.opTime   \n"
			+ " ,convert(varchar(7),xmis.sys_系统日志.opTime,120) as loginmonth   \n"
			+ " ,xmis.hr_人员部门关系表.部门ID as subDeptID   \n"
			+ " from xmis.sys_系统日志,xmis.hr_人员部门关系表   \n"
			+ " where userID<>-1   \n"
			+ " and (opType = 'timeout' or opType = 'loginout')   \n"
			+ " and opTime>='2011-10-01'   \n"
			+ " and opTime<'2012-06-01'   \n"
			+ " and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID   \n"
			+ " select #history.*   \n"
			+ " ,case when xmis.org_部门归属部门表.父部门ID IS null then #history.subDeptID else xmis.org_部门归属部门表.父部门ID end as deptID   \n"
			+ " into #history2   \n"
			+ " from #history,xmis.org_部门归属部门表   \n"
			+ " where #history.subDeptID *= xmis.org_部门归属部门表.部门ID   \n"
			+ " and loginmonth>=@beginDate    \n"
			+ " and loginmonth<=@endDate  \n"
			+ " select #history2.userID,loginmonth,COUNT(*) as total   \n"
			+ " into #re   \n"
			+ " from #history2   \n"
			+ " group by userID,loginmonth   \n"
			+ " --根据开始日期和结束日期及当前日期，查找所有月份 \n"
			+ " DECLARE @today VARCHAR(10) \n"
			+ " SELECT @today = CONVERT(VARCHAR(7),GETDATE(),120) + '-01' \n"
			+ " select convert(varchar(7),null,120) as loginmonth into #months where 1=2   \n"
			+ " declare @tdate datetime   \n"
			+ " set @tdate = @beginDate + '-01'   \n"
			+ " IF @tdate < '2011-08-01' BEGIN \n"
			+ " 	SET @tdate = '2011-08-01' \n"
			+ " END \n"
			+ " while(@tdate <= @endDate + '-01' AND @tdate <= @today) begin    \n"
			+ "     insert into #months select convert(varchar(7),@tdate,120)   \n"
			+ "     set @tdate = DATEADD(MONTH,1,@tdate) \n"
			+ " end   \n"
			+ " select identity(int,0,1) as row_no,#months.loginmonth into #allMonth from #months  \n"
			+ " ----------------------------------------------- \n"
			+ " declare @count int   \n"
			+ " select @count = count(*) from #allMonth   \n"
			+ " declare @i int   \n"
			+ " set @i = 0   \n"
			+ " while(@i < @count)   \n"
			+ "  begin   \n"
			+ " declare @yearAndMonth varchar(7)   \n"
			+ " select @yearAndMonth = loginmonth from #allMonth where row_no = @i   \n"
			+ " insert into #re select #user.人员ID,@yearAndMonth,0 from #user where #user.人员ID not in (select #re.userID from #re where loginmonth = @yearAndMonth)   \n"
			+ " set @i = @i + 1   \n"
			+ " end   \n"
			+ " select #re.*,#user.userName as userName,0 as userPx   \n"
			+ " into #result   \n"
			+ " from #re,#user  \n"
			+ " where #re.userID = #user.人员ID   \n"
			+ " select * into #pxtemp from #result where 1=2    \n"
			+ " if(@sortDate = '小计') begin     \n"
			+ " 	insert into #pxtemp select userID,'小计',SUM(total),userName,0 from #result group by userID,userName     \n"
			+ " end    \n"
			+ " else begin    \n"
			+ " 	insert into #pxtemp select * from #result where loginmonth = @sortDate  \n"  
			+ " end    \n"
			+ " select identity(int,1,1) as row_no,*    \n"
			+ " into #px   \n"
			+ " from #pxtemp    \n"
			+ " order by total desc  \n"
			+ " update #result set #result.userPx = #px.row_no from #result,#px where #result.userID = #px.userID   \n"
			+ " select 99999 as userID,loginmonth,SUM(total) as total,'合计' as userName,99999 as userPx into #totalTemp from #result group by loginmonth   \n"
			+ " union all    \n"
			+ " select userID,'小计',SUM(total),userName,99999 from #result group by userID,userName   \n"
			+ " union all   \n"
			+ " select 99999,'小计',SUM(total),'合计',99999 from #result   \n"
			+ " insert into #result select * from #totalTemp   \n"
			+ " update #result set #result.userPx = #px.row_no from #result,#px where #result.userID = #px.userID and #result.loginmonth = '小计'  \n" 
			+ " select *   \n"
			+ " ,case when SUBSTRING(loginmonth,1,4)='小计' then '<div style=\"display:none;\">2222</div>' else SUBSTRING(loginmonth,1,4) end as year  \n"
			+ " ,case when SUBSTRING(loginmonth,6,2)='' then '小计' else SUBSTRING(loginmonth,6,2) end as month from #result  \n";
		System.out.println(sql);
		return jt.queryForList(sql, new Object[]{start,end,sort,deptName});
	}

	public List getPersonOfCompByComp(String sort) {
		String sql = " SET NOCOUNT ON \n" 
			+ " declare @beginDate datetime --开始日期   \n"
			+ " declare @endDate datetime   --结束日期  \n"
			+ " declare @numOfWeek int  \n"
			+ " declare @tempDate datetime   \n"
			+ " declare @deptID int --部门名称   \n"
			+ " declare @sortDate varchar(21)   --排序   \n"
			+ " select @endDate = GETDATE()   \n"
			+ " set @sortDate=? \n"
			+ " --得到当先日期的周一是哪天  \n"
			+ " select @numOfWeek = datepart(weekday,@endDate)   --日期是周内的第几天  \n"
			+ " if(@numOfWeek = 1) --如果当天在本周是第一天，即周日  \n"
			+ " begin   \n"
			+ " 	set @tempDate = @endDate  \n"
			+ " end  \n"
			+ "  else begin  \n"
			+ " 	select @tempDate = DATEADD(Day,0-(DATEPART(Weekday,@endDate)+@@DATEFIRST-2)%7-1,@endDate)  \n"
			+ "  end  \n"
			+ " --查找所有周  \n"
			+ " select CONVERT(varchar(10),null,120) as startDay,CONVERT(varchar(10),null,120) as endDay into #weeks where 1=2  \n" 
			+ " declare @j int  \n"
			+ " set @j = 0  \n"
			+ " while(@j < 4) begin   \n"
			+ "   insert into #weeks    \n"
			+ "   values(CONVERT(varchar(10),@tempDate,120),CONVERT(varchar(10),DATEADD(DAY,6,@tempDate),120))   \n"
			+ "   select @tempDate = DATEADD(Day,-7,@tempDate)   \n"
			+ "   set @j = @j + 1  \n"
			+ "  end   \n"
			+ " --设置开始日期  \n"
			+ " select @beginDate = min(CONVERT(datetime,startDay,120)) from #weeks  \n"
			+ " SELECT 公司ID   \n"
			+ " ,xmis.org_部门归属公司表.部门ID   \n"
			+ " ,xmis.org_部门.部门名称   \n"
			+ " ,xmis.org_部门归属公司表.排序   \n"
			+ " into #d   \n"
			+ " FROM xmis.org_部门归属公司表,xmis.org_部门   \n"
			+ " where 公司ID = 1 \n"
			+ " and xmis.org_部门归属公司表.部门ID = xmis.org_部门.部门ID  \n"
			+ " --得到所有人员  \n"
			+ " SELECT dh.人员ID   \n"
			+ " ,dh.部门ID   \n"
			+ " ,RTRIM(hr.姓氏) + RTRIM(hr.名字) as userName   \n"
			+ " into #user   \n"
			+ " FROM xmis.hr_人员部门关系表 as dh,xmis.hr_人员 hr,#d \n"
			+ " where dh.部门ID = #d.部门ID \n"
			+ " and dh.人员ID = hr.人员ID   \n"
			+ " and hr.人员ID > 0 AND (hr.禁用 is null or hr.禁用= 0)   \n"
			+ " select xmis.sys_系统日志.id   \n"
			+ " ,xmis.sys_系统日志.userID   \n"
			+ " ,xmis.sys_系统日志.opTime   \n"
			+ " ,xmis.hr_人员部门关系表.部门ID as subDeptID   \n"
			+ " into #h  \n"
			+ " from xmis.sys_系统日志,xmis.hr_人员部门关系表,xmis.hr_人员   \n"
			+ " where userID<>-1 and opType = 'login' and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID   \n"
			+ " and xmis.sys_系统日志.userID = xmis.hr_人员.人员ID   \n"
			+ " AND (xmis.hr_人员.禁用 is null or xmis.hr_人员.禁用= 0)  \n"
			+ " union all   \n"
			+ " select xmis.sys_系统日志.id   \n"
			+ " ,xmis.sys_系统日志.userID   \n"
			+ " ,xmis.sys_系统日志.opTime   \n"
			+ " ,xmis.hr_人员部门关系表.部门ID as subDeptID   \n"
			+ " from xmis.sys_系统日志,xmis.hr_人员部门关系表,xmis.hr_人员   \n"
			+ " where userID<>-1 and (opType = 'timeout' or opType = 'loginout') and opTime>='2011-10-01' and opTime<'2012-06-01' and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID   \n"
			+ " and xmis.sys_系统日志.userID = xmis.hr_人员.人员ID   \n"
			+ " AND (xmis.hr_人员.禁用 is null or xmis.hr_人员.禁用= 0)  \n"
			+ " select *  \n"
			+ " ,case when datepart(weekday,opTime) = 1 then convert(varchar(10),opTime,120) else convert(varchar(10),DATEADD(Day,0-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end as startDay   \n"
			+ " ,case when datepart(weekday,opTime) = 1 then convert(varchar(10),dateadd(day,6,opTime),120) else convert(varchar(10),DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end as endDay    \n"
			+ " into #history  \n"
			+ " from #h where opTime >=@beginDate and opTime <=@endDate  \n"
			+ " select #history.*   \n"
			+ " ,case when xmis.org_部门归属部门表.父部门ID IS null then #history.subDeptID else xmis.org_部门归属部门表.父部门ID end as deptID   \n"
			+ " into #history2   \n"
			+ " from #history,xmis.org_部门归属部门表   \n"
			+ " where #history.subDeptID *= xmis.org_部门归属部门表.部门ID   \n"
			+ " select #history2.userID,startDay,endDay,COUNT(*) as total   \n"
			+ " into #re   \n"
			+ " from #history2   \n"
			+ " group by userID,startDay,endDay  \n"
			+ " select identity(int,0,1) as row_no,#weeks.startDay,#weeks.endDay into #allWeeks from #weeks order by #weeks.startDay,#weeks.endDay  \n"
			+ " declare @count int   \n"
			+ " select @count = count(*) from #allWeeks  \n" 
			+ " declare @i int   \n"
			+ " set @i = 0   \n"
			+ " while(@i < @count)   \n"
			+ " begin   \n"
			+ " 	declare @sd varchar(10)   \n"
			+ " 	declare @ed varchar(10)   \n"
			+ " 	select @sd = startDay,@ed=endDay from #allWeeks where row_no = @i   \n" 
		 	+ "  	insert into #re select #user.人员ID,@sd,@ed,0 from #user where #user.人员ID not in (select #re.userID from #re where startDay = @sd and endDay = @ed)   \n"
		 	+ "  	set @i = @i + 1   \n"
		 	+ " end   \n"
		 	+ " select #re.userID,#re.startDay + 'Z' + #re.endDay as weeks,#re.total,#user.userName as userName,0 as userPx,cast(#allWeeks.row_no + 1 as varchar(100)) as weeknum   \n"
		 	+ " into #result    \n"
		 	+ " from #re,#user,#allWeeks    \n"
		 	+ " where #re.userID = #user.人员ID    \n"
		 	+ " and #re.startDay = #allWeeks.startDay   \n"
		 	+ " and #re.endDay = #allWeeks.endDay   \n"
		 	+ " select * into #pxtemp from #result where 1=2     \n"
		 	+ " if(@sortDate = '小计') begin      \n"
		 	+ " 	insert into #pxtemp select userID,'小计',SUM(total),userName,0,'小计' from #result group by userID,userName   \n"   
		 	+ " end     \n"
		 	+ " else begin    \n" 
		 	+ " 	insert into #pxtemp select * from #result where weeks = @sortDate    \n"
		 	+ " end  \n"
		 	+ " select identity(int,1,1) as row_no,*     \n"
		 	+ " into #px    \n"
		 	+ " from #pxtemp     \n"
		 	+ " order by total desc   \n"
		 	+ " update #result set #result.userPx = #px.row_no from #result,#px where #result.userID = #px.userID   \n"
		 	+ " delete from #result where userPX > 20 \n"
		 	+ " insert into #result select userID,'小计',SUM(total),userName,99999,'<div style=\"display:none;\">小计</div>' from #result group by userID,userName    \n"
			+ " update #result set #result.userPx = #px.row_no from #result,#px where #result.userID = #px.userID and #result.weeks = '小计'   \n"
			+ " select * from #result \n";
		 System.out.println(sql);
		return jt.queryForList(sql, new Object[]{sort});
	}

	public List getLastAccounting7(String sort, String deptName) {
		String sql = "SET NOCOUNT ON \n"
			+ " declare @beginDate datetime --开始日期   \n"
			+ " declare @endDate datetime   --结束日期  \n"
			+ " declare @numOfWeek int  \n"
			+ " declare @tempDate datetime   \n"
			+ " declare @deptName varchar(100) --部门名称   \n"
			+ " declare @deptID int --部门名称   \n"
			+ " declare @sortDate varchar(21)   --排序 \n"
			+ " select @endDate = GETDATE()   \n"
			+ " set @sortDate=? \n"
			+ " set @deptName= ? \n"
			+ " --得到当先日期的周一是哪天  \n"
			+ " select @numOfWeek = datepart(weekday,@endDate)   --日期是周内的第几天  \n"
			+ " if(@numOfWeek = 1) --如果当天在本周是第一天，即周日  \n"
			+ " begin   \n"
			+ " 	set @tempDate = @endDate  \n"
			+ " end  \n"
			+ " else begin  \n"
			+ " 	select @tempDate = DATEADD(Day,0-(DATEPART(Weekday,@endDate)+@@DATEFIRST-2)%7-1,@endDate)  \n"
			+ " end  \n"
			+ " --查找所有周  \n"
			+ " select CONVERT(varchar(10),null,120) as startDay,CONVERT(varchar(10),null,120) as endDay into #weeks where 1=2   \n"
			+ " declare @j int  \n"
			+ " set @j = 0  \n"
			+ " while(@j < 4) begin   \n"
			+ "   insert into #weeks    \n"
			+ "   values(CONVERT(varchar(10),@tempDate,120),CONVERT(varchar(10),DATEADD(DAY,6,@tempDate),120))   \n"
			+ "   select @tempDate = DATEADD(Day,-7,@tempDate)   \n"
			+ "   set @j = @j + 1  \n"
			+ " end   \n"
			+ " --设置开始日期  \n"
			+ " select @beginDate = min(CONVERT(datetime,startDay,120)) from #weeks  \n"
			+ " --得到部门ID  \n"
			+ " SELECT @deptID=  \n"
			+ " comp.部门ID   \n"
			+ " FROM xmis.org_部门归属公司表 as comp,xmis.org_部门 as dept   \n"
			+ " where comp.公司ID = 1 and dept.部门ID = comp.部门ID   \n"
			+ " and dept.部门名称 = @deptName   \n"
			+ " SELECT dh.人员ID    \n"
			+ " ,dh.部门ID    \n"
			+ " ,RTRIM(hr.姓氏) + RTRIM(hr.名字) as userName    \n"
			+ " into #user    \n"
			+ " FROM xmis.hr_人员部门关系表 as dh,xmis.hr_人员 hr    \n"
			+ " where dh.部门ID in (  SELECT 部门ID FROM xmis.org_部门归属部门表 where 父部门ID =@deptID)    \n"
			+ " and dh.人员ID = hr.人员ID    \n"
			+ " and hr.人员ID > 0 AND (hr.禁用 is null or hr.禁用= 0) \n"
			+ " select xmis.sys_系统日志.id   \n"
			+ " ,xmis.sys_系统日志.userID   \n"
			+ " ,xmis.sys_系统日志.opTime   \n"
			+ " ,xmis.hr_人员部门关系表.部门ID as subDeptID   \n"
			+ " into #h  \n"
			+ " from xmis.sys_系统日志,xmis.hr_人员部门关系表,xmis.hr_人员   \n"
			+ " where userID<>-1 and opType = 'login' and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID   \n"
			+ " and xmis.sys_系统日志.userID = xmis.hr_人员.人员ID   \n"
			+ " AND (xmis.hr_人员.禁用 is null or xmis.hr_人员.禁用= 0)  \n"
			+ " union all   \n"
			+ " select xmis.sys_系统日志.id   \n"
			+ " ,xmis.sys_系统日志.userID   \n"
			+ " ,xmis.sys_系统日志.opTime   \n"
			+ " ,xmis.hr_人员部门关系表.部门ID as subDeptID   \n"
			+ " from xmis.sys_系统日志,xmis.hr_人员部门关系表,xmis.hr_人员   \n"
			+ " where userID<>-1 and (opType = 'timeout' or opType = 'loginout') and opTime>='2011-10-01' and opTime<'2012-06-01' and xmis.sys_系统日志.userID = xmis.hr_人员部门关系表.人员ID   \n"
			+ " and xmis.sys_系统日志.userID = xmis.hr_人员.人员ID   \n"
			+ " AND (xmis.hr_人员.禁用 is null or xmis.hr_人员.禁用= 0)  \n"
			+ " select *  \n"
		 + " ,case when datepart(weekday,opTime) = 1 then convert(varchar(10),opTime,120) else convert(varchar(10),DATEADD(Day,0-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end as startDay   \n"
		 + " ,case when datepart(weekday,opTime) = 1 then convert(varchar(10),dateadd(day,6,opTime),120) else convert(varchar(10),DATEADD(Day,6-(DATEPART(Weekday,opTime)+@@DATEFIRST-2)%7-1,opTime),120) end as endDay    \n"
		 + " into #history  \n"
		 + " from #h where opTime >=@beginDate and opTime <=@endDate  \n"
		 + " select #history.*   \n"
		 + " ,case when xmis.org_部门归属部门表.父部门ID IS null then #history.subDeptID else xmis.org_部门归属部门表.父部门ID end as deptID   \n"
		 + " into #history2   \n"
		 + " from #history,xmis.org_部门归属部门表   \n"
		 + " where #history.subDeptID *= xmis.org_部门归属部门表.部门ID   \n"
		 + " select #history2.userID,startDay,endDay,COUNT(*) as total   \n"
		 + " into #re   \n"
		 + " from #history2   \n"
		 + " group by userID,startDay,endDay  \n"
		 + " select identity(int,0,1) as row_no,#weeks.startDay,#weeks.endDay into #allWeeks from #weeks order by #weeks.startDay,#weeks.endDay  \n"
		 + " declare @count int   \n"
		 + " select @count = count(*) from #allWeeks   \n"
		 + " declare @i int   \n"
		 + " set @i = 0   \n"
		 + " while(@i < @count)   \n"
		 + " begin   \n"
		 + " 	declare @sd varchar(10)   \n"
		 + " 	declare @ed varchar(10)   \n"
		 + " 	select @sd = startDay,@ed=endDay from #allWeeks where row_no = @i    \n"
		 + " 	insert into #re select #user.人员ID,@sd,@ed,0 from #user where #user.人员ID not in (select #re.userID from #re where startDay = @sd and endDay = @ed)   \n"
		 + " 	set @i = @i + 1   \n"
		 + " end   \n"
		 + " select #re.userID,#re.startDay + 'Z' + #re.endDay as weeks,#re.total,#user.userName as userName,0 as userPx,cast(#allWeeks.row_no + 1 as varchar(100)) as weeknum   \n"
		 + " into #result    \n"
		 + " from #re,#user,#allWeeks    \n"
		 + " where #re.userID = #user.人员ID    \n"
		 + " and #re.startDay = #allWeeks.startDay   \n"
		 + " and #re.endDay = #allWeeks.endDay   \n"
		 + " select * into #pxtemp from #result where 1=2     \n"
		 + " if(@sortDate = '小计') begin      \n"
		 + " 	insert into #pxtemp select userID,'小计',SUM(total),userName,0,'小计' from #result group by userID,userName      \n"
		 + " end     \n"
		 + " else begin     \n"
		 + " 	insert into #pxtemp select * from #result where weeks = @sortDate    \n"
		 + " end  \n"
		 + " select identity(int,1,1) as row_no,*     \n"
		 + " into #px    \n"
		 + " from #pxtemp     \n"
		 + " order by total desc   \n"
		 + " update #result set #result.userPx = #px.row_no from #result,#px where #result.userID = #px.userID   \n"
		 + " select 99999 as userID,weeks as weeks,SUM(total) as total,'合计' as userName,99999 as userPx,cast(weeknum as varchar(100)) as weeknum into #totalTemp from #result group by weeks,weeknum  \n"
		 + " union all     \n"
		 + " select userID,'小计',SUM(total),userName,99999,'<div style=\"display:none;\">小计</div>' from #result group by userID,userName    \n"
		 + " union all    \n"
		 + " select 99999,'小计',SUM(total),'合计',99999,'<div style=\"display:none;\">小计</div>' from #result    \n"
		 + " insert into #result select * from #totalTemp    \n"
		 + " update #result set #result.userPx = #px.row_no from #result,#px where #result.userID = #px.userID and #result.weeks = '小计'   \n"
		 + " select * from #result  \n";
		return jt.queryForList(sql, new Object[]{sort,deptName});
	}
}
