//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ipm.rc
//
#define IDC_STGED_NEW                   3
#define IDOK2                           3
#define IDC_STGED_SAVE                  4
#define IDCANCEL2                       4
#define IDC_STGED_SAVE_AS               5
#define IDOK3                           5
#define IDC_STGED_SAVE_FILE             6
#define IDCANCEL3                       6
#define IDC_STGED_DEL                   7
#define IDOK4                           7
#define IDCANCEL4                       8
#define IDOK5                           9
#define IDCANCEL5                       10
#define IDOK6                           11
#define IDCANCEL6                       12
#define IDOK7                           13
#define IDCANCEL7                       14
#define IDOK8                           15
#define IDCANCEL8                       16
#define IDOK9                           17
#define IDCANCEL9                       18
#define IDOK10                          19
#define IDCANCEL10                      20
#define IDOK11                          21
#define IDCANCEL11                      22
#define IDR_IPM                         101
#define IDD_FORMFLASH                   101
#define IDI_IPM                         102
#define DLG_TOOLKIT                     110
#define DLG_PALETTE                     111
#define DLG_SYMBOL_SELECT               112
#define DLG_DYN_TEMPLATE                113
#define DLG_DYN_FORMAT                  114
#define DLG_GRID_SET                    115
#define DLG_LAYER_SET                   116
#define DLG_LAYER_HIDE_LOCK             117
#define DLG_GET_NAME                    118
#define DLG_TEXT_INPUT                  119
#define DLG_SYMBOL_GRP_EDIT             120
#define DLG_CGRP_EDITOR                 121
#define DLG_STRING_GRP_EDITOR           122
#define DLG_MENU_EDITOR                 123
#define DLG_SYMBOL_EDITOR               124
#define DLG_REPLACE                     125
#define BMP_LINEU                       201
#define BMP_ARCU                        202
#define BMP_CIRCLEU                     203
#define BMP_POLYLINEU                   204
#define BMP_RECTU                       205
#define BMP_SYMBOLU                     206
#define BMP_SELECTU                     207
#define BMP_GIFU                        208
#define BMP_TEXTU                       209
#define BMP_ZOOMU                       210
#define BMP_LINEU_DASH                  211
#define BMP_LINEWIDTH1                  224
#define BMP_LINEWIDTH2                  225
#define BMP_LINEWIDTH3                  226
#define BMP_LINEWIDTH4                  227
#define BMP_LINEWIDTH5                  228
#define BMP_LINEWIDTH6                  229
#define BMP_LINED                       231
#define BMP_ARCD                        232
#define BMP_CIRCLED                     233
#define BMP_POLYLINED                   234
#define BMP_RECTD                       235
#define BMP_SYMBOLD                     236
#define BMP_SELECTD                     237
#define BMP_GIFD                        238
#define BMP_TEXTD                       239
#define BMP_ZOOMD                       240
#define BMP_LINED_DASH                  241
#define BMP_TREEVIEW                    242
#define IDR_ACC                         244
#define POP_UP                          245
#define IDC_HAND                        246
#define IDR_TOOLBAR1                    247
#define IDC_MOVE                        249
#define IDC_PEN                         251
#define IDC_ARROWL                      252
#define IDC_ARROWS                      253
#define IDC_HAND_GRAB                   255
#define IDC_HAND_OPEN                   256
#define IDC_SW                          259
#define IDC_SE                          260
#define IDC_SPLITV                      261
#define IDC_SPLITH                      262
#define DLG_SYMBOL_IMPORT               264
#define DLG_ALIGN                       265
#define DLG_PROJECT                     269
#define IDC_PARA                        270
#define IDD_DIALOG2                     270
#define IDC_HOR                         271
#define DLG_ABOUT                       271
#define DLG_ATTRIBUTE                   272
#define DLG_BASE_ATTRIBUTE              272
#define DLG_BASE_ATTR                   272
#define DLG_DYN_ATTRIBUTE               273
#define DLG_DYN_POINT                   273
#define DLG_DYN_POINT_SELECT            273
#define DLG_ELSE_ATTRIBUTE              274
#define DLG_DYN_COLOR                   275
#define DLG_DYN_VIEW                    276
#define DLG_DYN_ATTR                    276
#define DLG_DYN_CONTROL                 277
#define IDB_BITMAP1                     279
#define IDD_FILE_SEARCH                 280
#define DLG_FIND_IN_FILE                281
#define IDB_FGBTN                       999
#define IDB_BGBTN                       1000
#define IDB_LINE                        1002
#define IDB_ARC                         1003
#define IDB_CIRCLE                      1004
#define IDB_POLYLINE                    1005
#define IDB_RECT                        1006
#define IDB_SYMBOL                      1007
#define IDB_SELECT                      1008
#define IDB_GIF                         1009
#define IDB_TEXT                        1010
#define IDB_ZOOM                        1011
#define IDB_LINE_DASH                   1012
#define IDC_FILLPTN                     1013
#define IDC_LINEWIDTH                   1016
#define IDC_FONT                        1017
#define IDC_SYMBOL_CLASS_LIST           1100
#define IDA_SYM_SELECTOR                1101
#define IDC_SYMBOL_CANVAS               1101
#define IDC_FORMAT_LIST                 1102
#define IDC_NO_REQ                      1103
#define IDC_DSP_REQ                     1104
#define IDC_GRID_WIDTH_SBAR             1104
#define IDC_PROG_REQ                    1105
#define IDC_GRID_WIDTH_EDIT             1105
#define IDC_MENU_REQ                    1106
#define IDC_GRID_HEIGHT_SBAR            1108
#define IDC_GRID_HEIGHT_EDIT            1109
#define IDC_ZOOM_MIN                    1110
#define IDC_ZOOM_MAX                    1111
#define IDC_ZOOM_SIZE                   1112
#define IDC_LAYER_SELECT                1113
#define IDC_HIDE_ALL                    1118
#define IDC_SHOW_ALL                    1119
#define IDC_LOCK_ALL                    1120
#define IDC_UNLOCK_ALL                  1121
#define IDC_NAME_LABLE                  1122
#define IDC_SAVEAS_NAME                 1123
#define IDC_TEXT                        1124
#define IDC_SYM_GRP_LIST                1125
#define IDC_NEW_SYM_GRP                 1126
#define IDC_SAVE_SYM_GRP                1127
#define IDC_SAVEAS_SYM_GRP              1128
#define IDC_FSAVE_SYM_GRP               1129
#define IDC_SYM_GRP_FRAME               1130
#define IDC_DEL_SYM_GRP                 1131
#define IDC_CGED_LIST                   1131
#define IDC_CGED_NEW                    1132
#define IDC_CGED_SAVE                   1133
#define IDC_CGED_SAVEAS                 1134
#define IDC_CGED_DEL                    1135
#define IDC_CGED_SFILE                  1136
#define IDC_CGED_CANVAS                 1138
#define IDC_CGED_SOLID                  1139
#define IDC_CGED_FLASH                  1140
#define IDC_STGED_GRP_LIST              1141
#define IDC_STGED_TXT0                  1142
#define IDC_STGED_TXT1                  1143
#define IDC_STGED_TXT2                  1144
#define IDC_STGED_TXT3                  1145
#define IDC_STGED_TXT4                  1146
#define IDC_STGED_TXT5                  1147
#define IDC_STGED_TXT6                  1148
#define IDC_STGED_TXT7                  1149
#define IDC_STGED_TXT8                  1150
#define IDC_STGED_TXT9                  1151
#define IDC_STGED_TXT10                 1152
#define IDC_STGED_TXT11                 1153
#define IDC_STGED_TXT12                 1154
#define IDC_STGED_TXT13                 1155
#define IDC_STGED_TXT14                 1156
#define IDC_STGED_TXT15                 1157
#define IDC_MED_LIST                    1159
#define IDC_MED_NEW                     1160
#define IDC_MED_EDIT                    1161
#define IDC_MED_DEL                     1162
#define IDC_SED_NEW                     1162
#define IDC_MED_SAVE_FILE               1163
#define IDC_SED_EDIT                    1163
#define IDC_REF_TYPE                    1163
#define IDC_SED_DELETE                  1164
#define IDC_REPLACE_SEARCH              1164
#define IDC_SED_ADD_CLASS               1165
#define IDC_REPLACE_TEXT                1165
#define IDC_SED_DEL_CLASS               1166
#define ID_DOK                          1166
#define IDC_SED_SAVE                    1167
#define IDC_SED_IMPORT                  1168
#define IDC_RADIO1                      1168
#define IDC_RADIO2                      1169
#define IDC_RADIO3                      1170
#define IDC_RADIO6                      1171
#define IDC_RADIO7                      1172
#define IDC_RADIO8                      1173
#define IDC_PAREL                       1173
#define IDC_RADIO4                      1174
#define IDC_VERTI                       1174
#define IDC_RADIO5                      1175
#define IDC_RADIO9                      1176
#define IDC_RADIO10                     1177
#define IDC_COMBO1                      1177
#define IDC_CMB_PRJ                     1177
#define IDC_DYN_COLOR_LIST              1177
#define IDC_FIND_TYPE                   1177
#define IDC_RADIO11                     1178
#define IDC_CHECK1                      1178
#define IDC_CHK_PRJ                     1178
#define IDC_FILLTYPE                    1178
#define IDC_FILEREVERSED                1178
#define IDC_RADIO12                     1179
#define ID_DCANCEL                      1179
#define IDC_DYN_VIEW_LIST               1179
#define IDC_RADIO13                     1180
#define IDC_DYN_CTRL_TYPE_LIST          1180
#define IDC_RADIO14                     1181
#define IDC_DYN_CTRL_PROG_LIST          1181
#define IDC_RADIO15                     1182
#define IDC_DYN_CTRL_MENU_LIST          1182
#define IDC_RADIO16                     1183
#define IDC_RADIO17                     1184
#define IDC_RADIO18                     1185
#define IDC_RADIO19                     1186
#define IDC_RADIO20                     1187
#define IDC_RADIO21                     1188
#define IDC_RADIO22                     1189
#define IDC_SEL_PT_NAME                 1189
#define IDC_RADIO23                     1190
#define IDC_DATABASE_TREE               1190
#define IDC_RADIO24                     1191
#define IDC_RADIO25                     1192
#define IDC_DYN_COLOR_GID               1192
#define IDC_RADIO26                     1193
#define IDC_DYN_LINK_POINT_NAME         1193
#define IDC_RADIO27                     1194
#define IDC_LINK_POINT_SEL_BUTTON       1194
#define IDC_RADIO28                     1195
#define IDC_CANCEL                      1195
#define IDC_DSP_FILE_SEL_BUTTON         1195
#define IDC_RADIO29                     1196
#define IDC_OK                          1196
#define IDC_DYN_CTRL_DSP_FILENAME       1196
#define IDC_RADIO30                     1197
#define IDC_DYN_CTRL_MENU_TEXT          1197
#define IDC_RADIO31                     1198
#define IDC_EDIT1                       1198
#define IDC_RADIO32                     1199
#define IDC_RADIO33                     1200
#define IDC_EDIT3                       1200
#define IDC_RADIO34                     1201
#define IDC_RADIO35                     1202
#define IDC_FIND                        1202
#define IDC_RADIO36                     1203
#define IDC_RADIO37                     1204
#define IDC_RADIO38                     1205
#define IDC_RADIO39                     1206
#define IDC_RADIO40                     1207
#define IDC_RADIO41                     1208
#define IDC_RADIO42                     1209
#define IDC_RADIO43                     1210
#define IDC_RADIO44                     1211
#define IDC_DB_SELECT_BUTTON            1212
#define IDC_DSPFILE_SELECT_BUTTON       1213
#define ID_Open_File                    40001
#define ID__SAVE                        40002
#define ID_SAVE                         40002
#define ID_SaveAs                       40003
#define ID__ABORT                       40004
#define ID_ABORT                        40004
#define ID_Print                        40005
#define ID_EXIT                         40006
#define ID_Symbol                       40008
#define ID_Sym_Grps                     40009
#define ID_Color_Grps                   40010
#define ID_Str_Grps                     40011
#define ID_Ctrl_Menus                   40012
#define ID_Sub_Display                  40013
#define ID_Copy                         40021
#define ID_Move                         40022
#define ID_Cut                          40023
#define ID_Paste                        40024
#define ID_Replace                      40025
#define ID_Delete                       40026
#define ID_Resize                       40027
#define ID_Reshape                      40028
#define ID_Send_Fgd                     40029
#define ID_Send_Fg                      40029
#define ID_Send_Bgd                     40030
#define ID_Send_Bg                      40030
#define ID_in_line                      40031
#define ID_ALIGN                        40031
#define ID_Canvas_Bgd_Color             40032
#define ID_Clear_Scrn                   40033
#define ID_Grid_Visible                 40041
#define ID_Grid_Valid                   40042
#define ID_Fgd_Grid                     40043
#define ID_Bgd_Grid                     40044
#define ID_Grid_Set                     40045
#define ID_Layer_Clutter                40050
#define ID_View                         40051
#define ID_Layer_LockHide               40052
#define ID_Layer_Set                    40053
#define ID_Layer_01                     40061
#define ID_Layer_02                     40062
#define ID_Layer_03                     40063
#define ID_Layer_04                     40064
#define ID_Layer_05                     40065
#define ID_Layer_06                     40066
#define ID_Layer_07                     40067
#define ID_Layer_08                     40068
#define ID_Layer_09                     40069
#define ID_Layer_10                     40070
#define ID_Layer_11                     40071
#define ID_Layer_12                     40072
#define ID_Layer_13                     40073
#define ID_Layer_14                     40074
#define ID_Layer_15                     40075
#define ID_Add_Dynamic                  40084
#define ID_Del_Dynamics                 40085
#define ID_Add_Display                  40086
#define ID_Add_Prog                     40087
#define ID_Add_CtrlMenu                 40088
#define ID_Del_Req                      40089
#define ID_Add_Dyn_Color                40090
#define ID_Del_Dyn_Color                40091
#define ID_Datab_Test                   40101
#define ID_REDISPLAY                    40110
#define ID_EDIT_RESIZE                  40113
#define ID_MENUITEM40114                40114
#define ID_FILE_SAVE1                   40115
#define ID_BUTTON40126                  40126
#define ID_BUTTON40127                  40127
#define ID_BUTTON40128                  40128
#define ID_BUTTON40129                  40129
#define IDM_ABOUT                       40130
#define ID_ALL_SELECT                   40131
#define ID_NEWFILE                      40132
#define ID_AUTO_SIZE                    40133
#define IDM_PRINTSETUP                  40134
#define ID_FILE_SEARCH                  40135
#define ID_FIND_IN_FILE                 40136
#define ID_Undo                         40137
#define ID_NORMAL_PAGE                  40140
#define ID_SIMU_PAGE                    40141
#define ID_DISPLAY_DBNAME               40142
#define ID_ATTRIBUTE                    40200
#define ID_SELECTED_shrink              40201
#define ID_SELECTED_extend              40202
#define IDM_EDIT_COPY                   0xE122
#define IDM_EDIT_CUT                    0xE123
#define IDM_EDIT_RESIZE                 0xE124
#define IDM_EDIT_PASTE                  0xE125

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        285
#define _APS_NEXT_COMMAND_VALUE         40143
#define _APS_NEXT_CONTROL_VALUE         1203
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
