/* ReportService.h
   Generated by wzg
*/

#ifndef ReportService_H
#define ReportService_H

#include "soapH.h"
#include "soapServiceSoapProxy.h"
#include "mainwindow.h"



class ReportService
{
	
private:
	ServiceSoap *soap;
	
	
public:
	MainWindow *window;

	ReportService();

    bool GetReportTree(QBuffer *content);
	bool GetTemplateInformation(QBuffer *content);
	bool GetTemplate(int reportId, QBuffer *content);
	bool GetTemplateConfig(int reportId, QBuffer *content);
	bool queryReport(int reportId, bool useSavedReport, QString startTime, QString endTime, QString inputCells, QBuffer *content);
	
	
};
#endif
