/* soapH.h
   Generated by gSOAP 2.7.6c from hreport.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);
#ifndef WITH_NOIDREF
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, int*);
#endif

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE__ns1__GetTemplateInformationResponse
#define SOAP_TYPE__ns1__GetTemplateInformationResponse (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetTemplateInformationResponse(struct soap*, const char*, int, const _ns1__GetTemplateInformationResponse *, const char*);
SOAP_FMAC3 _ns1__GetTemplateInformationResponse * SOAP_FMAC4 soap_get__ns1__GetTemplateInformationResponse(struct soap*, _ns1__GetTemplateInformationResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__GetTemplateInformationResponse * SOAP_FMAC4 soap_in__ns1__GetTemplateInformationResponse(struct soap*, const char*, _ns1__GetTemplateInformationResponse *, const char*);
SOAP_FMAC5 _ns1__GetTemplateInformationResponse * SOAP_FMAC6 soap_new__ns1__GetTemplateInformationResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetTemplateInformationResponse(struct soap*, _ns1__GetTemplateInformationResponse*);
SOAP_FMAC5 _ns1__GetTemplateInformationResponse * SOAP_FMAC6 soap_instantiate__ns1__GetTemplateInformationResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy__ns1__GetTemplateInformationResponse(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetTemplateInformation
#define SOAP_TYPE__ns1__GetTemplateInformation (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetTemplateInformation(struct soap*, const char*, int, const _ns1__GetTemplateInformation *, const char*);
SOAP_FMAC3 _ns1__GetTemplateInformation * SOAP_FMAC4 soap_get__ns1__GetTemplateInformation(struct soap*, _ns1__GetTemplateInformation *, const char*, const char*);
SOAP_FMAC3 _ns1__GetTemplateInformation * SOAP_FMAC4 soap_in__ns1__GetTemplateInformation(struct soap*, const char*, _ns1__GetTemplateInformation *, const char*);
SOAP_FMAC5 _ns1__GetTemplateInformation * SOAP_FMAC6 soap_new__ns1__GetTemplateInformation(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetTemplateInformation(struct soap*, _ns1__GetTemplateInformation*);
SOAP_FMAC5 _ns1__GetTemplateInformation * SOAP_FMAC6 soap_instantiate__ns1__GetTemplateInformation(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy__ns1__GetTemplateInformation(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetTemplateTreeResponse
#define SOAP_TYPE__ns1__GetTemplateTreeResponse (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetTemplateTreeResponse(struct soap*, const char*, int, const _ns1__GetTemplateTreeResponse *, const char*);
SOAP_FMAC3 _ns1__GetTemplateTreeResponse * SOAP_FMAC4 soap_get__ns1__GetTemplateTreeResponse(struct soap*, _ns1__GetTemplateTreeResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__GetTemplateTreeResponse * SOAP_FMAC4 soap_in__ns1__GetTemplateTreeResponse(struct soap*, const char*, _ns1__GetTemplateTreeResponse *, const char*);
SOAP_FMAC5 _ns1__GetTemplateTreeResponse * SOAP_FMAC6 soap_new__ns1__GetTemplateTreeResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetTemplateTreeResponse(struct soap*, _ns1__GetTemplateTreeResponse*);
SOAP_FMAC5 _ns1__GetTemplateTreeResponse * SOAP_FMAC6 soap_instantiate__ns1__GetTemplateTreeResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy__ns1__GetTemplateTreeResponse(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetTemplateTree
#define SOAP_TYPE__ns1__GetTemplateTree (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetTemplateTree(struct soap*, const char*, int, const _ns1__GetTemplateTree *, const char*);
SOAP_FMAC3 _ns1__GetTemplateTree * SOAP_FMAC4 soap_get__ns1__GetTemplateTree(struct soap*, _ns1__GetTemplateTree *, const char*, const char*);
SOAP_FMAC3 _ns1__GetTemplateTree * SOAP_FMAC4 soap_in__ns1__GetTemplateTree(struct soap*, const char*, _ns1__GetTemplateTree *, const char*);
SOAP_FMAC5 _ns1__GetTemplateTree * SOAP_FMAC6 soap_new__ns1__GetTemplateTree(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetTemplateTree(struct soap*, _ns1__GetTemplateTree*);
SOAP_FMAC5 _ns1__GetTemplateTree * SOAP_FMAC6 soap_instantiate__ns1__GetTemplateTree(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy__ns1__GetTemplateTree(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE__ns1__QueryResponse
#define SOAP_TYPE__ns1__QueryResponse (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__QueryResponse(struct soap*, const char*, int, const _ns1__QueryResponse *, const char*);
SOAP_FMAC3 _ns1__QueryResponse * SOAP_FMAC4 soap_get__ns1__QueryResponse(struct soap*, _ns1__QueryResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__QueryResponse * SOAP_FMAC4 soap_in__ns1__QueryResponse(struct soap*, const char*, _ns1__QueryResponse *, const char*);
SOAP_FMAC5 _ns1__QueryResponse * SOAP_FMAC6 soap_new__ns1__QueryResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__QueryResponse(struct soap*, _ns1__QueryResponse*);
SOAP_FMAC5 _ns1__QueryResponse * SOAP_FMAC6 soap_instantiate__ns1__QueryResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy__ns1__QueryResponse(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE__ns1__Query
#define SOAP_TYPE__ns1__Query (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__Query(struct soap*, const char*, int, const _ns1__Query *, const char*);
SOAP_FMAC3 _ns1__Query * SOAP_FMAC4 soap_get__ns1__Query(struct soap*, _ns1__Query *, const char*, const char*);
SOAP_FMAC3 _ns1__Query * SOAP_FMAC4 soap_in__ns1__Query(struct soap*, const char*, _ns1__Query *, const char*);
SOAP_FMAC5 _ns1__Query * SOAP_FMAC6 soap_new__ns1__Query(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__Query(struct soap*, _ns1__Query*);
SOAP_FMAC5 _ns1__Query * SOAP_FMAC6 soap_instantiate__ns1__Query(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy__ns1__Query(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetTemplateConfigResponse
#define SOAP_TYPE__ns1__GetTemplateConfigResponse (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetTemplateConfigResponse(struct soap*, const char*, int, const _ns1__GetTemplateConfigResponse *, const char*);
SOAP_FMAC3 _ns1__GetTemplateConfigResponse * SOAP_FMAC4 soap_get__ns1__GetTemplateConfigResponse(struct soap*, _ns1__GetTemplateConfigResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__GetTemplateConfigResponse * SOAP_FMAC4 soap_in__ns1__GetTemplateConfigResponse(struct soap*, const char*, _ns1__GetTemplateConfigResponse *, const char*);
SOAP_FMAC5 _ns1__GetTemplateConfigResponse * SOAP_FMAC6 soap_new__ns1__GetTemplateConfigResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetTemplateConfigResponse(struct soap*, _ns1__GetTemplateConfigResponse*);
SOAP_FMAC5 _ns1__GetTemplateConfigResponse * SOAP_FMAC6 soap_instantiate__ns1__GetTemplateConfigResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy__ns1__GetTemplateConfigResponse(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetTemplateConfig
#define SOAP_TYPE__ns1__GetTemplateConfig (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetTemplateConfig(struct soap*, const char*, int, const _ns1__GetTemplateConfig *, const char*);
SOAP_FMAC3 _ns1__GetTemplateConfig * SOAP_FMAC4 soap_get__ns1__GetTemplateConfig(struct soap*, _ns1__GetTemplateConfig *, const char*, const char*);
SOAP_FMAC3 _ns1__GetTemplateConfig * SOAP_FMAC4 soap_in__ns1__GetTemplateConfig(struct soap*, const char*, _ns1__GetTemplateConfig *, const char*);
SOAP_FMAC5 _ns1__GetTemplateConfig * SOAP_FMAC6 soap_new__ns1__GetTemplateConfig(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetTemplateConfig(struct soap*, _ns1__GetTemplateConfig*);
SOAP_FMAC5 _ns1__GetTemplateConfig * SOAP_FMAC6 soap_instantiate__ns1__GetTemplateConfig(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy__ns1__GetTemplateConfig(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetTemplateResponse
#define SOAP_TYPE__ns1__GetTemplateResponse (7)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetTemplateResponse(struct soap*, const char*, int, const _ns1__GetTemplateResponse *, const char*);
SOAP_FMAC3 _ns1__GetTemplateResponse * SOAP_FMAC4 soap_get__ns1__GetTemplateResponse(struct soap*, _ns1__GetTemplateResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__GetTemplateResponse * SOAP_FMAC4 soap_in__ns1__GetTemplateResponse(struct soap*, const char*, _ns1__GetTemplateResponse *, const char*);
SOAP_FMAC5 _ns1__GetTemplateResponse * SOAP_FMAC6 soap_new__ns1__GetTemplateResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetTemplateResponse(struct soap*, _ns1__GetTemplateResponse*);
SOAP_FMAC5 _ns1__GetTemplateResponse * SOAP_FMAC6 soap_instantiate__ns1__GetTemplateResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy__ns1__GetTemplateResponse(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetTemplate
#define SOAP_TYPE__ns1__GetTemplate (6)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetTemplate(struct soap*, const char*, int, const _ns1__GetTemplate *, const char*);
SOAP_FMAC3 _ns1__GetTemplate * SOAP_FMAC4 soap_get__ns1__GetTemplate(struct soap*, _ns1__GetTemplate *, const char*, const char*);
SOAP_FMAC3 _ns1__GetTemplate * SOAP_FMAC4 soap_in__ns1__GetTemplate(struct soap*, const char*, _ns1__GetTemplate *, const char*);
SOAP_FMAC5 _ns1__GetTemplate * SOAP_FMAC6 soap_new__ns1__GetTemplate(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__GetTemplate(struct soap*, _ns1__GetTemplate*);
SOAP_FMAC5 _ns1__GetTemplate * SOAP_FMAC6 soap_instantiate__ns1__GetTemplate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy__ns1__GetTemplate(struct soap*, int, int, void*, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE___ns1__GetTemplateInformation_
#define SOAP_TYPE___ns1__GetTemplateInformation_ (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetTemplateInformation_(struct soap*, const struct __ns1__GetTemplateInformation_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetTemplateInformation_(struct soap*, struct __ns1__GetTemplateInformation_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetTemplateInformation_(struct soap*, const struct __ns1__GetTemplateInformation_ *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetTemplateInformation_(struct soap*, const char*, int, const struct __ns1__GetTemplateInformation_ *, const char*);
SOAP_FMAC3 struct __ns1__GetTemplateInformation_ * SOAP_FMAC4 soap_get___ns1__GetTemplateInformation_(struct soap*, struct __ns1__GetTemplateInformation_ *, const char*, const char*);
SOAP_FMAC3 struct __ns1__GetTemplateInformation_ * SOAP_FMAC4 soap_in___ns1__GetTemplateInformation_(struct soap*, const char*, struct __ns1__GetTemplateInformation_ *, const char*);

#ifndef SOAP_TYPE___ns1__GetTemplateTree_
#define SOAP_TYPE___ns1__GetTemplateTree_ (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetTemplateTree_(struct soap*, const struct __ns1__GetTemplateTree_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetTemplateTree_(struct soap*, struct __ns1__GetTemplateTree_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetTemplateTree_(struct soap*, const struct __ns1__GetTemplateTree_ *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetTemplateTree_(struct soap*, const char*, int, const struct __ns1__GetTemplateTree_ *, const char*);
SOAP_FMAC3 struct __ns1__GetTemplateTree_ * SOAP_FMAC4 soap_get___ns1__GetTemplateTree_(struct soap*, struct __ns1__GetTemplateTree_ *, const char*, const char*);
SOAP_FMAC3 struct __ns1__GetTemplateTree_ * SOAP_FMAC4 soap_in___ns1__GetTemplateTree_(struct soap*, const char*, struct __ns1__GetTemplateTree_ *, const char*);

#ifndef SOAP_TYPE___ns1__Query_
#define SOAP_TYPE___ns1__Query_ (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__Query_(struct soap*, const struct __ns1__Query_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__Query_(struct soap*, struct __ns1__Query_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__Query_(struct soap*, const struct __ns1__Query_ *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__Query_(struct soap*, const char*, int, const struct __ns1__Query_ *, const char*);
SOAP_FMAC3 struct __ns1__Query_ * SOAP_FMAC4 soap_get___ns1__Query_(struct soap*, struct __ns1__Query_ *, const char*, const char*);
SOAP_FMAC3 struct __ns1__Query_ * SOAP_FMAC4 soap_in___ns1__Query_(struct soap*, const char*, struct __ns1__Query_ *, const char*);

#ifndef SOAP_TYPE___ns1__GetTemplateConfig_
#define SOAP_TYPE___ns1__GetTemplateConfig_ (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetTemplateConfig_(struct soap*, const struct __ns1__GetTemplateConfig_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetTemplateConfig_(struct soap*, struct __ns1__GetTemplateConfig_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetTemplateConfig_(struct soap*, const struct __ns1__GetTemplateConfig_ *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetTemplateConfig_(struct soap*, const char*, int, const struct __ns1__GetTemplateConfig_ *, const char*);
SOAP_FMAC3 struct __ns1__GetTemplateConfig_ * SOAP_FMAC4 soap_get___ns1__GetTemplateConfig_(struct soap*, struct __ns1__GetTemplateConfig_ *, const char*, const char*);
SOAP_FMAC3 struct __ns1__GetTemplateConfig_ * SOAP_FMAC4 soap_in___ns1__GetTemplateConfig_(struct soap*, const char*, struct __ns1__GetTemplateConfig_ *, const char*);

#ifndef SOAP_TYPE___ns1__GetTemplate_
#define SOAP_TYPE___ns1__GetTemplate_ (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetTemplate_(struct soap*, const struct __ns1__GetTemplate_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetTemplate_(struct soap*, struct __ns1__GetTemplate_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetTemplate_(struct soap*, const struct __ns1__GetTemplate_ *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetTemplate_(struct soap*, const char*, int, const struct __ns1__GetTemplate_ *, const char*);
SOAP_FMAC3 struct __ns1__GetTemplate_ * SOAP_FMAC4 soap_get___ns1__GetTemplate_(struct soap*, struct __ns1__GetTemplate_ *, const char*, const char*);
SOAP_FMAC3 struct __ns1__GetTemplate_ * SOAP_FMAC4 soap_in___ns1__GetTemplate_(struct soap*, const char*, struct __ns1__GetTemplate_ *, const char*);

#ifndef SOAP_TYPE___ns1__GetTemplateInformation
#define SOAP_TYPE___ns1__GetTemplateInformation (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetTemplateInformation(struct soap*, const struct __ns1__GetTemplateInformation *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetTemplateInformation(struct soap*, struct __ns1__GetTemplateInformation *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetTemplateInformation(struct soap*, const struct __ns1__GetTemplateInformation *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetTemplateInformation(struct soap*, const char*, int, const struct __ns1__GetTemplateInformation *, const char*);
SOAP_FMAC3 struct __ns1__GetTemplateInformation * SOAP_FMAC4 soap_get___ns1__GetTemplateInformation(struct soap*, struct __ns1__GetTemplateInformation *, const char*, const char*);
SOAP_FMAC3 struct __ns1__GetTemplateInformation * SOAP_FMAC4 soap_in___ns1__GetTemplateInformation(struct soap*, const char*, struct __ns1__GetTemplateInformation *, const char*);

#ifndef SOAP_TYPE___ns1__GetTemplateTree
#define SOAP_TYPE___ns1__GetTemplateTree (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetTemplateTree(struct soap*, const struct __ns1__GetTemplateTree *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetTemplateTree(struct soap*, struct __ns1__GetTemplateTree *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetTemplateTree(struct soap*, const struct __ns1__GetTemplateTree *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetTemplateTree(struct soap*, const char*, int, const struct __ns1__GetTemplateTree *, const char*);
SOAP_FMAC3 struct __ns1__GetTemplateTree * SOAP_FMAC4 soap_get___ns1__GetTemplateTree(struct soap*, struct __ns1__GetTemplateTree *, const char*, const char*);
SOAP_FMAC3 struct __ns1__GetTemplateTree * SOAP_FMAC4 soap_in___ns1__GetTemplateTree(struct soap*, const char*, struct __ns1__GetTemplateTree *, const char*);

#ifndef SOAP_TYPE___ns1__Query
#define SOAP_TYPE___ns1__Query (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__Query(struct soap*, const struct __ns1__Query *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__Query(struct soap*, struct __ns1__Query *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__Query(struct soap*, const struct __ns1__Query *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__Query(struct soap*, const char*, int, const struct __ns1__Query *, const char*);
SOAP_FMAC3 struct __ns1__Query * SOAP_FMAC4 soap_get___ns1__Query(struct soap*, struct __ns1__Query *, const char*, const char*);
SOAP_FMAC3 struct __ns1__Query * SOAP_FMAC4 soap_in___ns1__Query(struct soap*, const char*, struct __ns1__Query *, const char*);

#ifndef SOAP_TYPE___ns1__GetTemplateConfig
#define SOAP_TYPE___ns1__GetTemplateConfig (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetTemplateConfig(struct soap*, const struct __ns1__GetTemplateConfig *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetTemplateConfig(struct soap*, struct __ns1__GetTemplateConfig *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetTemplateConfig(struct soap*, const struct __ns1__GetTemplateConfig *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetTemplateConfig(struct soap*, const char*, int, const struct __ns1__GetTemplateConfig *, const char*);
SOAP_FMAC3 struct __ns1__GetTemplateConfig * SOAP_FMAC4 soap_get___ns1__GetTemplateConfig(struct soap*, struct __ns1__GetTemplateConfig *, const char*, const char*);
SOAP_FMAC3 struct __ns1__GetTemplateConfig * SOAP_FMAC4 soap_in___ns1__GetTemplateConfig(struct soap*, const char*, struct __ns1__GetTemplateConfig *, const char*);

#ifndef SOAP_TYPE___ns1__GetTemplate
#define SOAP_TYPE___ns1__GetTemplate (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetTemplate(struct soap*, const struct __ns1__GetTemplate *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetTemplate(struct soap*, struct __ns1__GetTemplate *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetTemplate(struct soap*, const struct __ns1__GetTemplate *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetTemplate(struct soap*, const char*, int, const struct __ns1__GetTemplate *, const char*);
SOAP_FMAC3 struct __ns1__GetTemplate * SOAP_FMAC4 soap_get___ns1__GetTemplate(struct soap*, struct __ns1__GetTemplate *, const char*, const char*);
SOAP_FMAC3 struct __ns1__GetTemplate * SOAP_FMAC4 soap_in___ns1__GetTemplate(struct soap*, const char*, struct __ns1__GetTemplate *, const char*);

#ifndef SOAP_TYPE_struct_5
#define SOAP_TYPE_struct_5 (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_struct_5(struct soap*, const struct struct_5 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_struct_5(struct soap*, struct struct_5 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_struct_5(struct soap*, const struct struct_5 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_struct_5(struct soap*, const char*, int, const struct struct_5 *, const char*);
SOAP_FMAC3 struct struct_5 * SOAP_FMAC4 soap_get_struct_5(struct soap*, struct struct_5 *, const char*, const char*);
SOAP_FMAC3 struct struct_5 * SOAP_FMAC4 soap_in_struct_5(struct soap*, const char*, struct struct_5 *, const char*);

#ifndef SOAP_TYPE_struct_4
#define SOAP_TYPE_struct_4 (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_struct_4(struct soap*, const struct struct_4 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_struct_4(struct soap*, struct struct_4 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_struct_4(struct soap*, const struct struct_4 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_struct_4(struct soap*, const char*, int, const struct struct_4 *, const char*);
SOAP_FMAC3 struct struct_4 * SOAP_FMAC4 soap_get_struct_4(struct soap*, struct struct_4 *, const char*, const char*);
SOAP_FMAC3 struct struct_4 * SOAP_FMAC4 soap_in_struct_4(struct soap*, const char*, struct struct_4 *, const char*);

#ifndef SOAP_TYPE_struct_3
#define SOAP_TYPE_struct_3 (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_struct_3(struct soap*, const struct struct_3 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_struct_3(struct soap*, struct struct_3 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_struct_3(struct soap*, const struct struct_3 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_struct_3(struct soap*, const char*, int, const struct struct_3 *, const char*);
SOAP_FMAC3 struct struct_3 * SOAP_FMAC4 soap_get_struct_3(struct soap*, struct struct_3 *, const char*, const char*);
SOAP_FMAC3 struct struct_3 * SOAP_FMAC4 soap_in_struct_3(struct soap*, const char*, struct struct_3 *, const char*);

#ifndef SOAP_TYPE_struct_2
#define SOAP_TYPE_struct_2 (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_struct_2(struct soap*, const struct struct_2 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_struct_2(struct soap*, struct struct_2 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_struct_2(struct soap*, const struct struct_2 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_struct_2(struct soap*, const char*, int, const struct struct_2 *, const char*);
SOAP_FMAC3 struct struct_2 * SOAP_FMAC4 soap_get_struct_2(struct soap*, struct struct_2 *, const char*, const char*);
SOAP_FMAC3 struct struct_2 * SOAP_FMAC4 soap_in_struct_2(struct soap*, const char*, struct struct_2 *, const char*);

#ifndef SOAP_TYPE_struct_1
#define SOAP_TYPE_struct_1 (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_struct_1(struct soap*, const struct struct_1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_struct_1(struct soap*, struct struct_1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_struct_1(struct soap*, const struct struct_1 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_struct_1(struct soap*, const char*, int, const struct struct_1 *, const char*);
SOAP_FMAC3 struct struct_1 * SOAP_FMAC4 soap_get_struct_1(struct soap*, struct struct_1 *, const char*, const char*);
SOAP_FMAC3 struct struct_1 * SOAP_FMAC4 soap_in_struct_1(struct soap*, const char*, struct struct_1 *, const char*);

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns1__GetTemplateInformationResponse
#define SOAP_TYPE_PointerTo_ns1__GetTemplateInformationResponse (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetTemplateInformationResponse(struct soap*, _ns1__GetTemplateInformationResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetTemplateInformationResponse(struct soap*, _ns1__GetTemplateInformationResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetTemplateInformationResponse(struct soap*, const char *, int, _ns1__GetTemplateInformationResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetTemplateInformationResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetTemplateInformationResponse(struct soap*, _ns1__GetTemplateInformationResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__GetTemplateInformationResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetTemplateInformationResponse(struct soap*, const char*, _ns1__GetTemplateInformationResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetTemplateInformation
#define SOAP_TYPE_PointerTo_ns1__GetTemplateInformation (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetTemplateInformation(struct soap*, _ns1__GetTemplateInformation *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetTemplateInformation(struct soap*, _ns1__GetTemplateInformation *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetTemplateInformation(struct soap*, const char *, int, _ns1__GetTemplateInformation *const*, const char *);
SOAP_FMAC3 _ns1__GetTemplateInformation ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetTemplateInformation(struct soap*, _ns1__GetTemplateInformation **, const char*, const char*);
SOAP_FMAC3 _ns1__GetTemplateInformation ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetTemplateInformation(struct soap*, const char*, _ns1__GetTemplateInformation **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetTemplateTreeResponse
#define SOAP_TYPE_PointerTo_ns1__GetTemplateTreeResponse (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetTemplateTreeResponse(struct soap*, _ns1__GetTemplateTreeResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetTemplateTreeResponse(struct soap*, _ns1__GetTemplateTreeResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetTemplateTreeResponse(struct soap*, const char *, int, _ns1__GetTemplateTreeResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetTemplateTreeResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetTemplateTreeResponse(struct soap*, _ns1__GetTemplateTreeResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__GetTemplateTreeResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetTemplateTreeResponse(struct soap*, const char*, _ns1__GetTemplateTreeResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetTemplateTree
#define SOAP_TYPE_PointerTo_ns1__GetTemplateTree (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetTemplateTree(struct soap*, _ns1__GetTemplateTree *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetTemplateTree(struct soap*, _ns1__GetTemplateTree *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetTemplateTree(struct soap*, const char *, int, _ns1__GetTemplateTree *const*, const char *);
SOAP_FMAC3 _ns1__GetTemplateTree ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetTemplateTree(struct soap*, _ns1__GetTemplateTree **, const char*, const char*);
SOAP_FMAC3 _ns1__GetTemplateTree ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetTemplateTree(struct soap*, const char*, _ns1__GetTemplateTree **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__QueryResponse
#define SOAP_TYPE_PointerTo_ns1__QueryResponse (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__QueryResponse(struct soap*, _ns1__QueryResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__QueryResponse(struct soap*, _ns1__QueryResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__QueryResponse(struct soap*, const char *, int, _ns1__QueryResponse *const*, const char *);
SOAP_FMAC3 _ns1__QueryResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__QueryResponse(struct soap*, _ns1__QueryResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__QueryResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__QueryResponse(struct soap*, const char*, _ns1__QueryResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__Query
#define SOAP_TYPE_PointerTo_ns1__Query (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__Query(struct soap*, _ns1__Query *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__Query(struct soap*, _ns1__Query *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__Query(struct soap*, const char *, int, _ns1__Query *const*, const char *);
SOAP_FMAC3 _ns1__Query ** SOAP_FMAC4 soap_get_PointerTo_ns1__Query(struct soap*, _ns1__Query **, const char*, const char*);
SOAP_FMAC3 _ns1__Query ** SOAP_FMAC4 soap_in_PointerTo_ns1__Query(struct soap*, const char*, _ns1__Query **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetTemplateConfigResponse
#define SOAP_TYPE_PointerTo_ns1__GetTemplateConfigResponse (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetTemplateConfigResponse(struct soap*, _ns1__GetTemplateConfigResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetTemplateConfigResponse(struct soap*, _ns1__GetTemplateConfigResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetTemplateConfigResponse(struct soap*, const char *, int, _ns1__GetTemplateConfigResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetTemplateConfigResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetTemplateConfigResponse(struct soap*, _ns1__GetTemplateConfigResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__GetTemplateConfigResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetTemplateConfigResponse(struct soap*, const char*, _ns1__GetTemplateConfigResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetTemplateConfig
#define SOAP_TYPE_PointerTo_ns1__GetTemplateConfig (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetTemplateConfig(struct soap*, _ns1__GetTemplateConfig *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetTemplateConfig(struct soap*, _ns1__GetTemplateConfig *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetTemplateConfig(struct soap*, const char *, int, _ns1__GetTemplateConfig *const*, const char *);
SOAP_FMAC3 _ns1__GetTemplateConfig ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetTemplateConfig(struct soap*, _ns1__GetTemplateConfig **, const char*, const char*);
SOAP_FMAC3 _ns1__GetTemplateConfig ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetTemplateConfig(struct soap*, const char*, _ns1__GetTemplateConfig **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetTemplateResponse
#define SOAP_TYPE_PointerTo_ns1__GetTemplateResponse (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetTemplateResponse(struct soap*, _ns1__GetTemplateResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetTemplateResponse(struct soap*, _ns1__GetTemplateResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetTemplateResponse(struct soap*, const char *, int, _ns1__GetTemplateResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetTemplateResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetTemplateResponse(struct soap*, _ns1__GetTemplateResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__GetTemplateResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetTemplateResponse(struct soap*, const char*, _ns1__GetTemplateResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetTemplate
#define SOAP_TYPE_PointerTo_ns1__GetTemplate (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetTemplate(struct soap*, _ns1__GetTemplate *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetTemplate(struct soap*, _ns1__GetTemplate *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetTemplate(struct soap*, const char *, int, _ns1__GetTemplate *const*, const char *);
SOAP_FMAC3 _ns1__GetTemplate ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetTemplate(struct soap*, _ns1__GetTemplate **, const char*, const char*);
SOAP_FMAC3 _ns1__GetTemplate ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetTemplate(struct soap*, const char*, _ns1__GetTemplate **, const char*);

#ifndef SOAP_TYPE_PointerTostruct_5
#define SOAP_TYPE_PointerTostruct_5 (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostruct_5(struct soap*, struct struct_5 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostruct_5(struct soap*, struct struct_5 *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostruct_5(struct soap*, const char *, int, struct struct_5 *const*, const char *);
SOAP_FMAC3 struct struct_5 ** SOAP_FMAC4 soap_get_PointerTostruct_5(struct soap*, struct struct_5 **, const char*, const char*);
SOAP_FMAC3 struct struct_5 ** SOAP_FMAC4 soap_in_PointerTostruct_5(struct soap*, const char*, struct struct_5 **, const char*);

#ifndef SOAP_TYPE_PointerTostruct_4
#define SOAP_TYPE_PointerTostruct_4 (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostruct_4(struct soap*, struct struct_4 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostruct_4(struct soap*, struct struct_4 *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostruct_4(struct soap*, const char *, int, struct struct_4 *const*, const char *);
SOAP_FMAC3 struct struct_4 ** SOAP_FMAC4 soap_get_PointerTostruct_4(struct soap*, struct struct_4 **, const char*, const char*);
SOAP_FMAC3 struct struct_4 ** SOAP_FMAC4 soap_in_PointerTostruct_4(struct soap*, const char*, struct struct_4 **, const char*);

#ifndef SOAP_TYPE_PointerTostruct_3
#define SOAP_TYPE_PointerTostruct_3 (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostruct_3(struct soap*, struct struct_3 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostruct_3(struct soap*, struct struct_3 *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostruct_3(struct soap*, const char *, int, struct struct_3 *const*, const char *);
SOAP_FMAC3 struct struct_3 ** SOAP_FMAC4 soap_get_PointerTostruct_3(struct soap*, struct struct_3 **, const char*, const char*);
SOAP_FMAC3 struct struct_3 ** SOAP_FMAC4 soap_in_PointerTostruct_3(struct soap*, const char*, struct struct_3 **, const char*);

#ifndef SOAP_TYPE_PointerTostruct_2
#define SOAP_TYPE_PointerTostruct_2 (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostruct_2(struct soap*, struct struct_2 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostruct_2(struct soap*, struct struct_2 *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostruct_2(struct soap*, const char *, int, struct struct_2 *const*, const char *);
SOAP_FMAC3 struct struct_2 ** SOAP_FMAC4 soap_get_PointerTostruct_2(struct soap*, struct struct_2 **, const char*, const char*);
SOAP_FMAC3 struct struct_2 ** SOAP_FMAC4 soap_in_PointerTostruct_2(struct soap*, const char*, struct struct_2 **, const char*);

#ifndef SOAP_TYPE_PointerTostruct_1
#define SOAP_TYPE_PointerTostruct_1 (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostruct_1(struct soap*, struct struct_1 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostruct_1(struct soap*, struct struct_1 *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostruct_1(struct soap*, const char *, int, struct struct_1 *const*, const char *);
SOAP_FMAC3 struct struct_1 ** SOAP_FMAC4 soap_get_PointerTostruct_1(struct soap*, struct struct_1 **, const char*, const char*);
SOAP_FMAC3 struct struct_1 ** SOAP_FMAC4 soap_in_PointerTostruct_1(struct soap*, const char*, struct struct_1 **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of soapH.h */
