/****************************************************************************
**
** Metadata for DSOFramer generated by dumpcpp from type library
** dsoframer.ocx
**
****************************************************************************/

#define QAX_DUMPCPP_DSOFRAMER_NOINLINES
#include "dsoframer.h"

using namespace DSOFramer;

static const uint qt_meta_data_DSOFramer___FramerControl[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       53,    10, // methods
       23,    275, // properties
       5,    344, // enums/sets

 // signals: signature, parameters, type, tag, flags
       26, 65, 87, 88, 5,
       89, 114, 119, 120, 5,
       121, 147, 162, 163, 5,

 // slots: signature, parameters, type, tag, flags
       164, 175, 176, 177, 9,
       178, 186, 187, 188, 9,
       189, 208, 225, 226, 9,
       227, 265, 270, 275, 9,
       276, 296, 305, 306, 11,
       307, 336, 353, 354, 11,
       355, 394, 420, 421, 11,
       422, 471, 509, 510, 9,
       511, 542, 565, 574, 9,
       575, 590, 599, 600, 11,
       601, 625, 643, 644, 11,
       645, 678, 703, 704, 11,
       705, 747, 784, 785, 11,
       786, 837, 886, 887, 9,
       888, 899, 900, 901, 11,
       902, 921, 932, 933, 11,
       934, 962, 985, 986, 11,
       987, 1024, 1054, 1055, 11,
       1056, 1102, 1141, 1142, 11,
       1143, 1198, 1244, 1245, 11,
       1246, 1310, 1367, 1368, 9,
       1369, 1384, 1385, 1386, 9,
       1387, 1406, 1407, 1408, 9,
       1409, 1416, 1417, 1418, 11,
       1419, 1434, 1449, 1450, 11,
       1451, 1475, 1508, 1509, 11,
       1510, 1543, 1588, 1589, 11,
       1590, 1632, 1689, 1690, 9,
       1691, 1732, 1749, 1750, 9,
       1751, 1772, 1782, 1783, 9,
       1784, 1807, 1819, 1820, 9,
       1821, 1852, 1864, 1865, 9,
       1866, 1886, 1894, 1895, 9,
       1896, 1936, 1973, 1974, 9,
       1975, 2021, 2030, 2031, 9,
       2032, 2055, 2069, 2070, 9,
       2071, 2092, 2102, 2103, 9,
       2104, 2143, 2159, 2160, 9,
       2161, 2182, 2191, 2192, 9,
       2193, 2213, 2224, 2225, 9,
       2226, 2252, 2269, 2270, 9,
       2271, 2288, 2296, 2297, 9,
       2298, 2318, 2329, 2330, 9,
       2331, 2349, 2358, 2359, 9,
       2360, 2385, 2399, 2400, 9,
       2401, 2430, 2448, 2449, 9,
       2450, 2468, 2477, 2478, 9,
       2479, 2509, 2517, 2518, 9,
       2519, 2534, 2535, 2536, 11,
       2537, 2560, 2582, 2583, 9,

 // properties: name, type, flags
       2584, 2601, 0x0201500b, 		 // dsoActivationPolicy ActivationPolicy
       2621, 2636, 0x00005001, 		 // IDispatch* ActiveDocument
       2647, 2657, 0x43015003, 		 // QColor BackColor
       2664, 2676, 0x43015003, 		 // QColor BorderColor
       2683, 2695, 0x0201500b, 		 // dsoBorderStyle BorderStyle
       2710, 2718, 0x0a015003, 		 // QString Caption
       2726, 2743, 0x0a005001, 		 // QString DocumentFullName
       2751, 2764, 0x0a005001, 		 // QString DocumentName
       2772, 2786, 0x01014003, 		 // bool EventsEnabled
       2791, 2801, 0x43015003, 		 // QColor ForeColor
       2808, 2824, 0x0201500b, 		 // dsoFrameHookPolicy FrameHookPolicy
       2843, 2852, 0x0a015003, 		 // QString HostName
       2860, 2868, 0x01005001, 		 // bool IsDirty
       2873, 2884, 0x01005001, 		 // bool IsReadOnly
       2889, 2900, 0x01015003, 		 // bool LockServer
       2905, 2922, 0x01015003, 		 // bool MenuAccelerators
       2927, 2935, 0x01015003, 		 // bool Menubar
       2940, 2951, 0x01014003, 		 // bool ModalState
       2956, 2965, 0x01015003, 		 // bool Titlebar
       2970, 2984, 0x43015003, 		 // QColor TitlebarColor
       2991, 3009, 0x43015003, 		 // QColor TitlebarTextColor
       3016, 3025, 0x01015003, 		 // bool Toolbars
       3030, 3038, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
       3046, 0x0, 4, 364, 
       3066, 0x0, 4, 372, 
       3081, 0x0, 9, 380, 
       3100, 0x0, 4, 398, 
       3119, 0x0, 7, 406, 

 // enum data: key, value
       3137, DSOFramer::dsoDefaultBehavior,
       3156, DSOFramer::dsoKeepUIActiveOnAppDeactive,
       3185, DSOFramer::dsoCompDeactivateOnLostFocus,
       3214, DSOFramer::dsoIPDeactivateOnCompDeactive,
       3244, DSOFramer::dsoBorderNone,
       3258, DSOFramer::dsoBorderFlat,
       3272, DSOFramer::dsoBorder3D,
       3284, DSOFramer::dsoBorder3DThin,
       3300, DSOFramer::dsoFileNew,
       3311, DSOFramer::dsoFileOpen,
       3323, DSOFramer::dsoFileClose,
       3336, DSOFramer::dsoFileSave,
       3348, DSOFramer::dsoFileSaveAs,
       3362, DSOFramer::dsoFilePrint,
       3375, DSOFramer::dsoFilePageSetup,
       3392, DSOFramer::dsoFileProperties,
       3410, DSOFramer::dsoFilePrintPreview,
       3430, DSOFramer::dsoNormalBehavior,
       3448, DSOFramer::dsoSetOnFirstOpen,
       3466, DSOFramer::dsoResetNow,
       3478, DSOFramer::dsoDisableHook,
       3493, DSOFramer::dsoDialogNew,
       3506, DSOFramer::dsoDialogOpen,
       3520, DSOFramer::dsoDialogSave,
       3534, DSOFramer::dsoDialogSaveCopy,
       3552, DSOFramer::dsoDialogPrint,
       3567, DSOFramer::dsoDialogPageSetup,
       3586, DSOFramer::dsoDialogProperties,

        0        // eod
};

static const char qt_meta_enumstringdata_DSOFramer[] = {
    "dsoActivationPolicy\0dsoBorderStyle\0dsoFileCommandType\0dsoFrameHookPolicy\0dsoShowDialogType\0"
    "dsoDefaultBehavior\0dsoKeepUIActiveOnAppDeactive\0dsoCompDeactivateOnLostFocus\0"
    "dsoIPDeactivateOnCompDeactive\0"
    "dsoBorderNone\0dsoBorderFlat\0dsoBorder3D\0dsoBorder3DThin\0"
    "dsoFileNew\0dsoFileOpen\0dsoFileClose\0dsoFileSave\0dsoFileSaveAs\0dsoFilePrint\0dsoFilePageSetup\0dsoFileProperties\0dsoFilePrintPreview\0"
    ""
    "dsoNormalBehavior\0dsoSetOnFirstOpen\0dsoResetNow\0dsoDisableHook\0"
    "dsoDialogNew\0dsoDialogOpen\0dsoDialogSave\0dsoDialogSaveCopy\0dsoDialogPrint\0dsoDialogPageSetup\0dsoDialogProperties\0"

};

static const char *qt_meta_stringdata_DSOFramer___FramerControl() {
    static const char stringdata0[] = {
    "DSOFramer::_FramerControl\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "Activate()\0\0\0\0Close()\0\0\0\0CreateNew(QString)\0ProgIdOrTemplate\0\0\0"
    "EnableFileCommand(dsoFileCommandType)\0Item\0bool\0\0ExecOleCommand(int)\0OLECMDID\0\0\0ExecOleCommand(int,QVariant)\0OLECMDID,Options\0\0\0ExecOleCommand(int,QVariant,QVariant&)\0OLECMDID,Options,vInParam\0\0\0ExecOleCommand(int,QVariant,QVariant&,QVariant&)\0"
    "OLECMDID,Options,vInParam,vInOutParam\0\0\0GetDataObjectContent(QVariant)\0ClipFormatNameOrNumber\0QVariant\0\0Open(QVariant)\0Document\0\0\0Open(QVariant,QVariant)\0Document,ReadOnly\0\0\0Open(QVariant,QVariant,QVariant)\0"
    "Document,ReadOnly,ProgId\0\0\0Open(QVariant,QVariant,QVariant,QVariant)\0Document,ReadOnly,ProgId,WebUsername\0\0\0Open(QVariant,QVariant,QVariant,QVariant,QVariant)\0Document,ReadOnly,ProgId,WebUsername,WebPassword\0"
    "\0\0PrintOut()\0\0\0\0PrintOut(QVariant)\0PromptUser\0\0\0PrintOut(QVariant,QVariant)\0PromptUser,PrinterName\0\0\0PrintOut(QVariant,QVariant,QVariant)\0PromptUser,PrinterName,Copies\0\0\0PrintOut(QVariant,QVariant,QVariant,QVariant)\0"
    "PromptUser,PrinterName,Copies,FromPage\0\0\0PrintOut(QVariant,QVariant,QVariant,QVariant,QVariant)\0PromptUser,PrinterName,Copies,FromPage,ToPage\0\0\0PrintOut(QVariant,QVariant,QVariant,QVariant,QVariant,QVariant)\0"
    "PromptUser,PrinterName,Copies,FromPage,ToPage,OutputFile\0\0\0PrintPreview()\0\0\0\0PrintPreviewExit()\0\0\0\0Save()\0\0\0\0Save(QVariant)\0SaveAsDocument\0\0\0Save(QVariant,QVariant)\0SaveAsDocument,OverwriteExisting\0\0\0Save(QVariant,QVariant,QVariant)\0"
    "SaveAsDocument,OverwriteExisting,WebUsername\0\0\0Save(QVariant,QVariant,QVariant,QVariant)\0SaveAsDocument,OverwriteExisting,WebUsername,WebPassword\0\0\0SetActivationPolicy(dsoActivationPolicy)\0ActivationPolicy\0"
    "\0\0SetBackColor(QColor)\0BackColor\0\0\0SetBorderColor(QColor)\0BorderColor\0\0\0SetBorderStyle(dsoBorderStyle)\0BorderStyle\0\0\0SetCaption(QString)\0Caption\0\0\0SetDataObjectContent(QVariant,QVariant)\0ClipFormatNameOrNumber,DataByteArray\0"
    "\0\0SetEnableFileCommand(dsoFileCommandType,bool)\0Item,rhs\0\0\0SetEventsEnabled(bool)\0EventsEnabled\0\0\0SetForeColor(QColor)\0ForeColor\0\0\0SetFrameHookPolicy(dsoFrameHookPolicy)\0FrameHookPolicy\0\0\0SetHostName(QString)\0"
    "HostName\0\0\0SetLockServer(bool)\0LockServer\0\0\0SetMenuAccelerators(bool)\0MenuAccelerators\0\0\0SetMenubar(bool)\0Menubar\0\0\0SetModalState(bool)\0ModalState\0\0\0SetTitlebar(bool)\0Titlebar\0\0\0SetTitlebarColor(QColor)\0"
    "TitlebarColor\0\0\0SetTitlebarTextColor(QColor)\0TitlebarTextColor\0\0\0SetToolbars(bool)\0Toolbars\0\0\0ShowDialog(dsoShowDialogType)\0DlgType\0\0\0_PrintOutOld()\0\0\0\0_PrintOutOld(QVariant)\0PromptToSelectPrinter\0\0\0"
    "ActivationPolicy\0"
    "dsoActivationPolicy\0ActiveDocument\0IDispatch*\0BackColor\0QColor\0BorderColor\0QColor\0BorderStyle\0dsoBorderStyle\0Caption\0QString\0DocumentFullName\0QString\0DocumentName\0QString\0EventsEnabled\0bool\0ForeColor\0QColor\0"
    "FrameHookPolicy\0dsoFrameHookPolicy\0HostName\0QString\0IsDirty\0bool\0IsReadOnly\0bool\0LockServer\0bool\0MenuAccelerators\0bool\0Menubar\0bool\0ModalState\0bool\0Titlebar\0bool\0TitlebarColor\0QColor\0TitlebarTextColor\0"
    "QColor\0Toolbars\0bool\0control\0QString\0"
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_DSOFramer)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_DSOFramer, sizeof(qt_meta_enumstringdata_DSOFramer));
    }

    return data;
};

const QMetaObject _FramerControl::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_DSOFramer___FramerControl(),
qt_meta_data_DSOFramer___FramerControl }
};

void *_FramerControl::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_DSOFramer___FramerControl()))
        return static_cast<void*>(const_cast<_FramerControl*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_DSOFramer__FramerControl[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       61,    10, // methods
       22,    315, // properties
       5,    381, // enums/sets

 // signals: signature, parameters, type, tag, flags
       25, 64, 80, 81, 5,
       82, 128, 153, 154, 5,
       155, 180, 193, 194, 5,
       195, 214, 215, 216, 5,
       217, 254, 268, 269, 5,
       270, 310, 322, 323, 5,
       324, 345, 346, 347, 5,
       348, 392, 426, 427, 5,
       428, 467, 489, 490, 5,
       491, 516, 521, 522, 5,
       523, 549, 564, 565, 5,

 // slots: signature, parameters, type, tag, flags
       566, 577, 578, 579, 9,
       580, 588, 589, 590, 9,
       591, 610, 627, 628, 9,
       629, 667, 672, 677, 9,
       678, 698, 707, 708, 11,
       709, 738, 755, 756, 11,
       757, 796, 822, 823, 11,
       824, 873, 911, 912, 9,
       913, 944, 967, 976, 9,
       977, 992, 1001, 1002, 11,
       1003, 1027, 1045, 1046, 11,
       1047, 1080, 1105, 1106, 11,
       1107, 1149, 1186, 1187, 11,
       1188, 1239, 1288, 1289, 9,
       1290, 1301, 1302, 1303, 11,
       1304, 1323, 1334, 1335, 11,
       1336, 1364, 1387, 1388, 11,
       1389, 1426, 1456, 1457, 11,
       1458, 1504, 1543, 1544, 11,
       1545, 1600, 1646, 1647, 11,
       1648, 1712, 1769, 1770, 9,
       1771, 1786, 1787, 1788, 9,
       1789, 1808, 1809, 1810, 9,
       1811, 1818, 1819, 1820, 11,
       1821, 1836, 1851, 1852, 11,
       1853, 1877, 1910, 1911, 11,
       1912, 1945, 1990, 1991, 11,
       1992, 2034, 2091, 2092, 9,
       2093, 2134, 2151, 2152, 9,
       2153, 2174, 2184, 2185, 9,
       2186, 2209, 2221, 2222, 9,
       2223, 2254, 2266, 2267, 9,
       2268, 2288, 2296, 2297, 9,
       2298, 2338, 2375, 2376, 9,
       2377, 2423, 2432, 2433, 9,
       2434, 2457, 2471, 2472, 9,
       2473, 2494, 2504, 2505, 9,
       2506, 2545, 2561, 2562, 9,
       2563, 2584, 2593, 2594, 9,
       2595, 2615, 2626, 2627, 9,
       2628, 2654, 2671, 2672, 9,
       2673, 2690, 2698, 2699, 9,
       2700, 2720, 2731, 2732, 9,
       2733, 2751, 2760, 2761, 9,
       2762, 2787, 2801, 2802, 9,
       2803, 2832, 2850, 2851, 9,
       2852, 2870, 2879, 2880, 9,
       2881, 2911, 2919, 2920, 9,
       2921, 2936, 2937, 2938, 11,
       2939, 2962, 2984, 2985, 9,

 // properties: name, type, flags
       2986, 3003, 0x0201500b, 		 // dsoActivationPolicy ActivationPolicy
       3023, 3038, 0x00005001, 		 // IDispatch* ActiveDocument
       3049, 3059, 0x43015003, 		 // QColor BackColor
       3066, 3078, 0x43015003, 		 // QColor BorderColor
       3085, 3097, 0x0201500b, 		 // dsoBorderStyle BorderStyle
       3112, 3120, 0x0a015003, 		 // QString Caption
       3128, 3145, 0x0a005001, 		 // QString DocumentFullName
       3153, 3166, 0x0a005001, 		 // QString DocumentName
       3174, 3188, 0x01014003, 		 // bool EventsEnabled
       3193, 3203, 0x43015003, 		 // QColor ForeColor
       3210, 3226, 0x0201500b, 		 // dsoFrameHookPolicy FrameHookPolicy
       3245, 3254, 0x0a015003, 		 // QString HostName
       3262, 3270, 0x01005001, 		 // bool IsDirty
       3275, 3286, 0x01005001, 		 // bool IsReadOnly
       3291, 3302, 0x01015003, 		 // bool LockServer
       3307, 3324, 0x01015003, 		 // bool MenuAccelerators
       3329, 3337, 0x01015003, 		 // bool Menubar
       3342, 3353, 0x01014003, 		 // bool ModalState
       3358, 3367, 0x01015003, 		 // bool Titlebar
       3372, 3386, 0x43015003, 		 // QColor TitlebarColor
       3393, 3411, 0x43015003, 		 // QColor TitlebarTextColor
       3418, 3427, 0x01015003, 		 // bool Toolbars

 // enums: name, flags, count, data
       3432, 0x0, 4, 401, 
       3452, 0x0, 4, 409, 
       3467, 0x0, 9, 417, 
       3486, 0x0, 4, 435, 
       3505, 0x0, 7, 443, 

 // enum data: key, value
       3523, DSOFramer::dsoDefaultBehavior,
       3542, DSOFramer::dsoKeepUIActiveOnAppDeactive,
       3571, DSOFramer::dsoCompDeactivateOnLostFocus,
       3600, DSOFramer::dsoIPDeactivateOnCompDeactive,
       3630, DSOFramer::dsoBorderNone,
       3644, DSOFramer::dsoBorderFlat,
       3658, DSOFramer::dsoBorder3D,
       3670, DSOFramer::dsoBorder3DThin,
       3686, DSOFramer::dsoFileNew,
       3697, DSOFramer::dsoFileOpen,
       3709, DSOFramer::dsoFileClose,
       3722, DSOFramer::dsoFileSave,
       3734, DSOFramer::dsoFileSaveAs,
       3748, DSOFramer::dsoFilePrint,
       3761, DSOFramer::dsoFilePageSetup,
       3778, DSOFramer::dsoFileProperties,
       3796, DSOFramer::dsoFilePrintPreview,
       3816, DSOFramer::dsoNormalBehavior,
       3834, DSOFramer::dsoSetOnFirstOpen,
       3852, DSOFramer::dsoResetNow,
       3864, DSOFramer::dsoDisableHook,
       3879, DSOFramer::dsoDialogNew,
       3892, DSOFramer::dsoDialogOpen,
       3906, DSOFramer::dsoDialogSave,
       3920, DSOFramer::dsoDialogSaveCopy,
       3938, DSOFramer::dsoDialogPrint,
       3953, DSOFramer::dsoDialogPageSetup,
       3972, DSOFramer::dsoDialogProperties,

        0        // eod
};

static const char *qt_meta_stringdata_DSOFramer__FramerControl() {
    static const char stringdata0[] = {
    "DSOFramer::FramerControl\0"
    "BeforeDocumentClosed(IDispatch*,bool&)\0Document,Cancel\0\0\0BeforeDocumentSaved(IDispatch*,QString,bool&)\0Document,Location,Cancel\0\0\0OnActivationChange(bool)\0fGoingActive\0\0\0OnDocumentClosed()\0\0\0\0OnDocumentOpened(QString,IDispatch*)\0"
    "File,Document\0\0\0OnFileCommand(dsoFileCommandType,bool&)\0Item,Cancel\0\0\0OnPrintPreviewExit()\0\0\0\0OnSaveCompleted(IDispatch*,QString,QString)\0Document,DocName,FullFileLocation\0\0\0exception(int,QString,QString,QString)\0"
    "code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "Activate()\0\0\0\0Close()\0\0\0\0CreateNew(QString)\0ProgIdOrTemplate\0\0\0EnableFileCommand(dsoFileCommandType)\0Item\0"
    "bool\0\0ExecOleCommand(int)\0OLECMDID\0\0\0ExecOleCommand(int,QVariant)\0OLECMDID,Options\0\0\0ExecOleCommand(int,QVariant,QVariant&)\0OLECMDID,Options,vInParam\0\0\0ExecOleCommand(int,QVariant,QVariant&,QVariant&)\0"
    "OLECMDID,Options,vInParam,vInOutParam\0\0\0GetDataObjectContent(QVariant)\0ClipFormatNameOrNumber\0QVariant\0\0Open(QVariant)\0Document\0\0\0Open(QVariant,QVariant)\0Document,ReadOnly\0\0\0Open(QVariant,QVariant,QVariant)\0"
    "Document,ReadOnly,ProgId\0\0\0Open(QVariant,QVariant,QVariant,QVariant)\0Document,ReadOnly,ProgId,WebUsername\0\0\0Open(QVariant,QVariant,QVariant,QVariant,QVariant)\0Document,ReadOnly,ProgId,WebUsername,WebPassword\0"
    "\0\0PrintOut()\0\0\0\0PrintOut(QVariant)\0PromptUser\0\0\0PrintOut(QVariant,QVariant)\0PromptUser,PrinterName\0\0\0PrintOut(QVariant,QVariant,QVariant)\0PromptUser,PrinterName,Copies\0\0\0PrintOut(QVariant,QVariant,QVariant,QVariant)\0"
    "PromptUser,PrinterName,Copies,FromPage\0\0\0PrintOut(QVariant,QVariant,QVariant,QVariant,QVariant)\0PromptUser,PrinterName,Copies,FromPage,ToPage\0\0\0PrintOut(QVariant,QVariant,QVariant,QVariant,QVariant,QVariant)\0"
    "PromptUser,PrinterName,Copies,FromPage,ToPage,OutputFile\0\0\0PrintPreview()\0\0\0\0PrintPreviewExit()\0\0\0\0Save()\0\0\0\0Save(QVariant)\0SaveAsDocument\0\0\0Save(QVariant,QVariant)\0SaveAsDocument,OverwriteExisting\0\0\0Save(QVariant,QVariant,QVariant)\0"
    "SaveAsDocument,OverwriteExisting,WebUsername\0\0\0Save(QVariant,QVariant,QVariant,QVariant)\0SaveAsDocument,OverwriteExisting,WebUsername,WebPassword\0\0\0SetActivationPolicy(dsoActivationPolicy)\0ActivationPolicy\0"
    "\0\0SetBackColor(QColor)\0BackColor\0\0\0SetBorderColor(QColor)\0BorderColor\0\0\0SetBorderStyle(dsoBorderStyle)\0BorderStyle\0\0\0SetCaption(QString)\0Caption\0\0\0SetDataObjectContent(QVariant,QVariant)\0ClipFormatNameOrNumber,DataByteArray\0"
    "\0\0SetEnableFileCommand(dsoFileCommandType,bool)\0Item,rhs\0\0\0SetEventsEnabled(bool)\0EventsEnabled\0\0\0SetForeColor(QColor)\0ForeColor\0\0\0SetFrameHookPolicy(dsoFrameHookPolicy)\0FrameHookPolicy\0\0\0SetHostName(QString)\0"
    "HostName\0\0\0SetLockServer(bool)\0LockServer\0\0\0SetMenuAccelerators(bool)\0MenuAccelerators\0\0\0SetMenubar(bool)\0Menubar\0\0\0SetModalState(bool)\0ModalState\0\0\0SetTitlebar(bool)\0Titlebar\0\0\0SetTitlebarColor(QColor)\0"
    "TitlebarColor\0\0\0SetTitlebarTextColor(QColor)\0TitlebarTextColor\0\0\0SetToolbars(bool)\0Toolbars\0\0\0ShowDialog(dsoShowDialogType)\0DlgType\0\0\0_PrintOutOld()\0\0\0\0_PrintOutOld(QVariant)\0PromptToSelectPrinter\0\0\0"
    "ActivationPolicy\0"
    "dsoActivationPolicy\0ActiveDocument\0IDispatch*\0BackColor\0QColor\0BorderColor\0QColor\0BorderStyle\0dsoBorderStyle\0Caption\0QString\0DocumentFullName\0QString\0DocumentName\0QString\0EventsEnabled\0bool\0ForeColor\0QColor\0"
    "FrameHookPolicy\0dsoFrameHookPolicy\0HostName\0QString\0IsDirty\0bool\0IsReadOnly\0bool\0LockServer\0bool\0MenuAccelerators\0bool\0Menubar\0bool\0ModalState\0bool\0Titlebar\0bool\0TitlebarColor\0QColor\0TitlebarTextColor\0"
    "QColor\0Toolbars\0bool\0"
    };
    static char data[sizeof(stringdata0) + sizeof(qt_meta_enumstringdata_DSOFramer)];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
        memcpy(data + index, qt_meta_enumstringdata_DSOFramer, sizeof(qt_meta_enumstringdata_DSOFramer));
    }

    return data;
};

const QMetaObject FramerControl::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_DSOFramer__FramerControl(),
qt_meta_data_DSOFramer__FramerControl }
};

void *FramerControl::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_DSOFramer__FramerControl()))
        return static_cast<void*>(const_cast<FramerControl*>(this));
    return QAxWidget::qt_metacast(_clname);
}

