/*
* DO NOT EDIT THIS FILE - it is generated by Glade.
* WINDOWS HANVE SYN TO UNIX  by chi.hailong 2007.06.15 ;
* last SYN by hcl 2007.11.28
*/

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
/*
#include <unistd.h>
#include <string.h>
#include <sys/ddi.h> */
#include <stdio.h>
#include <gtk/gtk.h>
#include <glib.h>

#include "../../../dms/v4.0a/inc/dms_com.h"
#include "../inc/gtk_ipm_k_def.h"
#include "../inc/gtk_oix_cstr.h"
#include "../inc/gtk_msg_text_def.h"
#include "../inc/gtk_widgets.h"
#include "../inc/gtk_db_tab_def.h"
#include 	"../../../pas/v4.0a/inc/relatepoint.h"
#include "../inc/gtk_search_data.h"

#define G_SAFE_FREE(p)	\
	if (p != 0)			\
	{					\
	g_free(p);		\
	p=0;			\
	}

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
	g_object_set_data_full (G_OBJECT (component), name, \
gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
g_object_set_data (G_OBJECT (component), name, widget)

#define RELATEPTINTERVAL 1000
gint 	relatept_timeout_id[MAX_CRT_NUMBER] ={0,0,0} ;

#define VBOX1_WIDTH   (120+80) 
#define VBOX2_WIDTH   300
#define BOX_HEIGHT    350
extern DB_TAB_WINDOW_INFO db_tab_window_info[];
extern RelatePoint			*relatepoint;
extern void 	PopupDetailInfoBox(GtkWidget* , int crt_n, POINTER pt);
extern void GetCrtNumberOfWgt ( GtkWidget  *wgt, int     *crt_n );
extern char *_toUtf8(char *c);
extern char *_fromUtf8(char *c);
extern char *_toUtf8EX(char *c);
extern GtkWidget *searchdialog[MAX_CRT_NUMBER];

extern int getCrtNumFromPointer(int data);
extern int getDataFromPointer(int data);
extern int getMenuDataPointer(int crtn,int data);
extern void	PopupMessageBox (GtkWidget *parent,char msg[] );


extern GtkWidget *searchdialog[MAX_CRT_NUMBER];  
void UpdateSearchDbDevMenu(int crt_n) ; 
com_property_col= sizeof(com_property)/sizeof(com_property[0]);
Imp_property_col= sizeof(Imp_property)/sizeof(Imp_property[0]);
Pol_SOE_property_col= sizeof(Pol_SOE_property)/sizeof(Pol_SOE_property[0]);
opr_num = sizeof(opr_name)/sizeof(opr_name[0]);

void
on_stn_filter_combox_changed           (GtkComboBox     *combobox,
                                        gpointer         user_data)
{
}

void
on_dev_filter_combox_changed           (GtkComboBox     *combobox,
                                        gpointer         user_data)
{
	1==1 ; 
}
void GetPropertyOption(DMS_COMMON db_cmm,BOOL *opt_meet);
void DspSearchPage (int crt_n, int pt_num );


void GetStnFilterSelect(GtkWidget* widget,gpointer         user_data) 
{
	int crt_n,data ; 
	crt_n=getCrtNumFromPointer((int)user_data);
	data=getDataFromPointer((int)user_data);
	search_pt.stn_id = (gint)data;
	printf("search_pt.stn_id=%d\n",search_pt.stn_id);
	UpdateSearchDbDevMenu(  crt_n) ; 
}

void GetDevFilterSelect(GtkWidget* widget,gpointer         user_data) 
{
	int crt_n ,data ;
	crt_n=getCrtNumFromPointer((int)user_data);
	data=getDataFromPointer((int)user_data);
	search_pt.dev_id = (gint)data;
	printf("search_pt.dev_id=%d\n",search_pt.dev_id);
}


void UpdateSearchDbDevMenu(int crt_n) 
{
	char	dev_comment[GROUP_COMMENT_SIZE];
	UCHAR	stn_id, dev_id;
	int		i,grp_num;
	GtkWidget *menu,*items,*optionMenu;
	int MenuPointer;
	gchar *pConvert=0;

	optionMenu  = GTK_WIDGET((GtkOptionMenu*) g_object_get_data(G_OBJECT(searchdialog[crt_n]),"dev_filter_combox"));
	//	menu =gtk_option_menu_get_menu(GTK_OPTION_MENU(optionMenu));
	gtk_option_menu_remove_menu(GTK_OPTION_MENU(optionMenu));
	
	menu =gtk_menu_new();
	gtk_widget_set_usize(menu, 130, -1);
	
	stn_id=  search_pt.stn_id  ;
    if  (stn_id==0)
	{
		items = gtk_menu_item_new_with_label(pConvert=_toUtf8EX("OIX_STR_SEL_STATION")); // "OIX_STR_SEL_STATION" 请选择厂站
		G_SAFE_FREE(pConvert);
		gtk_container_add(GTK_CONTAINER(menu),items);
	}
	else
	{
		if(-1==GetGroupNumById(stn_id, &grp_num))
			return;	
		dev_id= 0;
		for(i=0; i<=grp_num; i++) 
		{  	
			if (i==0)
			{
				strcpy (dev_comment, pConvert=_toUtf8EX("OIX_ALL_DEVICES"));   //OIX_ALL_DEVICES  所有设备
				G_SAFE_FREE(pConvert);
			}
			else
				if(-1==GetGroupCommentById(stn_id, (UCHAR)i, dev_comment))
					continue;
				items = gtk_menu_item_new_with_label(pConvert=_toUtf8(dev_comment));	 
				G_SAFE_FREE(pConvert);
				gtk_container_add(GTK_CONTAINER(menu),items);
				MenuPointer=getMenuDataPointer(crt_n,i);
				gtk_signal_connect(GTK_OBJECT(items), "activate", GTK_SIGNAL_FUNC(GetDevFilterSelect), (gpointer)MenuPointer);
				if(!dev_id)
					dev_id= i;
		}
	}	
    gtk_option_menu_set_menu(GTK_OPTION_MENU(optionMenu),menu);
	gtk_option_menu_set_history(GTK_OPTION_MENU(optionMenu), 0);
	//	db_tab_window_info[crt_n].select_pt.dev_id= dev_id;
	gtk_widget_show_all(optionMenu);
}


BOOL Cmpfvalue(float real_fval,float obj_fval,int k)
{
    BOOL result= TRUE;
	if(strcmp(search_pt.opr[k],"=")==0)
	{ 
		if(real_fval==obj_fval)
			result = result&TRUE;
		else
			result=result&FALSE;                                 
	}
	else if(strcmp(search_pt.opr[k],"<")==0)
	{ 
		if(real_fval<obj_fval)
			result = result&TRUE;
		else
			result=result&FALSE;                                 
	}
	else if(strcmp(search_pt.opr[k],">")==0)
	{ 
		if(real_fval>obj_fval)
			result = result&TRUE;
		else
			result=result&FALSE;                                 
	}
	else if(strcmp(search_pt.opr[k],"<=")==0)
	{ 
		if(real_fval<=obj_fval)
			result = result&TRUE;
		else
			result=result&FALSE;                                 
	}
	else if(strcmp(search_pt.opr[k],">=")==0)
	{ 
		if(real_fval>=obj_fval)
			result = result&TRUE;
		else
			result=result&FALSE;                                 
	}
	else if(strcmp(search_pt.opr[k],"!=")==0)
	{ 
		if(real_fval!=obj_fval)
			result = result&TRUE;
		else
			result=result&FALSE;                                 
	}
	else
		result=result&FALSE;  
    return result;
}

BOOL CmpInt(int real_fval,int obj_fval,int k)
{
    BOOL result= TRUE;
	if(strcmp(search_pt.opr[k],"=")==0)
	{
		if(real_fval==obj_fval)
			result = result&TRUE;
		else
			result=result&FALSE; 
	}
	else if(strcmp(search_pt.opr[k],"<")==0)
	{ 
		if(real_fval<obj_fval)
			result = result&TRUE;
		else
			result=result&FALSE;                                 
	}
	else if(strcmp(search_pt.opr[k],">")==0)
	{ 
		if(real_fval>obj_fval)
			result = result&TRUE;
		else
			result=result&FALSE;                                 
	}
	else if(strcmp(search_pt.opr[k],"<=")==0)
	{ 
		if(real_fval<=obj_fval)
			result = result&TRUE;
		else
			result=result&FALSE;                                 
	}
	else if(strcmp(search_pt.opr[k],">=")==0)
	{ 
		if(real_fval>=obj_fval)
			result = result&TRUE;
		else
			result=result&FALSE;                                 
	}
	else if(strcmp(search_pt.opr[k],"!=")==0)
	{ 
		if(real_fval!=obj_fval)
			result = result&TRUE;
		else
			result=result&FALSE;                                 
	}
	else
		result=result&FALSE;  
    return result;
}
#ifndef _LeadByte
#define _LeadByte 		0x80      
#endif
#ifndef _isLeadbyte  
#define _isLeadbyte(_c)		( ( unsigned char) ( _c ) & _LeadByte )   
#endif

BOOL CmpString(char s1[256/*50*/],char s2[256/*50*/]/*,int k*/)
{ 
    BOOL result=TRUE;
    int i,lenofs1,lenofs2,s1_pointer=0;
    char tmpstr1[3];
	
	if (strstr(s1,s2)!=(char *)NULL)
		return TRUE;
	else
		return FALSE ;		
    strcpy(tmpstr1,"");		
	
    lenofs1= strlen(s1);
    lenofs2= strlen(s2);
	
	for(i=0;i<lenofs2;i++)
	{
		if(strcmp(s2+i,"*")==0)
		{
			printf("find %s in %s,end,S2+%d=%s\n",s2,s1,i,s2+i);
			result=TRUE;
			break;
		}
		if(s1_pointer>=lenofs1)
		{
			/*	printf("s1[%d]=%c\n",s1_pointer,s1[s1_pointer]);*/
			printf("s1_pointer>=lenofs1::not find %s in %s,s1[%d]=%c \n",s2,s1,s1_pointer,s1[s1_pointer]);
			result= FALSE;
			break;
		}
		if(_isLeadbyte(s2[i]))
		{
			strncpy(tmpstr1,s2+i,2);
			tmpstr1[2]=0;		
		}
		else
		{
			strncpy(tmpstr1,s2+i,1);		
			tmpstr1[1]=0;
		}
		if(strcmp(tmpstr1,"?")==0)
		{
			s1_pointer ++;	
			
			if(s2[i+1] !=s1[s1_pointer] &&(s2[i+1]!='?')&&(s2[i+1]!='*'))
			{
				/*printf("s2[%d]=%c,!=s1[%d]=%c\n",i+1,s2[i+1],s1_pointer,s1[s1_pointer]);*/
				printf("IN ?::not find %s in %s \n",s2,s1);
				result = FALSE;
				break;
			}			
		}
		else if(strcmp(tmpstr1,"*")==0)				
			continue;		
		else
		{				
			/*	printf("### s1+%d=%s,tmpstr1=%s\n",s1_pointer,s1+s1_pointer,tmpstr1);*/
			if(strstr(s1+s1_pointer,tmpstr1)==NULL)
			{				
				printf("not find %s in %s \n",tmpstr1,s1+s1_pointer);
				result = FALSE;
				break;
			}
			else
			{
				s1_pointer =s1_pointer+ strlen(s1+s1_pointer)-strlen(strstr(s1+s1_pointer,tmpstr1))/*+1*/;
				if(s2[i+1] !=s1[s1_pointer+1] &&(s2[i+1]!='?')&&(s2[i+1]!='*'))
				{				
					printf("not find %s in %s ,s2[%d]=%c,s1[%d]=%c\n",s2,s1,i+1,s2[i+1],s1_pointer+1,s1[s1_pointer+1]);
					result = FALSE;
					break;
				}
				if(strlen(s1+s1_pointer)-strlen(strstr(s1+s1_pointer,tmpstr1))==0)
					s1_pointer = s1_pointer +1;
				/*printf("@@@@ s1_pointer=%d\n",s1_pointer);*/
			}
			
		}
		if(_isLeadbyte(s2[i]))
		{			
			i++;
			s1_pointer = s1_pointer+2;			
		}		
	}    
    return result;    
}

void
on_detail_btn_pressed                    (GtkButton       *button,
										  gpointer         user_data)
{
    int j,select_pt_id,row,crt_n=0;
	
    GetCrtNumberOfWgt ( GTK_WIDGET(button), &crt_n );
    if( crt_n < 0 )
		return ;    
    row = (int)user_data;
    
    j= cur_search_page.page_no*40+row-1;
    select_pt_id = result_pt[j].pt_id;
    db_tab_window_info[crt_n].select_pt= result_pt[j];
    PopupDetailInfoBox(main_w[crt_n],crt_n,db_tab_window_info[crt_n].select_pt);
}

void on_destroy_search_result_win(GtkWidget *w,gpointer arg)
{
	int crt_n = (gint) arg ;

	if( crt_n < 0 || crt_n > MAX_CRT_NUMBER )
		return ;
	
	SearchResultWin[crt_n]= (void *)NULL ; 

	if(relatept_timeout_id[crt_n]!=0)
	{
		gtk_timeout_remove(relatept_timeout_id[crt_n]);	
		relatept_timeout_id[crt_n]= 0;
	}
}

void
on_exit_btn_pressed                    (GtkButton       *button,
                                        gpointer         user_data)
{
    int crt_n=0;
	
    GetCrtNumberOfWgt ( GTK_WIDGET(button), &crt_n );
    if( crt_n < 0 )
		return ;
    gtk_widget_destroy(user_data);
}


void
on_page_down_pressed                   (GtkButton       *button,
                                        gpointer         user_data)
{
	
    int pt_num;
	
    int crt_n=0;
	
    GetCrtNumberOfWgt ( GTK_WIDGET(button), &crt_n );
    if( crt_n < 0 )
		return ;
    
    printf("down result:::pt_num =%d\n",(gint)user_data);
    pt_num = (gint)user_data;
    cur_search_page.page_no++;
    if(cur_search_page.page_no>=cur_search_page.page_num)
	{
		gdk_beep();
		cur_search_page.page_no--;
		printf("cur_search_page.page_no=%d,page_num=%d,pt_num=%d\n",cur_search_page.page_no,cur_search_page.page_num,pt_num);
		return;
    }
    DspSearchPage(crt_n,pt_num);
}

void
on_page_up_pressed                     (GtkButton       *button,
                                        gpointer         user_data)
{
	int pt_num;
	
    int crt_n=0;
	
    GetCrtNumberOfWgt ( GTK_WIDGET(button), &crt_n );
    if( crt_n < 0 )
		return ;
    
    pt_num = (gint)user_data;
    cur_search_page.page_no--;
    printf("up result:::pt_num =%d,page_no=%d\n",(gint)user_data,cur_search_page.page_no);
    if(cur_search_page.page_no<0)
    {
        gdk_beep();
        cur_search_page.page_no++;
        printf("cur_search_page.page_no=%d,pt_num=%d\n",cur_search_page.page_no,pt_num);
        return;
    }
    DspSearchPage(crt_n,pt_num);
}


void
DspSearchPage (int crt_n, int pt_num )
{
    GtkWidget *result_lab[41][10],*detail_btn[41];
    int row,col,i,j;
    char lab_str[41][10][20],detail_btn_lab[41][20],tmp_str[100];
    DMS_COMMON db_cmm;        
	char  LongNamerStr1[128];
	gchar *pConvert=0;
	
    cur_search_page.start_id = cur_search_page.page_no*40;
    cur_search_page.end_id = MIN(cur_search_page.start_id+40,pt_num);
    
    for(row=1;row<41;row++)
        for(col=0;col<10;col++)
        {
            sprintf(lab_str[row][col],"lab%d",(row-1)*10+col+1);            
            result_lab[row][col] = gtk_object_get_data(GTK_OBJECT(SearchResultWin[crt_n]),lab_str[row][col]);
        }
		
		for(row=1;row<41;row++)
        {
            sprintf(detail_btn_lab[row],"Detail%d",row); 
            detail_btn[row] = gtk_object_get_data(GTK_OBJECT(SearchResultWin[crt_n]),detail_btn_lab[row]);
		}
		/* printf("start_id=%d,end_id=%d\n",cur_search_page.start_id,cur_search_page.end_id);*/
		row =0;
		for(j=cur_search_page.start_id;j<cur_search_page.end_id;j++)
		{        
			sprintf(tmp_str,"%d",result_pt[j].pt_id);
			row = j%40+1;   
			/*printf("j=%d,row=%d,tmp_str=%s\n",j,row,tmp_str);*/
			gtk_label_set_text(GTK_LABEL(result_lab[row][0]),tmp_str);
			
			if ( ReadEntryById (&result_pt[j], &db_cmm ) == -1)		
				continue;  
			
			sprintf(tmp_str,"%s",db_cmm.fixed.entryName);
			gtk_label_set_text(GTK_LABEL(result_lab[row][1]),tmp_str);
			
			GetGroupLongnameById( db_cmm.point.stn_id, db_cmm.point.dev_id, tmp_str );
			GetEntryLongnameById (&db_cmm.point,LongNamerStr1 );
			strcat(tmp_str,LongNamerStr1);
			gtk_label_set_text(GTK_LABEL(result_lab[row][2]), pConvert=_toUtf8(tmp_str));
			G_SAFE_FREE(pConvert);
			
			sprintf(tmp_str,"%d",db_cmm.fixed.iost.noUpdate);
			gtk_label_set_text(GTK_LABEL(result_lab[row][3]), pConvert=_toUtf8(tmp_str));
			G_SAFE_FREE(pConvert);
			
			
			if(result_pt[j].data_type==POL_TYPE||result_pt[j].data_type==SOE_TYPE)                      
				GetIndPtRtStateStrById(&db_cmm.point, tmp_str );
			
			else if(result_pt[j].data_type==ANA_TYPE)
				sprintf(tmp_str,"%.2f",db_cmm.var.anlg.fValue);
			gtk_label_set_text(GTK_LABEL(result_lab[row][4]), pConvert=_toUtf8(tmp_str));
			G_SAFE_FREE(pConvert);
			
			if(result_pt[j].data_type==POL_TYPE||result_pt[j].data_type==SOE_TYPE)
				sprintf(tmp_str,"%d",db_cmm.var.ind.status.chan_fail);
			else
				sprintf(tmp_str,"%d",db_cmm.var.anlg.value.status.chan_fail);
			gtk_label_set_text(GTK_LABEL(result_lab[row][5]),tmp_str);
			
			if(result_pt[j].data_type==POL_TYPE||result_pt[j].data_type==SOE_TYPE)
				sprintf(tmp_str,"%d",db_cmm.var.ind.status.man_set);
			else
				sprintf(tmp_str,"%d",db_cmm.var.anlg.value.status.ctrl_block);
			gtk_label_set_text(GTK_LABEL(result_lab[row][6]),tmp_str);
			
			sprintf(tmp_str,"%d",db_cmm.fixed.iost.scanEnable);
			gtk_label_set_text(GTK_LABEL(result_lab[row][7]),tmp_str);
			
			sprintf(tmp_str,"%d",db_cmm.fixed.iost.almEnable);
			gtk_label_set_text(GTK_LABEL(result_lab[row][8]),tmp_str);
			
			sprintf(tmp_str,"%d",db_cmm.fixed.iost.almNoAck);
			gtk_label_set_text(GTK_LABEL(result_lab[row][9]),tmp_str);
		}
		printf("*****row=%d\n",row);  
		if(row<40)
		{          
            for(i=0;i<10;i++)
            {
                for(j=1;j<=row;j++)
				{  
					if(i!=0)
						gtk_widget_show (result_lab[j][i]); 
					gtk_widget_show(detail_btn[j]);
                }
                for(j=row+1;j<41;j++) 
				{
					gtk_widget_hide (result_lab[j][i]);
					gtk_widget_hide (detail_btn[j]);
                }
            }  
		}
		else
        {
            for(j=1;j<41;j++)
            {
                gtk_widget_show(detail_btn[j]);    
                for(i=0;i<10;i++)
                {
					if(i!=0)   
						gtk_widget_show (result_lab[j][i]);
                }
            }
		}
}

void
on_property_btn_toggled                     (GtkToggleButton *togglebutton,
											 gpointer         user_data)
{
    int i,j;
    int crt_n=0;
    GtkWidget /**property_btn,*/*opt_lab;
    char property_str[256],lab_str[256],old_str[256];
	gchar *pConvert=0;
	//int flag;
	
	//flag=FALSE;
	
    GetCrtNumberOfWgt ( GTK_WIDGET(togglebutton), &crt_n );
    if( crt_n < 0 )
		return ;
    
    i=(gint)user_data;    
    
    if(gtk_toggle_button_get_active(togglebutton))
    {
        /*add by hcl*/
		
		//if(Opt_item==OPT_ITEM_NUM)/*OPT_ITEM_NUM=4*/
		//{
		//flag=TRUE;
		//	gtk_toggle_button_set_active        (togglebutton,FALSE);
		//	return;
		//}
		if(selected_items[crt_n]>4)
			return;
		
		printf("active::i=%d is toggled\n",i);
		/* printf("com_property[%d]=%s\n",i,com_property[i]);
        property_btn = gtk_object_get_data(GTK_OBJECT(searchdialog[crt_n]),com_property[i]); */
		
        for(j=1;j<=4;j++)
        {    
            sprintf(lab_str,"opt%d_lab",j);
            opt_lab = gtk_object_get_data(GTK_OBJECT(searchdialog[crt_n]),lab_str);
            strcpy(old_str,gtk_label_get_text(GTK_LABEL(opt_lab)));
            strcpy(old_str, pConvert=_fromUtf8(old_str));
			G_SAFE_FREE(pConvert);
            printf("old_str=%s,lab_str=%s\n",old_str,lab_str);
			
            if(strcmp(old_str,lab_str)==0)  
            {    
				if(i<com_property_col)
                {                   
					
					//					if(i==3&&search_pt.data_type==ANA_TYPE)
					//						strcpy(property_str,OIX_CSTR_BLOCK);
					//					else 
					strcpy(property_str,com_property[i]);   
                }
                else
				{
					if(i==ANA_PROPERTY)
					{
						/* printf("i==ANA_PROPERTY=%d\n",ANA_PROPERTY1);*/
						strcpy(property_str,Ana_property[0]);
					}
					/* if(i==ANA_PROPERTY2)
					{
					printf("i==ANA_PROPERTY=%d\n",ANA_PROPERTY2);
					strcpy(property_str,Ana_property[1]);
				}*/
					if(i==POL_PROPERTY)
						strcpy(property_str,Pol_SOE_property[0]);
					if(i==IMP_PROPERTY)
						strcpy(property_str,Imp_property[0]); 
						/* if(i==CALC_PROPERTY)
						strcpy(property_str,Calc_property[0]);
                        if(i==OUTS_PROPERTY)
					strcpy(property_str,Outs_property[0]);*/
                }
                
                gtk_label_set_text(GTK_LABEL(opt_lab), pConvert=_toUtf8(_CS_(property_str)));
				G_SAFE_FREE(pConvert);
                strcpy(Optlabel_str[j-1],_CS_(property_str));
                strcpy(search_pt.property[j-1],_CS_(property_str));
				//                Opt_item ++;
                selected_items[crt_n]++;
				if(selected_items[crt_n]>=4)
				{
					int	k;
					for(k=0;k<property_btn_index.btn_num;k++)
						if(!gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(property_btn_index.btn[k])))
							gtk_widget_set_sensitive(property_btn_index.btn[k], FALSE);
				}
				
                break;
            }
            /*printf("property[%d]=%s\n",opt_item,search_pt.property[Opt_item]);*/
        }
    }
    else
    {		
        printf("i=%d is Untoggled\n",i);
        for(j=1;j<=4;j++)
        {    
            sprintf(lab_str,"opt%d_lab",j);
            opt_lab = gtk_object_get_data(GTK_OBJECT(searchdialog[crt_n]),lab_str);
            strcpy(old_str,gtk_label_get_text(GTK_LABEL(opt_lab)));
            strcpy(old_str, pConvert=_fromUtf8(old_str));
			G_SAFE_FREE(pConvert);
            printf("old_str=%s,lab_str=%s\n",old_str,lab_str);
            
			if(i<com_property_col)
            {
				
				strcpy(property_str,com_property[i]);  
            }
            else
            {
				if(i==ANA_PROPERTY)
					strcpy(property_str,Ana_property[0]);
				
				if(i==POL_PROPERTY)
					strcpy(property_str,Pol_SOE_property[0]);
				if(i==IMP_PROPERTY)
					strcpy(property_str,Imp_property[0]); 
					/*  if(i==CALC_PROPERTY)
					strcpy(property_str,Calc_property[0]);
					if(i==OUTS_PROPERTY)
				strcpy(property_str,Outs_property[0]);*/
            }
			printf("###old_str=%s,property_str=%s\n",old_str,_CS_(property_str));
            
            if(strcmp(old_str,_CS_(property_str))==0)  
            {               
                gtk_label_set_text(GTK_LABEL(opt_lab), pConvert=_toUtf8/*EX*/(lab_str));
				G_SAFE_FREE(pConvert);
                strcpy(Optlabel_str[j-1],"");
                strcpy(search_pt.property[j-1],"");
				//Opt_item --;
				if(selected_items[crt_n]==4)
				{
					int	k;
					for(k=0;k<property_btn_index.btn_num;k++)
						if(!gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(property_btn_index.btn[k])))
							gtk_widget_set_sensitive(property_btn_index.btn[k], TRUE);
				}
                selected_items[crt_n]--;
                break;
            }
        }
    }                     
}

void DspPropertyPage(int crt_n)
{
    int i,j,k=0,ANA_OUTA=0,POL_SOE=0,data_type[15];
    GtkWidget *com_property_btn,*private_property_btn[15];
    char private_property[20];    
	
	property_btn_index.btn_num=0;
	
	for(i=0;i<com_property_col;i++)
    {
        com_property_btn = gtk_object_get_data(GTK_OBJECT(searchdialog[crt_n]),com_property[i]);   
		//        if(search_pt.data_type==ANA_TYPE&&i==3)
		//            gtk_object_set(GTK_OBJECT(com_property_btn),"GtkButton::label",_toUtf8EX(OIX_CSTR_BLOCK),NULL); 
        gtk_widget_show(com_property_btn); 
		property_btn_index.btn[property_btn_index.btn_num++]= com_property_btn;
    } 
    
    com_property_btn = gtk_object_get_data(GTK_OBJECT(searchdialog[crt_n]),"table1"); 
    gtk_widget_show(com_property_btn);  
    
	for(i=1;i<MAX_DATATYPE_NUM;i++)
    {
        if((0x01 & (search_pt.data_type>>(i-1))))
        {
            data_type[k]=i;           
            k++;
        }
    }
    
    if(k==0)
    {        
        for(j=0;j<Ana_property_col;j++)
		{
            private_property_btn[j] = gtk_object_get_data(GTK_OBJECT(searchdialog[crt_n]),Ana_property[j]);         
            gtk_widget_hide(private_property_btn[j]);  
        }
        
        private_property_btn[0] = gtk_object_get_data(GTK_OBJECT(searchdialog[crt_n]),Imp_property[0]);         
        gtk_widget_hide(private_property_btn[0]); 
        private_property_btn[0] = gtk_object_get_data(GTK_OBJECT(searchdialog[crt_n]),Pol_SOE_property[0]);         
        gtk_widget_hide(private_property_btn[0]); 
        /*private_property_btn[0] = gtk_object_get_data(GTK_OBJECT(searchdialog[crt_n]),Calc_property[0]);         
        gtk_widget_hide(private_property_btn[0]); 
        private_property_btn[0] = gtk_object_get_data(GTK_OBJECT(searchdialog[crt_n]),Outs_property[0]);         
        gtk_widget_hide(private_property_btn[0]); */
        
		for(i=0;i<com_property_col;i++)
        {
            com_property_btn = gtk_object_get_data(GTK_OBJECT(searchdialog[crt_n]),com_property[i]); 
            gtk_widget_hide(com_property_btn);       
        }     
		
        com_property_btn = gtk_object_get_data(GTK_OBJECT(searchdialog[crt_n]),"table1"); 
        gtk_widget_hide(com_property_btn); 
    }
    
    if((0x01 & (search_pt.data_type>>(POL_TYPE-1)))==TRUE)
        POL_SOE++;
    if((0x01 & (search_pt.data_type>>(SOE_TYPE-1)))==TRUE)
        POL_SOE++;
    if((0x01 &(search_pt.data_type>>(OUTS_TYPE-1)))==TRUE)
        POL_SOE++;
    if((0x01 & (search_pt.data_type>>(OUTA_TYPE-1)))==TRUE)
        ANA_OUTA++;
    if((0x01 & (search_pt.data_type>>(ANA_TYPE-1)))==TRUE)
        ANA_OUTA++;
    
    for(j=0;j<k;j++)
    {
		if(data_type[j]==ANA_TYPE||data_type[j]==OUTA_TYPE)           
			strcpy(private_property,Ana_property[0]);      
		else if(data_type[j]==IMP_TYPE)            
			strcpy(private_property,Imp_property[0]);
		else if(data_type[j]==POL_TYPE || data_type[j]==SOE_TYPE|| data_type[j]==OUTS_TYPE||data_type[j]==SYSMSG_TYPE)
			strcpy(private_property,Pol_SOE_property[0]);
			/* else if(data_type[j]==CALC_TYPE)
			strcpy(private_property,Calc_property[0]);
			else if(data_type[j]==OUTS_TYPE)
		strcpy(private_property,Outs_property[0]);    */ 
		
		private_property_btn[j] = gtk_object_get_data(GTK_OBJECT(searchdialog[crt_n]),private_property); 
		property_btn_index.btn[property_btn_index.btn_num++]= private_property_btn[j];
		if(private_property_btn[j])
		{           
			if(k==1||(k==POL_SOE&&POL_SOE>1)||k==ANA_OUTA&&ANA_OUTA>1) 
                gtk_widget_show(private_property_btn[j]);             
			else           
				gtk_widget_hide(private_property_btn[j]); 
		}
		/* if(data_type[j]==ANA_TYPE)  
		{
		strcpy(private_property,Ana_property[1]);                
		private_property_btn[j] = gtk_object_get_data(GTK_OBJECT(searchdialog[crt_n]),private_property);                 
		if(k==1)
		gtk_widget_show(private_property_btn[j]);  
		else
		gtk_widget_hide(private_property_btn[j]); 
	}       */
	}       
}

void
on_datatype_btn_toggled                     (GtkToggleButton *togglebutton,
											 gpointer         user_data)
{
    int i;
    int crt_n=0;
	
    GetCrtNumberOfWgt ( GTK_WIDGET(togglebutton), &crt_n );
    if( crt_n < 0 )
		return ;
    
    i=(gint)user_data;
    
    if(gtk_toggle_button_get_active(togglebutton))
	{
        printf("data_type=%d is %d\n",(gint)user_data,gtk_toggle_button_get_active(togglebutton));
        search_pt.data_type = (search_pt.data_type)  | (1<<(i-1)) ;  /*  Set bit N */
    }
    else
	{
        printf("data_type=%d is %d\n",(gint)user_data,gtk_toggle_button_get_active(togglebutton));
        search_pt.data_type =(search_pt.data_type) & (~(1<<(i-1))) ;   /*  Clear bit N */
    }
    
    DspPropertyPage(crt_n);                                  
}


int SearchData() 
{
	int i,j,m,/*row,col,*/pt_num=0,grp_num,entry_num;
	POINTER point;
	DMS_COMMON db_cmm;
	BOOL result=FALSE;
	if(search_pt.dev_id==0)/* all lcu*/
	{
		if(-1==GetGroupNumById((UCHAR)search_pt.stn_id, &grp_num))
			return -1;
		
		for(i=1;i<=grp_num;i++)
		{
			for(j=1;j<MAX_DATATYPE_NUM;j++)
			{
				if((0x01 & (search_pt.data_type>>(j-1))))
				{
					if(-1==GetEntryNumById((UCHAR)search_pt.stn_id,(UCHAR)i, (UCHAR)j, &entry_num))
						continue;
					printf("dev_id=%d,data_type=%d,entry_num=%d\n",i,j,entry_num);
					point.stn_id = search_pt.stn_id;
					point.dev_id = i;
					point.data_type=j;
					for(m=0;m<entry_num;m++)
					{
						point.pt_id	= m;
						result = TRUE;
						if ( ReadEntryById (&point, &db_cmm ) == -1)		
							continue;
						GetPropertyOption(db_cmm,&result); 
						if(result==TRUE)
						{     
							result_pt[pt_num] = point;                       
							pt_num++;  
						}
					}
				}
			}
		}
	}
	else  /*point to certain stn*/
	{
		for(i=1;i<MAX_DATATYPE_NUM;i++)
		{     
			if((0x01 & (search_pt.data_type>>(i-1))))
			{
				if(-1==GetEntryNumById((UCHAR)search_pt.stn_id, (UCHAR)search_pt.dev_id, (UCHAR)i, &entry_num))
					continue;
				point.stn_id = search_pt.stn_id;
				point.dev_id = search_pt.dev_id;
				point.data_type=i;
				printf("stn_id=%d,dev_id=%d,data_type=%d,entry_num=%d\n",search_pt.stn_id,search_pt.dev_id,i,entry_num);
				for(j=0;j<entry_num;j++)
				{
					point.pt_id	= j;
					result = TRUE;
					
					if ( ReadEntryById (&point, &db_cmm ) == -1)		
						continue;
					
					GetPropertyOption(db_cmm,&result); 
					
					if(result==TRUE)
					{     
						result_pt[pt_num] = point;                       
						pt_num++; 
					}
				}               
			}            
		}       
	}
	return pt_num ; 
}

GtkWidget *DspResult(int crt_n,int pt_num,int type)
{
	GtkWidget *window1;
	GtkWidget *table1;
	GtkWidget *alm_ack;
	GtkWidget *scan_enable;
	GtkWidget *man_set;
	GtkWidget *data_qulity;
	GtkWidget *rt_value;
	GtkWidget *noupdate;
	GtkWidget *LongName;
	GtkWidget *entry_name;
	GtkWidget *addr;
	GtkWidget *alm_enable;
	int /*i,j,m,*/row,col/*,grp_num,entry_num*/;
	char lab_title[60];
//	POINTER point;
//	DMS_COMMON db_cmm;
	BOOL result=TRUE;
	GtkWidget *lab[41][10];
	GtkWidget *exit_btn;
	GtkWidget *page_up;
	GtkWidget *page_down; 
	GtkWidget *detail_btn[40];
	gchar *pConvert=0;
	
// 	if  ((pt_num=SearchData()) <=0)
// 	{
// 		PopupMessageBox( searchdialog[crt_n],(MSG_NUM_RESULT_IS_ZERO)) ; //"Number of results is zero!!!");
// 		return (void*) NULL ; 
// 		
// 	}
	window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
if (type==1)
{
	gtk_window_set_title (GTK_WINDOW (window1), pConvert=_toUtf8EX(OIX_STR_RELATEINFO));
	G_SAFE_FREE(pConvert);
} 
else
{
		gtk_window_set_title (GTK_WINDOW (window1), pConvert=_toUtf8EX(OIX_STR_SEARCH));
		G_SAFE_FREE(pConvert);
}

	
	gtk_window_set_transient_for(GTK_WINDOW(window1), GTK_WINDOW(main_w[crt_n]));
	gtk_widget_show (window1);
	gtk_widget_set_usize(GTK_WIDGET(window1), 1200, -1);
	
	table1 = gtk_table_new (40, 11, FALSE);
	gtk_widget_show (table1);
	gtk_container_add (GTK_CONTAINER (window1), table1);
	gtk_container_set_border_width (GTK_CONTAINER (table1), 0);
	gtk_table_set_row_spacings (GTK_TABLE (table1), 1);
	gtk_table_set_col_spacings (GTK_TABLE (table1), 1);
	
	gtk_table_set_col_spacing (GTK_TABLE (table1),1, 20);  
    
	
	alm_ack = gtk_label_new (pConvert=_toUtf8EX(OIX_CSTR_AlarmNoAck));
	G_SAFE_FREE(pConvert);
	gtk_widget_show (alm_ack);
	gtk_table_attach (GTK_TABLE (table1), alm_ack, 9, 10, 0, 1,
		(GtkAttachOptions) (GTK_EXPAND),
		(GtkAttachOptions) (0), 0, 0);
	gtk_label_set_line_wrap (GTK_LABEL (alm_ack), TRUE);
	gtk_misc_set_alignment (GTK_MISC (alm_ack), 0, 0.5);
	gtk_misc_set_padding (GTK_MISC (alm_ack), 5, 5);
	
	scan_enable = gtk_label_new (pConvert=_toUtf8EX(OIX_CSTR_ScanEnable));
	G_SAFE_FREE(pConvert);
	gtk_widget_show (scan_enable);
	gtk_table_attach (GTK_TABLE (table1), scan_enable, 7, 8, 0, 1,
		(GtkAttachOptions) (GTK_EXPAND),
		(GtkAttachOptions) (0), 0, 0);
	gtk_misc_set_alignment (GTK_MISC (scan_enable), 0, 0.5);
	gtk_misc_set_padding (GTK_MISC (scan_enable), 5, 5);
	
	if(search_pt.data_type==ANA_TYPE)
	{
		man_set = gtk_label_new (pConvert=_toUtf8EX(OIX_CSTR_BLOCK));
		G_SAFE_FREE(pConvert);
	}
	else
	{
		man_set = gtk_label_new (pConvert=_toUtf8EX(OIX_CSTR_MAN_SET));
		G_SAFE_FREE(pConvert);
	}
	gtk_widget_show (man_set);
	gtk_table_attach (GTK_TABLE (table1), man_set, 6, 7, 0, 1,
		(GtkAttachOptions) (GTK_EXPAND),
		(GtkAttachOptions) (0), 0, 0);
	gtk_misc_set_alignment (GTK_MISC (man_set), 0, 0.5);
	gtk_misc_set_padding (GTK_MISC (man_set), 5, 5);
	
	data_qulity = gtk_label_new (pConvert=_toUtf8EX(OIX_STR_DATA_QUALITY));
	G_SAFE_FREE(pConvert);
	gtk_widget_show (data_qulity);
	gtk_table_attach (GTK_TABLE (table1), data_qulity, 5, 6, 0, 1,
		(GtkAttachOptions) (GTK_EXPAND),
		(GtkAttachOptions) (0), 0, 0);
	gtk_misc_set_alignment (GTK_MISC (data_qulity), 0, 0.5);
	gtk_misc_set_padding (GTK_MISC (data_qulity), 5, 5);
	
	rt_value = gtk_label_new (pConvert=_toUtf8EX(OIX_CSTR_RT_VALUE));
	G_SAFE_FREE(pConvert);
	gtk_widget_show (rt_value);
	gtk_table_attach (GTK_TABLE (table1), rt_value, 4, 5, 0, 1,
		(GtkAttachOptions) (GTK_EXPAND),
		(GtkAttachOptions) (0), 0, 0);
	gtk_misc_set_alignment (GTK_MISC (rt_value), 0, 0.5);
	gtk_misc_set_padding (GTK_MISC (rt_value), 5, 5);
	
	noupdate = gtk_label_new (pConvert=_toUtf8EX(OIX_CSTR_NO_UPDATE));
	G_SAFE_FREE(pConvert);
	gtk_widget_show (noupdate);
	gtk_table_attach (GTK_TABLE (table1), noupdate, 3, 4, 0, 1,
		(GtkAttachOptions) (GTK_EXPAND),
		(GtkAttachOptions) (0), 0, 0);
	gtk_misc_set_alignment (GTK_MISC (noupdate), 0, 0.5);
	gtk_misc_set_padding (GTK_MISC (noupdate), 5, 5);
	
	LongName = gtk_label_new (pConvert=_toUtf8EX(OIX_CSTR_LONGNAME));
	G_SAFE_FREE(pConvert);
	gtk_widget_show (LongName);
	gtk_table_attach (GTK_TABLE (table1), LongName, 2, 3, 0, 1,
		(GtkAttachOptions) (GTK_EXPAND),
		(GtkAttachOptions) (0), 0, 0);
	gtk_misc_set_alignment (GTK_MISC (LongName), 0, 0);
	gtk_misc_set_padding (GTK_MISC (LongName), 5, 5);
	
	entry_name = gtk_label_new (pConvert=_toUtf8EX(OIX_CSTR_NAME));
	G_SAFE_FREE(pConvert);
	gtk_widget_show (entry_name);
	gtk_table_attach (GTK_TABLE (table1), entry_name, 1, 2, 0, 1,
		(GtkAttachOptions) (GTK_EXPAND),
		(GtkAttachOptions) (0), 0, 0);
	gtk_misc_set_alignment (GTK_MISC (entry_name), 0, 0);
	gtk_misc_set_padding (GTK_MISC (entry_name), 3, 3);
	
	addr = gtk_label_new ("I/O");
	/* gtk_widget_show (addr);*/
	gtk_table_attach (GTK_TABLE (table1), addr, 0, 1, 0, 1,
		(GtkAttachOptions) (GTK_EXPAND),
		(GtkAttachOptions) (0), 0, 0);
	gtk_misc_set_alignment (GTK_MISC (addr), 0, 0.5);
	gtk_misc_set_padding (GTK_MISC (addr), 0, 0);
	
	alm_enable = gtk_label_new (pConvert=_toUtf8EX(OIX_CSTR_AlarmEnable));
	G_SAFE_FREE(pConvert);
	gtk_widget_show (alm_enable);
	gtk_table_attach (GTK_TABLE (table1), alm_enable, 8, 9, 0, 1,
		(GtkAttachOptions) (GTK_EXPAND),
		(GtkAttachOptions) (0), 0, 0);
	gtk_misc_set_alignment (GTK_MISC (alm_enable), 0, 0.5);
	gtk_misc_set_padding (GTK_MISC (alm_enable), 5, 5);
	
	for(col=0;col<10;col++)
		for(row=1;row<=40;row++)
		{
			sprintf(lab_title,"lab%d",(row-1)*10+col+1);
			lab[row][col] = gtk_label_new (lab_title);
			gtk_widget_hide (lab[row][col]);
			if(col!=2)
				gtk_table_attach (GTK_TABLE (table1), lab[row][col], col, col+1, row, row+1,
				(GtkAttachOptions) (GTK_EXPAND),(GtkAttachOptions) (0), 0, 0);
			else
				gtk_table_attach (GTK_TABLE (table1), lab[row][col], col, col+1, row, row+1,
				(GtkAttachOptions) (GTK_FILL),(GtkAttachOptions) (0), 0, 0);
			gtk_misc_set_alignment (GTK_MISC (lab[row][col]), 0, 0.5);
			gtk_misc_set_padding (GTK_MISC (lab[row][col]), 0, 1);
			GLADE_HOOKUP_OBJECT (window1, lab[row][col], lab_title);
		}
		
		for(row=1;row<=40;row++)
		{
			sprintf(lab_title,"Detail%d",row);
			detail_btn[row] = gtk_button_new_with_mnemonic (pConvert=_toUtf8EX(OIX_CSTR_MESSAGE));
			G_SAFE_FREE(pConvert);
			gtk_widget_set_usize(GTK_WIDGET(detail_btn[row]), 60, 22);
			/* gtk_widget_show (detail_btn[row]);*/
			gtk_table_attach (GTK_TABLE (table1), detail_btn[row], 0, 1, row, row+1,
				(GtkAttachOptions)(GTK_FILL),
				(GtkAttachOptions) (0), 0, 0);   
			GLADE_HOOKUP_OBJECT (window1, detail_btn[row], lab_title);
			g_signal_connect ((gpointer) detail_btn[row], "pressed",
				G_CALLBACK (on_detail_btn_pressed),
				GINT_TO_POINTER(row));
		}
		
		exit_btn = gtk_button_new_with_mnemonic (pConvert=_toUtf8EX(OIX_CSTR_EXIT));
		G_SAFE_FREE(pConvert);
		gtk_widget_show (exit_btn);
		gtk_table_attach (GTK_TABLE (table1), exit_btn, 2, 3, 41, 42,
			(GtkAttachOptions) (GTK_EXPAND),
			(GtkAttachOptions) (0), 0, 0);
		gtk_container_set_border_width (GTK_CONTAINER (exit_btn), 5);
		
		page_up = gtk_button_new_with_mnemonic (pConvert=_toUtf8EX(OIX_CSTR_PAGE_UP));
		G_SAFE_FREE(pConvert);
		gtk_widget_show (page_up);
		gtk_table_attach (GTK_TABLE (table1), page_up, 5, 6, 41, 42,
			(GtkAttachOptions) (GTK_FILL),
			(GtkAttachOptions) (0), 0, 0);
		gtk_container_set_border_width (GTK_CONTAINER (page_up), 5);
		
		page_down = gtk_button_new_with_mnemonic (pConvert=_toUtf8EX(OIX_CSTR_PAGE_DOWN));
		G_SAFE_FREE(pConvert);
		gtk_widget_show (page_down);
		gtk_table_attach (GTK_TABLE (table1), page_down, 7, 8, 41, 42,
			(GtkAttachOptions) (GTK_FILL),
			(GtkAttachOptions) (0), 0, 0);
		gtk_container_set_border_width (GTK_CONTAINER (page_down), 5);  
		
		/* Store pointers to all widgets, for use by lookup_widget(). */
		GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
		GLADE_HOOKUP_OBJECT (window1, table1, "table1");
		GLADE_HOOKUP_OBJECT (window1, alm_ack, "alm_ack");
		GLADE_HOOKUP_OBJECT (window1, scan_enable, "scan_enable");
		GLADE_HOOKUP_OBJECT (window1, man_set, "man_set");
		GLADE_HOOKUP_OBJECT (window1, data_qulity, "data_qulity");
		GLADE_HOOKUP_OBJECT (window1, rt_value, "rt_value");
		GLADE_HOOKUP_OBJECT (window1, noupdate, "noupdate");
		GLADE_HOOKUP_OBJECT (window1, LongName, "LongName");
		GLADE_HOOKUP_OBJECT (window1, entry_name, "entry_name");
		GLADE_HOOKUP_OBJECT (window1, addr, "addr");
		GLADE_HOOKUP_OBJECT (window1, alm_enable, "alm_enable");  
		
		////////////////////////////////////////////////////////////////////
		//		old code here ;
		//////////////////////////////////////////////////////////////////
		cur_search_page.page_no=0;
		cur_search_page.page_num = pt_num/40 +1;
		cur_search_page.start_id = 0;
		
		cur_search_page.end_id = pt_num;
		
		printf("cur_search_page.page_num=%d,start_id=%d,pt_num=%d\n",cur_search_page.page_num,cur_search_page.start_id,pt_num);
		
		g_signal_connect (GTK_OBJECT (window1), "destroy",
			GTK_SIGNAL_FUNC (on_destroy_search_result_win), (gpointer)crt_n);
		
		g_signal_connect ((gpointer) exit_btn, "pressed",
			G_CALLBACK (on_exit_btn_pressed),
			window1);
		g_signal_connect ((gpointer) page_up, "pressed",
			G_CALLBACK (on_page_up_pressed),
			(gpointer)pt_num);
		g_signal_connect ((gpointer) page_down, "pressed",
			G_CALLBACK (on_page_down_pressed),
			(gpointer)pt_num);
		return window1;  
}

void GetPropertyOption(DMS_COMMON db_cmm,BOOL *opt_meet)
{
    int k;
    int real_val,obj_val;
    float real_fval,obj_fval;
    char cmpstring[50],obj_str[50];
	char  LongNamerStr1[128];
    
    *opt_meet = TRUE;
    for(k=0;k<OPT_ITEM_NUM;k++)
    {    
		if(*opt_meet==FALSE)
            break;
		
		if(strstr(search_pt.property[k],"_lab")!=NULL)
            continue;       
		
		if(strstr(search_pt.data.str[k],"empty")!=NULL)
			continue;

		if(strcmp(search_pt.property[k],_CS_(OIX_CSTR_RT_VALUE))==0
            ||strcmp(search_pt.property[k],_CS_(OIX_CSTR_CALC_VALUE))==0)                  
		{
			obj_fval=(float)(atof(search_pt.data.str[k]));
			real_fval = db_cmm.var.anlg.fValue;
			if(strcmp(search_pt.property[k],_CS_(OIX_CSTR_CALC_VALUE))==0)                  
				real_fval = db_cmm.var.calc.fValue; 
			
			*opt_meet=Cmpfvalue(real_fval,obj_fval,k);
		}
		else if(strcmp(search_pt.property[k],_CS_(OIX_CSTR_LONGNAME))==0
			||strcmp(search_pt.property[k],_CS_(OIX_CSTR_NAME))==0
			||strcmp(search_pt.property[k],_CS_(OIX_CSTR_UNIT_NO))==0
			||strcmp(search_pt.property[k],_CS_(OIX_CSTR_SLOT))==0
			||strcmp(search_pt.property[k],_CS_(OIX_CSTR_CHANNEL))==0)
		{
			strcpy(obj_str,search_pt.data.str[k]);
			strcpy(cmpstring,"") ; 
			
			if(strcmp(search_pt.property[k],_CS_(OIX_CSTR_LONGNAME))==0)  
			{
				GetEntryLongnameById (&db_cmm.point,LongNamerStr1 );
				strcpy(cmpstring,LongNamerStr1);
			}
			if(strcmp(search_pt.property[k],_CS_(OIX_CSTR_NAME))==0)                  
                strcpy(cmpstring,db_cmm.fixed.entryName);
			if(strcmp(search_pt.property[k],_CS_(OIX_CSTR_UNIT_NO))==0)
                strcpy(cmpstring,db_cmm.fixed.hard_addr.unit_no);
			if(strcmp(search_pt.property[k],_CS_(OIX_CSTR_SLOT))==0) 
				strcpy(cmpstring,db_cmm.fixed.hard_addr.slot_no);
			if(strcmp(search_pt.property[k],_CS_(OIX_CSTR_CHANNEL))==0)
				strcpy(cmpstring,db_cmm.fixed.hard_addr.channel_no);
            if (strlen(cmpstring)>0)
				*opt_meet=CmpString(cmpstring,obj_str);
			else
				*opt_meet=FALSE  ; 
		}
		else
		{ //判断实时库点属性 状态
			obj_val = atoi(search_pt.data.str[k]);
			real_val = -32767 ; 
            if(strcmp(search_pt.property[k],_CS_(OIX_STR_FAULT))==0)                  
				real_val = db_cmm.fixed.ioattr.fault;          
            if(strcmp(search_pt.property[k],_CS_(OIX_STR_FAIL))==0)
				real_val =db_cmm.fixed.ioattr.fail; 
            if(strcmp(search_pt.property[k],_CS_(OIX_CSTR_ScanEnable))==0)                  
				real_val = db_cmm.fixed.iost.scanEnable;
            if(strcmp(search_pt.property[k],_CS_(OIX_CSTR_AlarmEnable))==0)                  
				real_val = db_cmm.fixed.iost.almEnable; 
            if(strcmp(search_pt.property[k],_CS_(OIX_CSTR_AlarmNoAck))==0)                  
				real_val = db_cmm.fixed.iost.almNoAck; 
            if(strcmp(search_pt.property[k],_CS_(OIX_STR_CTRL_LOCK))==0)                  
				real_val = db_cmm.fixed.iost.ctrlLock; 
            if(strcmp(search_pt.property[k],_CS_(OIX_CSTR_NO_UPDATE))==0)                  
				real_val = db_cmm.fixed.iost.noUpdate; 
            if(strcmp(search_pt.property[k],_CS_(OIX_CSTR_ALM_REPEAT))==0)                  
				real_val = db_cmm.fixed.iost.almRepeat;
            if(strcmp(search_pt.property[k],_CS_(OIX_STR_ACCUM))==0)                  
				real_val =(int)( db_cmm.var.imp.entry.d_accum);
            if(strcmp(search_pt.property[k],_CS_(OIX_CSTR_RT_STATE))==0)                  
				real_val = db_cmm.var.ind.status.rt_state;
			if(strcmp(search_pt.property[k],_CS_(OIX_CSTR_MAN_SET_OR_BLOCK))==0)   //wzgOIX_CSTR_MAN_SET 
			{
				if(db_cmm.point.data_type==ANA_TYPE || db_cmm.point.data_type==OUTA_TYPE
					|| db_cmm.point.data_type==PARAM_TYPE)
					real_val =db_cmm.var.anlg.value.status.ctrl_block;  
				else
					real_val = db_cmm.var.ind.status.man_set;
			}
			if(strcmp(search_pt.property[k],_CS_(OIX_CSTR_BLOCK))==0)
			{
				real_val =db_cmm.var.anlg.value.status.ctrl_block;
			}
			if(strcmp(search_pt.property[k],_CS_(OIX_STR_DATA_QUALITY))==0) 
			{
				if(db_cmm.point.data_type ==ANA_TYPE||db_cmm.point.data_type ==OUTA_TYPE)
                    real_val =db_cmm.var.anlg.value.status.chan_fail;
				else if(db_cmm.point.data_type ==IMP_TYPE)
					real_val =db_cmm.var.ind.status.chan_fail;
				else
					real_val =db_cmm.var.imp.entry.status.chan_fail;
			}			
			if (	real_val != -32767)
				*opt_meet=CmpInt(real_val,obj_val,k);   
			else
				*opt_meet=FALSE ; 
		}
	}
}

void
on_ok_btn_pressed                      (GtkButton       *button,
                                        gpointer         user_data)
{
    int i,j;
    GtkWidget *opt_lab[OPT_ITEM_NUM],*OptEntry[OPT_ITEM_NUM],*OprComb[OPT_ITEM_NUM]/*,*dev_comb*/;
    char lab_str[OPT_ITEM_NUM][20];
    int crt_n=0;
	int pt_num=0;
	gchar *pConvert=0;
	
    GetCrtNumberOfWgt ( GTK_WIDGET(button), &crt_n );
    if( crt_n < 0 )
		return ;
	if (search_pt.stn_id==0)
	{
		PopupMessageBox(searchdialog[crt_n], (MSG_MUST_SEL_STATION_FIRST));  //"MSG_MUST_SEL_STATION_FIRST" 必须先选择一个电站
        return;
	}
	
	
    for(i=0;i<OPT_ITEM_NUM;i++)
    {
        sprintf(lab_str[i],"opt%d_lab",i+1);
        opt_lab[i] = gtk_object_get_data(GTK_OBJECT(searchdialog[crt_n]),lab_str[i]);
        strcpy(search_pt.property[i],gtk_label_get_text(GTK_LABEL(opt_lab[i])));
        strcpy(search_pt.property[i], pConvert=_fromUtf8(search_pt.property[i]));
		G_SAFE_FREE(pConvert);
        
        OprComb[i]=gtk_object_get_data(GTK_OBJECT(searchdialog[crt_n]),OptComb_name[i]);
        j= gtk_combo_box_get_active(GTK_COMBO_BOX(OprComb[i]));
        strcpy(search_pt.opr[i],opr_name[j]);     
        
        OptEntry[i]=gtk_object_get_data(GTK_OBJECT(searchdialog[crt_n]),Optentry_name[i]);
        strcpy(search_pt.data.str[i],gtk_entry_get_text(GTK_ENTRY(OptEntry[i])));
        strcpy(search_pt.data.str[i], pConvert=_fromUtf8(search_pt.data.str[i]));
		G_SAFE_FREE(pConvert);
        printf("search property=%s, opr=%s,str=%s\n",search_pt.property[i],search_pt.opr[i],search_pt.data.str[i]);
    }
	/*first delete old result win!!*/
	if (SearchResultWin[crt_n])
	{
		gtk_widget_destroy(SearchResultWin[crt_n]) ;
		SearchResultWin[crt_n]= (void *)NULL ;  
	}
	if  ((pt_num=SearchData()) <=0)
	{
		PopupMessageBox( searchdialog[crt_n],(MSG_NUM_RESULT_IS_ZERO)) ; //"Number of results is zero!!!");
		return  ; 
		
	}
	if (SearchResultWin[crt_n]=DspResult(crt_n,pt_num,0))
		DspSearchPage(crt_n,cur_search_page.end_id);
	
}

void
on_cancel_btn_clicked                  (GtkButton       *button,
                                        gpointer         user_data)
{
	gtk_widget_destroy(user_data);
}






GtkWidget* CreateStnFilterMenu(int crt_n) 
{
	char	stn_comment[STATION_COMMENT_SIZE];
	int		stn_num,index,	MenuPointer;
	GtkWidget *optionmenu, *menu,*items;
	int		menu_index, active_index;
	gchar *pConvert=0;
	UCHAR	stn_id;
	menu =gtk_menu_new();	
	
	GetStationNum(&stn_num);
	stn_id= 0;
	menu_index= active_index= 0;
	items = gtk_menu_item_new_with_label(pConvert=_toUtf8EX("OIX_ALL_STATION"));  //OIX_ALL_STATION  所有厂站
	G_SAFE_FREE(pConvert);
	gtk_widget_show(items)  ; 
	gtk_container_add(GTK_CONTAINER(menu),items);
	MenuPointer=getMenuDataPointer(crt_n,0);
	gtk_signal_connect(GTK_OBJECT(items), "activate", GTK_SIGNAL_FUNC(GetStnFilterSelect), (gpointer)MenuPointer);

	for(index=1; index<=stn_num; index++) 
	{
		UCHAR	stn_id;
		if(-1==GetStnIdByIndex(index, &stn_id))
			continue;
		
		if( GetStnCommentById((UCHAR)stn_id,(char*)( stn_comment))==-1 )
			continue;
		
		items = gtk_menu_item_new_with_label(pConvert=_toUtf8(stn_comment));
		G_SAFE_FREE(pConvert);
		gtk_widget_show(items)  ; 
		gtk_container_add(GTK_CONTAINER(menu),items);

		MenuPointer=getMenuDataPointer(crt_n,stn_id);
		gtk_signal_connect(GTK_OBJECT(items), "activate", GTK_SIGNAL_FUNC(GetStnFilterSelect), (gpointer)MenuPointer);
		
		if(stn_id==db_tab_window_info[crt_n].select_pt.stn_id)
			active_index= menu_index;
		menu_index++;
	}
		
	
	optionmenu = gtk_option_menu_new();
    gtk_option_menu_set_menu(GTK_OPTION_MENU(optionmenu),menu);
	gtk_option_menu_set_history(GTK_OPTION_MENU(optionmenu), active_index);

	return optionmenu;

}




GtkWidget* CreateDevFilterMenu(int crt_n) 
{
//	char	dev_comment[GROUP_COMMENT_SIZE];
//	UCHAR	stn_id, dev_id*;
//	int		i,grp_num;
	GtkWidget *optionmenu, *menu,*items;
//	int		menu_index, active_index;
	int MenuPointer;
	gchar *pConvert=0;
	
	menu =gtk_menu_new();
	gtk_widget_set_usize(menu, 130, -1);
	
	items = gtk_menu_item_new_with_label(pConvert=_toUtf8EX(OIX_ALL_DEVICES));	 
	G_SAFE_FREE(pConvert);
	gtk_container_add(GTK_CONTAINER(menu),items);
	MenuPointer=getMenuDataPointer(crt_n,0);
	gtk_signal_connect(GTK_OBJECT(items), "activate", GTK_SIGNAL_FUNC(GetDevFilterSelect), (gpointer)MenuPointer);
	
	optionmenu = gtk_option_menu_new();
	gtk_option_menu_set_menu(GTK_OPTION_MENU(optionmenu),menu);
	//	gtk_option_menu_set_history(GTK_OPTION_MENU(optionmenu), active_index); 
	return optionmenu;
}
/**/

GtkWidget*
create_search_window (GtkWidget *parent,int crt_n)
{
	GtkWidget *window1;
	GtkWidget *hbox1;
	GtkWidget *vbox1;
	GtkWidget *hbox2;
	GtkWidget *stn_filter_combox;   //chichi
	GtkWidget *dev_filter_combox;
	GtkWidget *ana_btn;
	GtkWidget *pol_btn;
	GtkWidget *soe_btn;
	GtkWidget *imp_btn;
	/* GtkWidget *calc_btn;*/
	/*GtkWidget *chara_btn;*/
	GtkWidget *outa_btn;
	GtkWidget *outs_btn;
	GtkWidget *sysmsg_btn;
	/*GtkWidget *curve_btn;
	GtkWidget *obj_btn;*/
	GtkWidget *frame1;
	/*GtkWidget *alignment1;*/
	GtkWidget *hbox3;
	/*GtkWidget *result_btn;*/
	GtkWidget *ok_btn;
	GtkWidget *cancel_btn;
	GtkWidget *vbox2;
	/*GtkWidget *drawingarea1;*/
	GtkWidget *table1;
	GtkWidget *opt1_lab;
	GtkWidget *opt2_lab;
	GtkWidget *opt3_lab;
	GtkWidget *opt4_lab;
	GtkWidget *opt1_comb;
	GtkWidget *opt1_entry;
	GtkWidget *opt2_entry;
	GtkWidget *opt3_entry;
	GtkWidget *opt4_entry;
	GtkWidget *opt2_comb;
	GtkWidget *opt3_comb;
	GtkWidget *opt4_comb; 
	
	GtkWidget *hbox5,*vbox4,*vbox5,*property_btn[20],
		*ana_property_btn[Ana_property_col],*pol_property_btn,
		*imp_property_btn/* *calc_property_btn,*outs_property_btn*/;
	char  recordTpyeName[100];
//	char	dev_comment[GROUP_COMMENT_SIZE];
	int	i/*,grp_num*/;

	gchar *pConvert=0;
	
	search_pt.stn_id =0;
	search_pt.dev_id =0;
	search_pt.data_type = 0x0;
	selected_items[crt_n]=0;
	
	window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
	gtk_window_set_title(GTK_WINDOW(window1), pConvert=_toUtf8EX(OIX_STR_SEARCH));
	G_SAFE_FREE(pConvert);
	gtk_window_set_transient_for(GTK_WINDOW(window1), GTK_WINDOW(parent));

	//gtk_widget_set_name (window1,"OIX_STR_SEARCH");
	gtk_widget_show (window1);
	
	hbox1 = gtk_hbox_new (FALSE, 0);
	gtk_widget_show (hbox1);
	gtk_container_add (GTK_CONTAINER (window1), hbox1);
	
	vbox1 = gtk_vbox_new (FALSE, 0);
	gtk_box_pack_start (GTK_BOX (hbox1), vbox1, FALSE, FALSE, 0);
	gtk_widget_set_size_request (vbox1, VBOX1_WIDTH, BOX_HEIGHT);
	gtk_widget_show (vbox1);
	
	hbox2 = gtk_hbox_new (FALSE, 0);
	gtk_widget_show (hbox2);
	gtk_box_pack_start (GTK_BOX (vbox1), hbox2, FALSE, FALSE, 0);
	// chichi
	stn_filter_combox = CreateStnFilterMenu(crt_n);
	gtk_widget_show (stn_filter_combox);
	gtk_box_pack_start (GTK_BOX (hbox2), stn_filter_combox, FALSE, FALSE, 0);
	gtk_widget_set_size_request (stn_filter_combox, 80, 40);
	gtk_container_set_border_width (GTK_CONTAINER (stn_filter_combox), 5);  /**/
    
	////////////////////////////////dev menu!!!////////////////////////////////////////////////////
	dev_filter_combox = CreateDevFilterMenu (crt_n);
	gtk_widget_show (dev_filter_combox);
	gtk_box_pack_start (GTK_BOX (hbox2), dev_filter_combox, FALSE, FALSE, 0);
	gtk_container_set_border_width (GTK_CONTAINER (dev_filter_combox), 5);
	
	// 	gtk_combo_box_set_active(GTK_COMBO_BOX (dev_filter_combox),0);
	
	/////////////////////////////////////////////////////////////////////////////////////////////////////////
	if(GetRecLongnameByType( 1, recordTpyeName )==-1)
		strcpy(recordTpyeName ,"Undefine");
	ana_btn = gtk_check_button_new_with_mnemonic (pConvert=_toUtf8(recordTpyeName));
	G_SAFE_FREE(pConvert);
	gtk_widget_show (ana_btn);
	gtk_box_pack_start (GTK_BOX (vbox1), ana_btn, FALSE, FALSE, 0);
	gtk_widget_set_size_request (ana_btn, 5, -1);
	gtk_container_set_border_width (GTK_CONTAINER (ana_btn), 5);
	
	
	if(GetRecLongnameByType( 5, recordTpyeName )==-1)
		strcpy(recordTpyeName ,"Undefine");
	
	pol_btn = gtk_check_button_new_with_mnemonic (pConvert=_toUtf8(recordTpyeName));
	G_SAFE_FREE(pConvert);
	gtk_widget_show (pol_btn);
	gtk_box_pack_start (GTK_BOX (vbox1), pol_btn, FALSE, FALSE, 0);
	gtk_container_set_border_width (GTK_CONTAINER (pol_btn), 5);
	
	
	if(GetRecLongnameByType( 4, recordTpyeName )==-1)
		strcpy(recordTpyeName ,"Undefine");
	soe_btn = gtk_check_button_new_with_mnemonic (pConvert=_toUtf8(recordTpyeName));
	G_SAFE_FREE(pConvert);
	gtk_widget_show (soe_btn);
	gtk_box_pack_start (GTK_BOX (vbox1), soe_btn, FALSE, FALSE, 0);
	gtk_container_set_border_width (GTK_CONTAINER (soe_btn), 5);
	
	
	if(GetRecLongnameByType( 3, recordTpyeName )==-1)
		strcpy(recordTpyeName ,"Undefine");
	imp_btn = gtk_check_button_new_with_mnemonic (pConvert=_toUtf8(recordTpyeName));
	G_SAFE_FREE(pConvert);
	gtk_widget_show (imp_btn);
	gtk_box_pack_start (GTK_BOX (vbox1), imp_btn, FALSE, FALSE, 0);
	gtk_container_set_border_width (GTK_CONTAINER (imp_btn), 5);
	
	/* calc_btn = gtk_check_button_new_with_mnemonic ("\350\256\241\347\256\227\351\207\217");
	gtk_widget_show (calc_btn);
	gtk_box_pack_start (GTK_BOX (vbox1), calc_btn, FALSE, FALSE, 0);
	gtk_container_set_border_width (GTK_CONTAINER (calc_btn), 5);
	
	  chara_btn = gtk_check_button_new_with_mnemonic ("\346\270\251\345\272\246\347\211\271\345\276\201\345\200\274");
	  gtk_widget_show (chara_btn);
	  gtk_box_pack_start (GTK_BOX (vbox1), chara_btn, FALSE, FALSE, 0);
	gtk_container_set_border_width (GTK_CONTAINER (chara_btn), 5);*/
	
	if(GetRecLongnameByType( 7, recordTpyeName )==-1)
		strcpy(recordTpyeName ,"Undefine");
	outa_btn = gtk_check_button_new_with_mnemonic (pConvert=_toUtf8(recordTpyeName));
	G_SAFE_FREE(pConvert);
	gtk_widget_show (outa_btn);
	gtk_box_pack_start (GTK_BOX (vbox1), outa_btn, FALSE, FALSE, 0);
	gtk_container_set_border_width (GTK_CONTAINER (outa_btn), 5);
	
	
	if(GetRecLongnameByType( 8, recordTpyeName )==-1)
		strcpy(recordTpyeName ,"Undefine");
	outs_btn = gtk_check_button_new_with_mnemonic (pConvert=_toUtf8(recordTpyeName));
	G_SAFE_FREE(pConvert);
	gtk_widget_show (outs_btn);
	gtk_box_pack_start (GTK_BOX (vbox1), outs_btn, FALSE, FALSE, 0);
	gtk_container_set_border_width (GTK_CONTAINER (outs_btn), 5);
	
	
	if(GetRecLongnameByType( 6, recordTpyeName )==-1)
		strcpy(recordTpyeName ,"Undefine");
	
	sysmsg_btn = gtk_check_button_new_with_mnemonic(pConvert=_toUtf8(recordTpyeName));
	G_SAFE_FREE(pConvert);
	gtk_widget_show (sysmsg_btn);
	gtk_box_pack_start (GTK_BOX (vbox1), sysmsg_btn, FALSE, FALSE, 0);
	gtk_container_set_border_width (GTK_CONTAINER (sysmsg_btn), 5);
	
	/* curve_btn = gtk_check_button_new_with_mnemonic ("\346\233\262\347\272\277\347\202\271");
	gtk_widget_show (curve_btn);
	gtk_box_pack_start (GTK_BOX (vbox1), curve_btn, FALSE, FALSE, 0);
	gtk_container_set_border_width (GTK_CONTAINER (curve_btn), 5);
	
	  obj_btn = gtk_check_button_new_with_mnemonic ("\346\216\247\345\210\266\345\257\271\350\261\241");
	  gtk_widget_show (obj_btn);
	  gtk_box_pack_start (GTK_BOX (vbox1), obj_btn, FALSE, FALSE, 0);
	gtk_container_set_border_width (GTK_CONTAINER (obj_btn), 5);*/
	
	hbox3 = gtk_hbox_new (FALSE, 55);
	gtk_widget_show (hbox3);
	gtk_box_pack_end (GTK_BOX (vbox1), hbox3, FALSE, FALSE, 0); 
	
	vbox2 = gtk_vbox_new (FALSE, 0);
	gtk_widget_show (vbox2);
	gtk_box_pack_start (GTK_BOX (hbox1), vbox2, FALSE, FALSE, 0);
	gtk_widget_set_size_request (vbox2, VBOX2_WIDTH, BOX_HEIGHT);
	
	frame1= gtk_frame_new(pConvert=_toUtf8EX(OIX_CONDITION_SEL));  //"OIX_CONDITION_SEL" 条件选择
	G_SAFE_FREE(pConvert);
	gtk_box_pack_start (GTK_BOX (vbox2),frame1, TRUE, TRUE, 0);
	gtk_widget_show (frame1);
	
	vbox5 = gtk_vbox_new (FALSE, 0);    
	
	gtk_widget_show(vbox5); 
	
    for(i=0;i<com_property_col-1;i++)
    {      
        hbox5 = gtk_hbox_new (FALSE, 0);
        gtk_box_pack_start (GTK_BOX (vbox5), hbox5, FALSE, FALSE, 0);
        gtk_widget_show(hbox5); 
        
        vbox4 = gtk_vbox_new (FALSE, 0);    
        gtk_widget_set_size_request (vbox4, 100, 20);
        gtk_box_pack_start (GTK_BOX (hbox5), vbox4, FALSE, FALSE, 0);
        gtk_widget_show(vbox4); 
        
        property_btn[i] = gtk_check_button_new_with_mnemonic (pConvert=_toUtf8EX(com_property[i]));
		G_SAFE_FREE(pConvert);
        
		/* gtk_widget_show(property_btn[i]);*/
        GLADE_HOOKUP_OBJECT (window1, property_btn[i], com_property[i]);
        gtk_box_pack_start (GTK_BOX (vbox4), property_btn[i], FALSE, FALSE, 0); 
        g_signal_connect ((gpointer) property_btn[i], "toggled",
			G_CALLBACK (on_property_btn_toggled),
			GINT_TO_POINTER(i));
        i++;
        
        vbox4 = gtk_vbox_new (FALSE, 0);    
        gtk_widget_set_size_request (vbox4, 100, 20);
        gtk_box_pack_start (GTK_BOX (hbox5), vbox4, FALSE, FALSE, 0);
        gtk_widget_show(vbox4); 
        
        property_btn[i] = gtk_check_button_new_with_mnemonic (pConvert=_toUtf8EX(com_property[i]));
		G_SAFE_FREE(pConvert);
        /*gtk_widget_show(   property_btn[i]);  */       
        GLADE_HOOKUP_OBJECT (window1, property_btn[i], com_property[i]);
        gtk_box_pack_start (GTK_BOX (vbox4), property_btn[i], FALSE, FALSE, 0); 
        g_signal_connect ((gpointer) property_btn[i], "toggled",
			G_CALLBACK (on_property_btn_toggled),
			GINT_TO_POINTER(i));
        
		i++;
        
        vbox4 = gtk_vbox_new (FALSE, 0);    
        gtk_widget_set_size_request (vbox4, 100, 20);
        gtk_box_pack_start (GTK_BOX (hbox5), vbox4, FALSE, FALSE, 0);
        gtk_widget_show(vbox4); 
        
        property_btn[i] = gtk_check_button_new_with_mnemonic (pConvert=_toUtf8EX(com_property[i]));
		G_SAFE_FREE(pConvert);
        /*gtk_widget_show(   property_btn[i]);  */       
        GLADE_HOOKUP_OBJECT (window1, property_btn[i], com_property[i]);
        gtk_box_pack_start (GTK_BOX (vbox4), property_btn[i], FALSE, FALSE, 0); 
        g_signal_connect ((gpointer) property_btn[i], "toggled",
			G_CALLBACK (on_property_btn_toggled),
			GINT_TO_POINTER(i));
    }
	if(i==com_property_col-1)
    {
        hbox5 = gtk_hbox_new (FALSE, 0);
        gtk_box_pack_start (GTK_BOX (vbox5), hbox5, FALSE, FALSE, 0);
        gtk_widget_show(hbox5); 
        
        vbox4 = gtk_vbox_new (FALSE, 0);    
        gtk_widget_set_size_request (vbox4, 100, 20);
        gtk_box_pack_start (GTK_BOX (hbox5), vbox4, FALSE, FALSE, 0);
        gtk_widget_show(vbox4); 
        
        property_btn[i] = gtk_check_button_new_with_mnemonic (pConvert=_toUtf8EX(com_property[i]));
		G_SAFE_FREE(pConvert);
		
        GLADE_HOOKUP_OBJECT (window1, property_btn[i], com_property[i]);
        gtk_box_pack_start (GTK_BOX (vbox4), property_btn[i], FALSE, FALSE, 0); 
        g_signal_connect ((gpointer) property_btn[i], "toggled",
			G_CALLBACK (on_property_btn_toggled),
			GINT_TO_POINTER(i));
	} 
	else
	{
        hbox5 = gtk_hbox_new (FALSE, 0);
        gtk_box_pack_start (GTK_BOX (vbox5), hbox5, FALSE, FALSE, 0);
        gtk_widget_show(hbox5); 
	}
	for(i=0;i<Ana_property_col;i++)
	{
        vbox4 = gtk_vbox_new (FALSE, 0);    
        gtk_widget_set_size_request (vbox4, 100, 20);
        gtk_box_pack_start (GTK_BOX (hbox5), vbox4, FALSE, FALSE, 0);
        gtk_widget_show(vbox4); 
        
        
        ana_property_btn[i] = gtk_check_button_new_with_mnemonic (pConvert=_toUtf8EX(Ana_property[i]));
		G_SAFE_FREE(pConvert);
		/* gtk_widget_show(ana_property_btn);*/
        GLADE_HOOKUP_OBJECT (window1, ana_property_btn[i], Ana_property[i]);
        gtk_box_pack_start (GTK_BOX (vbox4), ana_property_btn[i], FALSE, FALSE, 0); 
        g_signal_connect ((gpointer) ana_property_btn[i], "toggled",
			G_CALLBACK (on_property_btn_toggled),
			(gpointer)(ANA_PROPERTY+i));
	}
	
	/* hbox5 = gtk_hbox_new (FALSE, 0);
	gtk_box_pack_start (GTK_BOX (vbox5), hbox5, FALSE, FALSE, 0);
	gtk_widget_show(hbox5); */
	
	vbox4 = gtk_vbox_new (FALSE, 0);    
	gtk_widget_set_size_request (vbox4, 100, 20);
	gtk_box_pack_start (GTK_BOX (hbox5), vbox4, FALSE, FALSE, 0);
	gtk_widget_show(vbox4); 
	
	pol_property_btn = gtk_check_button_new_with_mnemonic (pConvert=_toUtf8EX(Pol_SOE_property[0]));
	G_SAFE_FREE(pConvert);
	
	GLADE_HOOKUP_OBJECT (window1, pol_property_btn, Pol_SOE_property[0]);
	gtk_box_pack_start (GTK_BOX (vbox4), pol_property_btn, FALSE, FALSE, 0); 
	g_signal_connect ((gpointer) pol_property_btn, "toggled",
		G_CALLBACK (on_property_btn_toggled),
		(gpointer)(POL_PROPERTY));
	
	hbox5 = gtk_hbox_new (FALSE, 0);
	gtk_box_pack_start (GTK_BOX (vbox5), hbox5, FALSE, FALSE, 0);
	gtk_widget_show(hbox5);
	
	vbox4 = gtk_vbox_new (FALSE, 0);    
	gtk_widget_set_size_request (vbox4, 100, 20);
	gtk_box_pack_start (GTK_BOX (hbox5), vbox4, FALSE, FALSE, 0);
	gtk_widget_show(vbox4); 
	
	imp_property_btn = gtk_check_button_new_with_mnemonic (pConvert=_toUtf8EX(Imp_property[0]));
	G_SAFE_FREE(pConvert);
	g_signal_connect ((gpointer) imp_property_btn, "toggled",
		G_CALLBACK (on_property_btn_toggled),
		(gpointer)IMP_PROPERTY);
	GLADE_HOOKUP_OBJECT (window1, imp_property_btn, Imp_property[0]);
	gtk_box_pack_start (GTK_BOX (vbox4), imp_property_btn, FALSE, FALSE, 0); 
	
    /*    hbox5 = gtk_hbox_new (FALSE, 0);
	gtk_box_pack_start (GTK_BOX (vbox5), hbox5, FALSE, FALSE, 0);
	gtk_widget_show(hbox5); 
	
	  vbox4 = gtk_vbox_new (FALSE, 0);    
	  gtk_widget_set_size_request (vbox4, 100, 20);
	  gtk_box_pack_start (GTK_BOX (hbox5), vbox4, FALSE, FALSE, 0);
	  gtk_widget_show(vbox4); 
	  
		/* calc_property_btn = gtk_check_button_new_with_mnemonic (_toUtf8EX(Calc_property[0]));
        g_signal_connect ((gpointer) calc_property_btn, "toggled",
		G_CALLBACK (on_property_btn_toggled),
		CALC_PROPERTY);
        GLADE_HOOKUP_OBJECT (window1, calc_property_btn, Calc_property[0]);
        gtk_box_pack_start (GTK_BOX (vbox4), calc_property_btn, FALSE, FALSE, 0); 
        
		  vbox4 = gtk_vbox_new (FALSE, 0);    
		  gtk_widget_set_size_request (vbox4, 100, 20);
		  gtk_box_pack_start (GTK_BOX (hbox5), vbox4, FALSE, FALSE, 0);
	gtk_widget_show(vbox4); */
	
	/*  outs_property_btn = gtk_check_button_new_with_mnemonic (_toUtf8EX(Outs_property[0]));
	g_signal_connect ((gpointer) outs_property_btn , "toggled",
	G_CALLBACK (on_property_btn_toggled),
	OUTS_PROPERTY);
	GLADE_HOOKUP_OBJECT (window1, outs_property_btn, Outs_property[0]);
	gtk_box_pack_start (GTK_BOX (vbox4), outs_property_btn, FALSE, FALSE, 0);  */
	
	hbox5 = gtk_hbox_new (FALSE, 10);
	gtk_box_pack_start (GTK_BOX (vbox5), hbox5, FALSE, FALSE, 0);
	gtk_widget_show(hbox5); 
	
	table1 = gtk_table_new (4, 3, FALSE);
	/*gtk_widget_show (table1);*/
	
	gtk_box_pack_start (GTK_BOX (hbox5), table1, FALSE, FALSE, 0);
	gtk_table_set_row_spacings (GTK_TABLE (table1), 10);
	gtk_container_add(GTK_CONTAINER(frame1),vbox5);    
	
	opt1_lab = gtk_label_new ("opt1_lab");
	gtk_widget_show (opt1_lab);
	gtk_table_attach (GTK_TABLE (table1), opt1_lab, 0, 1, 0, 1,
		(GtkAttachOptions) (GTK_FILL),
		(GtkAttachOptions) (0), 0, 0);
	gtk_misc_set_alignment (GTK_MISC (opt1_lab), 0, 0.5);
	
	opt2_lab = gtk_label_new ("opt2_lab");
	gtk_widget_show (opt2_lab);
	gtk_table_attach (GTK_TABLE (table1), opt2_lab, 0, 1, 1, 2,
		(GtkAttachOptions) (GTK_FILL),
		(GtkAttachOptions) (0), 0, 0);
	gtk_misc_set_alignment (GTK_MISC (opt2_lab), 0, 0.5);
	
	opt3_lab = gtk_label_new ("opt3_lab");
	gtk_widget_show (opt3_lab);
	gtk_table_attach (GTK_TABLE (table1), opt3_lab, 0, 1, 2, 3,
		(GtkAttachOptions) (GTK_FILL),
		(GtkAttachOptions) (0), 0, 0);
	gtk_misc_set_alignment (GTK_MISC (opt3_lab), 0, 0.5);
	
	opt4_lab = gtk_label_new ("opt4_lab");
	gtk_widget_show (opt4_lab);
	gtk_table_attach (GTK_TABLE (table1), opt4_lab, 0, 1, 3, 4,
		(GtkAttachOptions) (GTK_FILL),
		(GtkAttachOptions) (0), 0, 0);
	gtk_misc_set_alignment (GTK_MISC (opt4_lab), 0, 0.5);
	
	opt1_comb = gtk_combo_box_new_text ();
	gtk_widget_set_usize(GTK_WIDGET(opt1_comb), 80, 27);
	gtk_widget_show (opt1_comb);
	gtk_table_attach (GTK_TABLE (table1), opt1_comb, 1, 2, 0, 1,
		(GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		(GtkAttachOptions) (GTK_FILL), 0, 0);
	for(i=0;i<opr_num;i++)      
		gtk_combo_box_append_text (GTK_COMBO_BOX (opt1_comb),opr_name[i]);
	
	gtk_combo_box_set_active(GTK_COMBO_BOX (opt1_comb),0);
	
	opt1_entry = gtk_entry_new ();
	gtk_widget_set_usize(GTK_WIDGET(opt1_entry), 120, 27);
	gtk_widget_show (opt1_entry);
	gtk_table_attach (GTK_TABLE (table1), opt1_entry, 2, 3, 0, 1,
		(GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		(GtkAttachOptions) (0), 0, 0);
	
	opt2_entry = gtk_entry_new ();
	gtk_widget_set_usize(GTK_WIDGET(opt2_entry), 120, 27);
	gtk_widget_show (opt2_entry);
	gtk_table_attach (GTK_TABLE (table1), opt2_entry, 2, 3, 1, 2,
		(GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		(GtkAttachOptions) (0), 0, 0);
	
	opt3_entry = gtk_entry_new ();
	gtk_widget_set_usize(GTK_WIDGET(opt3_entry), 120, 27);
	gtk_widget_show (opt3_entry);
	gtk_table_attach (GTK_TABLE (table1), opt3_entry, 2, 3, 2, 3,
		(GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		(GtkAttachOptions) (0), 0, 0);
	
	opt4_entry = gtk_entry_new ();  
	gtk_widget_set_usize(GTK_WIDGET(opt4_entry), 120, 27);
	gtk_widget_show (opt4_entry);
	
	gtk_table_attach (GTK_TABLE (table1), opt4_entry, 2, 3, 3, 4,
		(GtkAttachOptions)(GTK_EXPAND | GTK_FILL) ,
		(GtkAttachOptions) (0), 0, 0);
	
	opt2_comb = gtk_combo_box_new_text ();
	gtk_widget_set_usize(GTK_WIDGET(opt2_comb), 80, 27);
	gtk_widget_show (opt2_comb);  
	gtk_table_attach (GTK_TABLE (table1), opt2_comb, 1, 2, 1, 2,
		(GtkAttachOptions) (GTK_FILL),
		(GtkAttachOptions) (GTK_FILL), 0, 0);
	for(i=0;i<opr_num;i++)      
		gtk_combo_box_append_text (GTK_COMBO_BOX (opt2_comb),opr_name[i]);
	
	gtk_combo_box_set_active(GTK_COMBO_BOX (opt2_comb),0);
	
	opt3_comb = gtk_combo_box_new_text ();
	gtk_widget_set_usize(GTK_WIDGET(opt3_comb), 80, 27);
	gtk_widget_show (opt3_comb);  
	gtk_table_attach (GTK_TABLE (table1), opt3_comb, 1, 2, 2, 3,
		(GtkAttachOptions) (GTK_FILL),
		(GtkAttachOptions) (GTK_FILL), 0, 0);
	for(i=0;i<opr_num;i++)      
		gtk_combo_box_append_text (GTK_COMBO_BOX (opt3_comb),opr_name[i]);
	gtk_combo_box_set_active(GTK_COMBO_BOX (opt3_comb),0);
	
	opt4_comb = gtk_combo_box_new_text ();
	gtk_widget_set_usize(GTK_WIDGET(opt4_comb), 80, 27);
	gtk_widget_show (opt4_comb);  
	gtk_table_attach (GTK_TABLE (table1), opt4_comb, 1, 2, 3, 4,
		(GtkAttachOptions) (GTK_FILL),
		(GtkAttachOptions) (GTK_FILL), 0, 0);
	for(i=0;i<opr_num;i++)      
		gtk_combo_box_append_text (GTK_COMBO_BOX (opt4_comb),opr_name[i]);
	gtk_combo_box_set_active(GTK_COMBO_BOX (opt4_comb),0);
	
	hbox5 = gtk_hbox_new (FALSE, 20);
	gtk_box_pack_start (GTK_BOX (vbox2), hbox5, FALSE, FALSE, 0);
	gtk_widget_show(hbox5);  
	
	ok_btn = gtk_button_new_with_mnemonic (pConvert=_toUtf8EX(OIX_CSTR_OK));
	G_SAFE_FREE(pConvert);
	gtk_widget_show (ok_btn);
	gtk_box_pack_start (GTK_BOX (hbox5), ok_btn, FALSE, FALSE, 0);
	gtk_widget_set_size_request (ok_btn, 100, 40);
	gtk_container_set_border_width (GTK_CONTAINER (ok_btn), 5);
	
	cancel_btn = gtk_button_new_with_mnemonic (pConvert=_toUtf8EX(OIX_CSTR_CANCEL));
	G_SAFE_FREE(pConvert);
	gtk_widget_show (cancel_btn);
	gtk_box_pack_start (GTK_BOX (hbox5), cancel_btn, FALSE, FALSE, 0);
	gtk_widget_set_size_request (cancel_btn, 100, 40);
	gtk_container_set_border_width (GTK_CONTAINER (cancel_btn), 5);
    // rm chi chi 	
	g_signal_connect ((gpointer) stn_filter_combox, "changed",
		G_CALLBACK (on_stn_filter_combox_changed),
		NULL);
	
	// 	g_signal_connect ((gpointer) dev_filter_combox, "changed",
	// 		G_CALLBACK (on_dev_filter_combox_changed),
	// 		NULL); 
	g_signal_connect ((gpointer) ana_btn, "toggled",
		G_CALLBACK (on_datatype_btn_toggled),
		(gpointer)ANA_TYPE);
	
	g_signal_connect ((gpointer) pol_btn, "toggled",
		G_CALLBACK (on_datatype_btn_toggled),
		(gpointer)POL_TYPE);
	g_signal_connect ((gpointer) soe_btn, "toggled",
		G_CALLBACK (on_datatype_btn_toggled),
		(gpointer)SOE_TYPE);
	g_signal_connect ((gpointer) imp_btn, "toggled",
		G_CALLBACK (on_datatype_btn_toggled),
		(gpointer)IMP_TYPE);
		/* g_signal_connect ((gpointer) calc_btn, "toggled",
		G_CALLBACK (on_datatype_btn_toggled),
		CALC_TYPE);
		g_signal_connect ((gpointer) chara_btn, "toggled",
		G_CALLBACK (on_datatype_btn_toggled),
	CHARA_TYPE);*/
	g_signal_connect ((gpointer) outa_btn, "toggled",
		G_CALLBACK (on_datatype_btn_toggled),
		(gpointer)OUTA_TYPE);
	g_signal_connect ((gpointer) outs_btn, "toggled",
		G_CALLBACK (on_datatype_btn_toggled),
		(gpointer) OUTS_TYPE);
	g_signal_connect ((gpointer) sysmsg_btn, "toggled",
		G_CALLBACK (on_datatype_btn_toggled),
		(gpointer)SYSMSG_TYPE);
		/* g_signal_connect ((gpointer) curve_btn, "toggled",
		G_CALLBACK (on_datatype_btn_toggled),
		CURVE_TYPE);
		g_signal_connect ((gpointer) obj_btn, "toggled",
		G_CALLBACK (on_datatype_btn_toggled),
	DEVOBJ_TYPE);*/
	g_signal_connect ((gpointer) ok_btn, "pressed",
		G_CALLBACK (on_ok_btn_pressed),
		window1);
	g_signal_connect ((gpointer) cancel_btn, "pressed",
		G_CALLBACK (on_cancel_btn_clicked),
		window1);
	
	/* Store pointers to all widgets, for use by lookup_widget(). */
	GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
	GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
	GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
	GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
	GLADE_HOOKUP_OBJECT (window1, dev_filter_combox, "dev_filter_combox");
	GLADE_HOOKUP_OBJECT (window1, ana_btn, "ana_btn");
	GLADE_HOOKUP_OBJECT (window1, pol_btn, "pol_btn");
	GLADE_HOOKUP_OBJECT (window1, soe_btn, "soe_btn");
	GLADE_HOOKUP_OBJECT (window1, imp_btn, "imp_btn");
	/* GLADE_HOOKUP_OBJECT (window1, calc_btn, "calc_btn");
	GLADE_HOOKUP_OBJECT (window1, chara_btn, "chara_btn");*/
	GLADE_HOOKUP_OBJECT (window1, outa_btn, "outa_btn");
	GLADE_HOOKUP_OBJECT (window1, outs_btn, "outs_btn");
	/*GLADE_HOOKUP_OBJECT (window1, curve_btn, "curve_btn");
	GLADE_HOOKUP_OBJECT (window1, obj_btn, "obj_btn");*/
	GLADE_HOOKUP_OBJECT (window1, frame1, "frame1");
	/*GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
	GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
	GLADE_HOOKUP_OBJECT (window1, result_btn, "result_btn");*/
	GLADE_HOOKUP_OBJECT (window1, ok_btn, "ok_btn");
	GLADE_HOOKUP_OBJECT (window1, cancel_btn, "cancel_btn");
	GLADE_HOOKUP_OBJECT (window1, vbox2, "vbox2");
	/* GLADE_HOOKUP_OBJECT (window1, drawingarea1, "drawingarea1");*/
	GLADE_HOOKUP_OBJECT (window1, table1, "table1");
	GLADE_HOOKUP_OBJECT (window1, opt1_lab, "opt1_lab");
	GLADE_HOOKUP_OBJECT (window1, opt2_lab, "opt2_lab");
	GLADE_HOOKUP_OBJECT (window1, opt3_lab, "opt3_lab");
	GLADE_HOOKUP_OBJECT (window1, opt4_lab, "opt4_lab");
	GLADE_HOOKUP_OBJECT (window1, opt1_comb, "opt1_comb");
	GLADE_HOOKUP_OBJECT (window1, opt1_entry, "opt1_entry");
	GLADE_HOOKUP_OBJECT (window1, opt2_entry, "opt2_entry");
	GLADE_HOOKUP_OBJECT (window1, opt3_entry, "opt3_entry");
	GLADE_HOOKUP_OBJECT (window1, opt4_entry, "opt4_entry");
	GLADE_HOOKUP_OBJECT (window1, opt2_comb, "opt2_comb");
	GLADE_HOOKUP_OBJECT (window1, opt3_comb, "opt3_comb");
	GLADE_HOOKUP_OBJECT (window1, opt4_comb, "opt4_comb");
	
	return window1;
}
void  UpdateRelatePt( int crt_n )
{
	DspSearchPage(crt_n,cur_search_page.end_id);
}

void DspRealtePtInfo(int crt_n,int relate_idx)
{

	int i;
	
	for (i=0;i<relatepoint[relate_idx].child_num;i++)
	{
	//	GetEntryIdByName(relatepoint[relate_idx].childname[i],&result_pt[i]);
		GetPtIdByNameStr(relatepoint[relate_idx].childname[i],&result_pt[i]);
		
	}

	if (SearchResultWin[crt_n])
	{
		gtk_widget_destroy(SearchResultWin[crt_n]) ;
		SearchResultWin[crt_n]= (void *)NULL ;  
	}

	if (SearchResultWin[crt_n]=DspResult(crt_n,relatepoint[relate_idx].child_num,1))
		DspSearchPage(crt_n,cur_search_page.end_id);

	if (!relatept_timeout_id[crt_n])
			relatept_timeout_id[crt_n]=  gtk_timeout_add ( RELATEPTINTERVAL,(GtkFunction)UpdateRelatePt, GINT_TO_POINTER (crt_n) );

}