/******************************************************************************************************************************************
#	File:	ots_str_list.h
#	Describe:	ots2000 menu str
#	Created by dm, 2010.09.08
******************************************************************************************************************************************/


#ifdef CHINESE
/**************************************************************中文版本******************************************************************/


/*****************变量**********************中文名称*******************************************************************/

#define		OTS_MSTR_FILE					"文件"
#define		OTS_MSTR_STUDENT_INFO			"学员信息"
#define		OTS_MSTR_TRAIN_MANAGE			"培训任务管理"
#define		OTS_MSTR_TRAIN_LIB				"工况与案例库"
#define		OTS_MSTR_HISTORY_REC			"历史记录查询"
#define		OTS_MSTR_EXAM					"专业知识考核"
#define		OTS_MSTR_SYS_SET				"系统设置"
#define		OTS_MSTR_HELP					"帮助"


#define		OTS_ASTR_LOGIN					"登陆"
#define		OTS_ASTR_LOGOUT					"注销"
#define		OTS_ASTR_QUIT					"退出"
#define		OTS_ASTR_USERINFO				"学员用户信息"
#define		OTS_ASTR_LOGIN_REC				"学员登陆历史记录"
#define		OTS_ASTR_SCORE					"学员历史成绩"
#define		OTS_ASTR_CPT					"用户权限"
#define		OTS_ASTR_SETTASK				"设置任务"
#define		OTS_ASTR_LOGIN_STUDENT			"在线学员培训"
#define		OTS_ASTR_TRAIN_INFO				"培训信息管理"
#define		OTS_ASTR_SIM_SPEED				"修改仿真速度"
#define		OTS_ASTR_GO_ON					"继续"
#define		OTS_ASTR_PAUSE					"暂停"
#define		OTS_ASTR_STOP					"停止"
#define		OTS_ASTR_SEND_MSG				"发送提示信息"
#define		OTS_ASTR_MODEL					"模型设置"
#define		OTS_ASTR_SEQUSNCE				"流程设置"
#define		OTS_ASTR_FAULT					"故障库设置"
#define		OTS_ASTR_TASK					"培训案例库"
#define		OTS_ASTR_SCENE					"静态工况库"
#define		OTS_ASTR_REVERT					"工况再现库"
#define		OTS_ASTR_OPT					"在线操作库"
#define		OTS_ASTR_HISTORY_REC			"学员历史记录查询"
#define		OTS_ASTR_EXAM					"题库管理"
#define		OTS_ASTR_CONFIG					"配置工作站"
#define		OTS_ASTR_HELP					"教员管理系统帮助"
#define		OTS_ASTR_ABOUT					"关于我们"
#define		OTS_ASTR_CONTACT				"联系我们"


#define		OTS_BSTR_APPLY					"应用"
#define		OTS_BSTR_ENTER					"确定"
#define		OTS_BSTR_CANCEL					"取消"
#define		OTS_BSTR_REFRESH				"刷新"
#define		OTS_BSTR_QUIT					"退出"
#define		OTS_BSTR_LOGIN					"登陆"
#define		OTS_BSTR_SEND					"发送"
#define		OTS_BSTR_CLOSE					"关闭"
#define		OTS_BSTR_LOOKAT					"查看"
#define		OTS_BSTR_SEND_TASK				"发送任务"
#define		OTS_BSTR_STNDEV					"选择厂站设备"
#define		OTS_BSTR_SELECT_TASK			"选择任务"
#define		OTS_BSTR_SEARCH					"查询"
#define		OTS_BSTR_TODAY_REC				"显示当天记录"
#define		OTS_BSTR_WORD					"导出到Word"
#define		OTS_BSTR_NEWEST					"显示最新"
#define		OTS_BSTR_SETTASK				"设置任务"
#define		OTS_BSTR_SETSCENE				"设置工况"
#define		OTS_BSTR_SETFAULT				"设置故障"
#define		OTS_BSTR_ADD					"添加"
#define		OTS_BSTR_DEL					"删除"
#define		OTS_BSTR_MODIFY					"修改"
#define		OTS_BSTR_FAULT_DATA				"故障数据"
#define		OTS_BSTR_FAULT_ADD				"添加故障"
#define		OTS_BSTR_FAULT_DEL				"删除故障"
#define		OTS_BSTR_FAULT_MODIFY			"修改故障"
#define		OTS_BSTR_MODEL_PARAM			"模型参数"
#define		OTS_BSTR_MODEL_ADD				"添加模型"
#define		OTS_BSTR_MODEL_DEL				"删除模型"
#define		OTS_BSTR_MODEL_MODIFY			"修改模型"
#define		OTS_BSTR_MODEL_INTO				"导入模型"
#define		OTS_BSTR_MODEL_CONFIG			"打开模型配置"
#define		OTS_BSTR_REVERT_ADD				"添加工况再现"
#define		OTS_BSTR_REVERT_DEL				"删除工况再现"
#define		OTS_BSTR_REVERT_MODIFY			"修改工况再现"
#define		OTS_BSTR_SCENE_DATA				"工况数据"
#define		OTS_BSTR_SCENE_ADD				"添加工况"
#define		OTS_BSTR_SCENE_DEL				"删除工况"
#define		OTS_BSTR_SCENE_MODIFY			"修改工况"
#define		OTS_BSTR_SCENE_INTO				"导入工况"
#define		OTS_BSTR_SEQUENCE_ADD			"添加流程"
#define		OTS_BSTR_SEQUENCE_DEL			"删除流程"
#define		OTS_BSTR_SEQUENCE_MODIFY		"修改流程"
#define		OTS_BSTR_SEQUENCE_INTO			"导入流程"
#define		OTS_BSTR_SEQUENCE_CONFIG		"打开流程配置"
#define		OTS_BSTR_STATION_ADD			"添加主机"
#define		OTS_BSTR_STATION_DEL			"删除主机"
#define		OTS_BSTR_STATION_MODIFY			"修改主机"
#define		OTS_BSTR_TASK_ADD				"添加任务"
#define		OTS_BSTR_TASK_DEL				"删除任务"
#define		OTS_BSTR_TASK_MODIFY			"修改任务"
#define		OTS_BSTR_TRAININFO_ADD			"添加培训信息"
#define		OTS_BSTR_TRAININFO_DEL			"删除培训信息"
#define		OTS_BSTR_TRAININFO_MODIFY		"修改培训信息"


#define		OTS_STR_LOGIN_STATUS			"未登录"

#else
#ifdef ENGLISH
/********************************************************************英文版本*****************************************************************/


/*****************变量**********************英文名称*******************************************************************/
#define		OTS_MSTR_FILE					"File"
#define		OTS_MSTR_STUDENT_INFO			"Student Info"
#define		OTS_MSTR_TRAIN_MANAGE			"培训任务管理"
#define		OTS_MSTR_TRAIN_LIB				"工况与案例库"
#define		OTS_MSTR_HISTORY_REC			"历史记录查询"
#define		OTS_MSTR_EXAM					"专业知识考核"
#define		OTS_MSTR_SYS_SET				"系统设置"
#define		OTS_MSTR_HELP					"帮助"


#define		OTS_ASTR_LOGIN					"登陆"
#define		OTS_ASTR_LOGOUT					"注销"
#define		OTS_ASTR_QUIT					"退出"
#define		OTS_ASTR_USERINFO				"学员用户信息"
#define		OTS_ASTR_LOGIN_REC				"学员登陆历史记录"
#define		OTS_ASTR_SCORE					"学员历史成绩"
#define		OTS_ASTR_CPT					"用户权限"
#define		OTS_ASTR_SETTASK				"设置任务"
#define		OTS_ASTR_LOGIN_STUDENT			"在线学员培训"
#define		OTS_ASTR_TRAIN_INFO				"培训信息管理"
#define		OTS_ASTR_SIM_SPEED				"修改仿真速度"
#define		OTS_ASTR_GO_ON					"继续"
#define		OTS_ASTR_PAUSE					"暂停"
#define		OTS_ASTR_STOP					"停止"
#define		OTS_ASTR_SEND_MSG				"发送提示信息"
#define		OTS_ASTR_MODEL					"模型设置"
#define		OTS_ASTR_SEQUSNCE				"流程设置"
#define		OTS_ASTR_FAULT					"故障库设置"
#define		OTS_ASTR_TASK					"培训案例库"
#define		OTS_ASTR_SCENE					"静态工况库"
#define		OTS_ASTR_REVERT					"工况再现库"
#define		OTS_ASTR_OPT					"在线操作库"
#define		OTS_ASTR_HISTORY_REC			"学员历史记录查询"
#define		OTS_ASTR_EXAM					"题库管理"
#define		OTS_ASTR_CONFIG					"配置工作站"
#define		OTS_ASTR_HELP					"教员管理系统帮助"
#define		OTS_ASTR_ABOUT					"关于我们"
#define		OTS_ASTR_CONTACT				"联系我们"


#define		OTS_BSTR_APPLY					"应用"
#define		OTS_BSTR_ENTER					"确定"
#define		OTS_BSTR_CANCEL					"取消"
#define		OTS_BSTR_REFRESH				"刷新"
#define		OTS_BSTR_QUIT					"退出"
#define		OTS_BSTR_LOGIN					"登陆"
#define		OTS_BSTR_SEND					"发送"
#define		OTS_BSTR_CLOSE					"关闭"
#define		OTS_BSTR_LOOKAT					"查看"
#define		OTS_BSTR_SEND_TASK				"发送任务"
#define		OTS_BSTR_STNDEV					"选择厂站设备"
#define		OTS_BSTR_SELECT_TASK			"选择任务"
#define		OTS_BSTR_SEARCH					"查询"
#define		OTS_BSTR_TODAY_REC				"显示当天记录"
#define		OTS_BSTR_WORD					"导出到Word"
#define		OTS_BSTR_NEWEST					"显示最新"
#define		OTS_BSTR_SETTASK				"设置任务"
#define		OTS_BSTR_SETSCENE				"设置工况"
#define		OTS_BSTR_SETFAULT				"设置故障"
#define		OTS_BSTR_ADD					"添加"
#define		OTS_BSTR_DEL					"删除"
#define		OTS_BSTR_MODIFY					"修改"
#define		OTS_BSTR_FAULT_DATA				"故障数据"
#define		OTS_BSTR_FAULT_ADD				"添加故障"
#define		OTS_BSTR_FAULT_DEL				"删除故障"
#define		OTS_BSTR_FAULT_MODIFY			"修改故障"
#define		OTS_BSTR_MODEL_PARAM			"模型参数"
#define		OTS_BSTR_MODEL_ADD				"添加模型"
#define		OTS_BSTR_MODEL_DEL				"删除模型"
#define		OTS_BSTR_MODEL_MODIFY			"修改模型"
#define		OTS_BSTR_MODEL_INTO				"导入模型"
#define		OTS_BSTR_MODEL_CONFIG			"打开模型配置"
#define		OTS_BSTR_REVERT_ADD				"添加工况再现"
#define		OTS_BSTR_REVERT_DEL				"删除工况再现"
#define		OTS_BSTR_REVERT_MODIFY			"修改工况再现"
#define		OTS_BSTR_SCENE_DATA				"工况数据"
#define		OTS_BSTR_SCENE_ADD				"添加工况"
#define		OTS_BSTR_SCENE_DEL				"删除工况"
#define		OTS_BSTR_SCENE_MODIFY			"修改工况"
#define		OTS_BSTR_SCENE_INTO				"导入工况"
#define		OTS_BSTR_SEQUENCE_ADD			"添加流程"
#define		OTS_BSTR_SEQUENCE_DEL			"删除流程"
#define		OTS_BSTR_SEQUENCE_MODIFY		"修改流程"
#define		OTS_BSTR_SEQUENCE_INTO			"导入流程"
#define		OTS_BSTR_SEQUENCE_CONFIG		"打开流程配置"
#define		OTS_BSTR_STATION_ADD			"添加主机"
#define		OTS_BSTR_STATION_DEL			"删除主机"
#define		OTS_BSTR_STATION_MODIFY			"修改主机"
#define		OTS_BSTR_TASK_ADD				"添加任务"
#define		OTS_BSTR_TASK_DEL				"删除任务"
#define		OTS_BSTR_TASK_MODIFY			"修改任务"
#define		OTS_BSTR_TRAININFO_ADD			"添加培训信息"
#define		OTS_BSTR_TRAININFO_DEL			"删除培训信息"
#define		OTS_BSTR_TRAININFO_MODIFY		"修改培训信息"

#endif
#endif