######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 5 14:37:07 2010
######################################################################

TEMPLATE = app
TARGET = SimuTrainee
CONFIG += qaxcontainer

win32{
QTDIR=C:\Qt\4.5.2
}
DEPENDPATH += .
INCLUDEPATH += .	\
		\home\ems\system\ots\v4.0a\inc
QT +=	sql \
	network

TRANSLATIONS =  designer_zh_CN.ts \
		SimuTrainee_en.ts  \
		SimuTrainee_zh_CN.ts

	
CONFIG(debug) {
	unix|win32: LIBS += odbc32.lib
	unix|win32: LIBS += odbccp32.lib
	unix|win32: LIBS += wsock32.lib
 	unix|win32: LIBS += \home\ems\system\dms\v4.0a\lib\dblib.lib
 	unix|win32: LIBS += \home\ems\system\lan\v4.0a\lib\lan.lib
	unix|win32: LIBS += \home\ems\system\dps\v4.0a\lib\ipclib.lib
	unix|win32: LIBS += \home\ems\system\ots\ots_hdb\lib\ots_hdbd.lib
	unix|win32: LIBS += \home\ems\system\ots\ots_hdb\lib\otsd.lib
} else {
	unix|win32: LIBS += odbc32.lib
	unix|win32: LIBS += odbccp32.lib
	unix|win32: LIBS += wsock32.lib
	unix|win32: LIBS += \home\ems\system\dms\v4.0a\lib\dblib.lib
 	unix|win32: LIBS += \home\ems\system\lan\v4.0a\lib\lan.lib
	unix|win32: LIBS += \home\ems\system\dps\v4.0a\lib\ipclib.lib
	unix|win32: LIBS += \home\ems\system\ots\ots_hdb\lib\ots_hdb.lib
	unix|win32: LIBS += \home\ems\system\ots\ots_hdb\lib\ots.lib
}

# Inputxxxxxx
FORMS +=	ui/SimuTrainee.ui \
		ui/ChangePassword.ui \
		ui/RevertPlayer.ui \
		ui/setSimuTip.ui \
		ui/taskManage.ui \
		ui/UserLogin.ui \
		/home/ems/system/ots/SimuTutor/ui/groups.ui \
		/home/ems/system/ots/SimuTutor/ui/historyrec.ui \
		/home/ems/system/ots/SimuTutor/ui/login.ui \
		/home/ems/system/ots/SimuTutor/ui/selecttask.ui \
		/home/ems/system/ots/SimuTutor/ui/sendmessage.ui \
		/home/ems/system/ots/SimuTutor/ui/setscenefault.ui \
		/home/ems/system/ots/SimuTutor/ui/settask.ui \
		/home/ems/system/ots/SimuTutor/ui/studentinfo.ui \
		/home/ems/system/ots/SimuTutor/ui/studentinfoadd.ui 

HEADERS +=	src/SimuTrainee.h \
		src/calculation.h \
		src/LocalOperate.h \
		src/Login.h \
		src/RevertPlayer.h \
		src/SimuTip.h \
		src/taskManage.h \
		src/thread.h \
		/home/ems/system/ots/SimuTutor/src/excelobject.h \
        	/home/ems/system/ots/SimuTutor/src/historyrec.h \
		/home/ems/system/ots/SimuTutor/src/qcommon.h \
		/home/ems/system/ots/SimuTutor/src/sendmessage.h \
		/home/ems/system/ots/SimuTutor/src/settask.h \
		/home/ems/system/ots/SimuTutor/src/studentinfo.h 
	
SOURCES +=	src/main.cpp \
		src/SimuTrainee.cpp \
		src/calculation.cpp \
		src/LocalOperate.cpp \
		src/Login.cpp \
		src/RevertPlayer.cpp \
		src/SimuTip.cpp \
		src/taskManage.cpp \
		src/thread.cpp \
		/home/ems/system/ots/SimuTutor/src/excelobject.cpp \
        	/home/ems/system/ots/SimuTutor/src/historyrec.cpp \
		/home/ems/system/ots/SimuTutor/src/qcommon.cpp \
		/home/ems/system/ots/SimuTutor/src/sendmessage.cpp \
		/home/ems/system/ots/SimuTutor/src/settask.cpp \
		/home/ems/system/ots/SimuTutor/src/studentinfo.cpp 

	
RESOURCES += SimuTrainee.qrc 
RC_FILE = SimuTrainee.rc 
