package com.bitc.jk.xmis.util.sql;

public class SQLScript_Financy {

	public static String getFinancyIncomeRunningAccountList = "SET NOCOUNT ON SELECT  CONVERT(INT, null) AS year \n"
			+ " ,CONVERT(INT, NULL) AS iperiod \n"
			+ " ,CONVERT(INT, NULL) AS ino_id \n"
			+ " ,CONVERT(DECIMAL(11,2),NULL) AS MB \n"
			+ " ,CONVERT(NVARCHAR(100),NULL) AS cdigest \n"
			+ " ,CONVERT(DATETIME, NULL) AS dbill_date \n"
			+ " ,CONVERT(NVARCHAR(100),NULL) project_code \n"
			+ " ,CONVERT(bit, NULL) AS flag  \n"
			+ " ,CONVERT(nvarchar(32), NULL) AS projectID  \n"
			+ " INTO #resultWithoutContract \n"
			+ " WHERE 1=2 \n"
			+ " SELECT DISTINCT project_code,xmis.prj_项目.项目ID \n"
			+ " into #projectCode \n"
			+ " FROM xmis.fas_项目金额调整表 adjusted , xmis.fas_fitemss00 , xmis.prj_项目 \n"
			+ " WHERE   xmis.fas_fitemss00.year = 2009 \n"
			+ " AND adjusted.citem_id = citemcode \n"
			+ " AND project_code = xmis.prj_项目.项目编码 \n"
			+ " insert into #resultWithoutContract  \n"
			+ " SELECT  2009 as year \n"
			+ " ,convert(int, null) as iperiod \n"
			+ " ,convert(int, null) as ino_id \n"
			+ " ,adjusted_mb AS MB \n"
			+ " ,'2010.09项目清理后,结算余额' as cdigest \n"
			+ " ,convert(datetime, '2009-09-30') as dbill_date  \n"
			+ " ,xmis.fas_fitemss00.project_code  \n"
			+ " ,1  \n"
			+ " ,#projectCode.项目ID \n"
			+ " from xmis.fas_项目金额调整表,xmis.fas_fitemss00,#projectCode \n"
			+ " WHERE xmis.fas_fitemss00.year = 2009  \n"
			+ " and  xmis.fas_项目金额调整表.citem_id = xmis.fas_fitemss00.citemcode  \n"
			+ " and xmis.fas_fitemss00.project_code = #projectCode.project_code \n"
			+ " union all \n"
			+ " SELECT  xmis.fas_GL_accvouch.year  \n"
			+ " ,xmis.fas_GL_accvouch.iperiod  \n"
			+ " ,xmis.fas_GL_accvouch.ino_id  \n"
			+ " ,SUM(mc) - SUM(md)  \n"
			+ " ,xmis.fas_GL_accvouch.cdigest  \n"
			+ " ,xmis.fas_GL_accvouch.dbill_date  \n"
			+ " ,xmis.fas_income.project_code   \n"
			+ " ,0  \n"
			+ " ,xmis.prj_项目.项目ID \n"
			+ " FROM xmis.fas_GL_accvouch , xmis.fas_income , xmis.fas_codeType ,xmis.prj_项目 \n"
			+ " WHERE xmis.fas_GL_accvouch.year = xmis.fas_income.year \n"
			+ " AND xmis.fas_GL_accvouch.iperiod = xmis.fas_income.iperiod \n"
			+ " AND xmis.fas_GL_accvouch.ino_id = xmis.fas_income.ino_id \n"
			+ " AND xmis.fas_GL_accvouch.citem_id = xmis.fas_income.citem_id   \n"
			+ " AND xmis.fas_codeType.type in ( 0,101 )  \n"
			+ " AND xmis.fas_codeType.type = xmis.fas_income.type \n"
			+ " AND xmis.fas_GL_accvouch.ccode = xmis.fas_codeType.ccode   \n"
			+ " AND xmis.fas_GL_accvouch.year = xmis.fas_codeType.year  \n"
			+ " AND xmis.fas_income.project_code = 项目编码  \n"
			+ " and 项目ID not in (select 项目ID from #projectCode) \n"
			+ " GROUP BY xmis.fas_GL_accvouch.year  \n"
			+ " ,xmis.fas_GL_accvouch.iperiod  \n"
			+ " ,xmis.fas_GL_accvouch.ino_id  \n"
			+ " ,xmis.fas_GL_accvouch.dbill_date  \n"
			+ " ,cdigest  \n"
			+ " ,xmis.fas_income.project_code   \n"
			+ " ,xmis.prj_项目.项目ID  \n"
			+ " HAVING  SUM(mc) - SUM(md) <> 0  \n"
			+ " ORDER BY xmis.fas_GL_accvouch.dbill_date \n"
			+ " select #resultWithoutContract.*,xmis.con_合同.合同ID as contractID,case when xmis.con_合同.简称 is null or rtrim(xmis.con_合同.简称)='' then xmis.con_合同.合同名称 else xmis.con_合同.简称 end as contractName,xmis.con_合同.乙方部门ID as deptID,xmis.con_合同.合同负责人 as empID \n"
			+ " into #result \n"
			+ " from #resultWithoutContract,xmis.con_合同  \n"
			+ " where #resultWithoutContract.projectID = xmis.con_合同.项目ID  \n"
			+ " and 合同类型ID = 1  \n"
			+ " and 父合同ID is null \n"
			+ " and 乙方部门ID is not null \n";

	public static String getFinancyOutpayRunningAccountList = " SELECT  2008 as year \n"
			+ " , convert(int, null) as iperiod \n"
			+ " , convert(int, null) as ino_id \n"
			+ " , SUM(payout_mb) AS MB \n"
			+ " , '2008期初余额' as cdigest \n"
			+ " , convert(datetime, '2008-01-01') as dbill_date  \n"
			+ " , project_code \n"
			+ " , 1 as flag \n"
			+ " , xmis.prj_项目.项目ID as projectID \n"
			+ " INTO #prevWithoutContract  \n"
			+ " FROM xmis.fas_qcjcb  \n"
			+ " ,xmis.fas_fitemss00  \n"
			+ " ,xmis.prj_项目  \n"
			+ " WHERE xmis.fas_fitemss00.year = 2008  \n"
			+ " and  xmis.fas_qcjcb.citem_id = xmis.fas_fitemss00.citemcode  \n"
			+ " and project_code = 项目编码  \n"
			+ " GROUP BY project_code,xmis.prj_项目.项目ID \n"
			+ " UNION ALL   \n"
			+ " SELECT xmis.fas_GL_accvouch.year  \n"
			+ " ,xmis.fas_GL_accvouch.iperiod  \n"
			+ " ,xmis.fas_GL_accvouch.ino_id  \n"
			+ " ,SUM(md - mc) pay_amt  \n"
			+ " ,xmis.fas_GL_accvouch.cdigest  \n"
			+ " ,xmis.fas_GL_accvouch.dbill_date  \n"
			+ " ,project_code  \n"
			+ " ,0   \n"
			+ " ,xmis.prj_项目.项目ID \n"
			+ " FROM xmis.fas_GL_accvouch  \n"
			+ " ,xmis.fas_fitemss00  \n"
			+ " ,xmis.fas_codeType  \n"
			+ " ,xmis.prj_项目 \n"
			+ " WHERE xmis.fas_GL_accvouch.year = xmis.fas_fitemss00.year     \n"
			+ " AND xmis.fas_GL_accvouch.citem_id = xmis.fas_fitemss00.citemcode   \n"
			+ " AND xmis.fas_fitemss00.bclose = 0          \n"
			+ " AND xmis.fas_GL_accvouch.iperiod > 0         \n"
			+ " AND xmis.fas_GL_accvouch.iperiod <= 12   \n"
			+ " AND NOT ( fas_GL_accvouch.year = 2011  AND fas_GL_accvouch.iperiod = 8  AND fas_GL_accvouch.ino_id IN ( 327, 466 ) )  \n"
			+ " AND xmis.fas_codeType.type = 1         \n"
			+ " AND xmis.fas_GL_accvouch.ccode = xmis.fas_codeType.ccode  \n"
			+ " AND xmis.fas_GL_accvouch.year = xmis.fas_codeType.year  \n"
			+ " AND project_code = 项目编码  \n"
			+ " GROUP BY xmis.fas_GL_accvouch.year  \n"
			+ " ,xmis.fas_GL_accvouch.iperiod  \n"
			+ " ,xmis.fas_GL_accvouch.ino_id  \n"
			+ " ,project_code ,  citem_id  \n"
			+ " ,xmis.fas_GL_accvouch.cdigest  \n"
			+ " ,xmis.fas_GL_accvouch.dbill_date   \n"
			+ " ,xmis.prj_项目.项目ID \n"
			+ " HAVING  SUM(md - mc) <> 0	 \n"
			+ " ORDER BY xmis.fas_GL_accvouch.dbill_date  \n"
			+ " select #prevWithoutContract.*,xmis.con_合同.合同ID as contractID,case when xmis.con_合同.简称 is null or rtrim(xmis.con_合同.简称)='' then xmis.con_合同.合同名称 else xmis.con_合同.简称 end as contractName,xmis.con_合同.乙方部门ID as deptID,xmis.con_合同.合同负责人 as empID  \n"
			+ " into #result  \n"
			+ " from #prevWithoutContract,xmis.con_合同   \n"
			+ " where #prevWithoutContract.projectID = xmis.con_合同.项目ID   \n"
			+ " and 合同类型ID = 1   \n"
			+ " and 父合同ID is null \n"
			+ " and 乙方部门ID is not null \n";
	
	public static String getResultStringWithPaging = 
		"\nSELECT * from #resultA "
		+ "WHERE row_no >= ? "
		+ " AND row_no < ? UNION ALL "
		+"\n\nSELECT MAX(row_no) as row_no,null as year,null as iperiod,null as ino_id,sum(MB) as MB,null,null,null,null,null,null,null,null,null from #resultA";


}
